### ISSUE TITLE
Error when merging whatsapp backups when there are corrupted databases (master)

### ISSUE THREAD

**Issue by hauck-jvsh** [sepinf-inc/IPED#1003]
When doing some test I found an error when processing the msgstore file inside a big UFDR. The strange thing is that the error does not occur when processing the msgstore.db files alone.
The following exception occurs

> org.apache.tika.exception.TikaException: WAExtractorException Exception
	at dpf.mg.udi.gpinf.whatsappextractor.WhatsAppParser.parseDB(WhatsAppParser.java:340)
	at dpf.mg.udi.gpinf.whatsappextractor.WhatsAppParser.parseAndCheckIfIsMainDb(WhatsAppParser.java:351)
	at dpf.mg.udi.gpinf.whatsappextractor.WhatsAppParser.parse(WhatsAppParser.java:196)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280)
	at dpf.sp.gpinf.indexer.parsers.IndexerDefaultParser.parse(IndexerDefaultParser.java:243)
	at dpf.sp.gpinf.indexer.io.ParsingReader$BackgroundParsing.run(ParsingReader.java:247)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: dpf.mg.udi.gpinf.whatsappextractor.WAExtractorException: org.sqlite.SQLiteException: [SQLITE_NOTADB]  File opened that is not a database file (file is not a database)
	at dpf.mg.udi.gpinf.whatsappextractor.ExtractorAndroid.extractChatList(ExtractorAndroid.java:96)
	at dpf.mg.udi.gpinf.whatsappextractor.Extractor.getChatList(Extractor.java:28)
	at dpf.mg.udi.gpinf.whatsappextractor.WhatsAppParser.extractChatList(WhatsAppParser.java:375)
	at dpf.mg.udi.gpinf.whatsappextractor.WhatsAppParser.parseDB(WhatsAppParser.java:335)
	... 10 more
Caused by: org.sqlite.SQLiteException: [SQLITE_NOTADB]  File opened that is not a database file (file is not a database)
	at org.sqlite.core.DB.newSQLException(DB.java:1012)
	at org.sqlite.core.DB.newSQLException(DB.java:1024)
	at org.sqlite.core.DB.throwex(DB.java:989)
	at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
	at org.sqlite.core.NativeDB.prepare(NativeDB.java:134)
	at org.sqlite.core.DB.prepare(DB.java:257)
	at org.sqlite.jdbc3.JDBC3Statement.executeQuery(JDBC3Statement.java:66)
	at org.sqlite.jdbc3.JDBC3Statement.executeQuery(JDBC3Statement.java:56)
	at org.sqlite.jdbc3.JDBC3DatabaseMetaData.getTables(JDBC3DatabaseMetaData.java:1844)
	at org.sqlite.jdbc3.JDBC3DatabaseMetaData.getColumns(JDBC3DatabaseMetaData.java:1205)
	at dpf.mg.udi.gpinf.whatsappextractor.ExtractorAndroid.databaseHasSortTimestamp(ExtractorAndroid.java:105)
	at dpf.mg.udi.gpinf.whatsappextractor.ExtractorAndroid.extractChatList(ExtractorAndroid.java:67)

**Comment by lfcnassif** [comment]
Thanks @hauck-jvsh. Could you check the "Parsing exception" line in log corresponding to above stacktrace? It contains file path and size, maybe it could be a zeroed file or folder with msgstore.db name...

**Comment by hauck-jvsh** [comment]
For sure, this the line.

> 2022-03-13 16:40:41	[WARN]	[indexer.parsers.IndexerDefaultParser]			ParsingThread-173 Parsing exception: TrisInIdem_Of0896-2020_Item_01.ufdr/Samsung GSM_SM-N975F Galaxy Note 10+.zip/data/data/com.whatsapp/databases/msgstore(2).db (28909569 bytes)		dpf.mg.udi.gpinf.whatsappextractor.WAExtractorException: org.sqlite.SQLiteException: [SQLITE_NOTADB]  File opened that is not a database file (file is not a database)

**Comment by hauck-jvsh** [comment]
There is also an error in the msgstore file that I processed alone and it worked.

> org.apache.tika.exception.TikaException: WAExtractorException Exception
	at dpf.mg.udi.gpinf.whatsappextractor.WhatsAppParser.parseDB(WhatsAppParser.java:340)
	at dpf.mg.udi.gpinf.whatsappextractor.WhatsAppParser.parseAndCheckIfIsMainDb(WhatsAppParser.java:351)
	at dpf.mg.udi.gpinf.whatsappextractor.WhatsAppParser.parse(WhatsAppParser.java:196)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280)
	at dpf.sp.gpinf.indexer.parsers.IndexerDefaultParser.parse(IndexerDefaultParser.java:243)
	at dpf.sp.gpinf.indexer.io.ParsingReader$BackgroundParsing.run(ParsingReader.java:247)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: dpf.mg.udi.gpinf.whatsappextractor.WAExtractorException: org.sqlite.SQLiteException: [SQLITE_CORRUPT]  The database disk image is malformed (database disk image is malformed)
	at dpf.mg.udi.gpinf.whatsappextractor.ExtractorAndroid.extractChatList(ExtractorAndroid.java:96)
	at dpf.mg.udi.gpinf.whatsappextractor.Extractor.getChatList(Extractor.java:28)
	at dpf.mg.udi.gpinf.whatsappextractor.WhatsAppParser.extractChatList(WhatsAppParser.java:375)
	at dpf.mg.udi.gpinf.whatsappextractor.WhatsAppParser.parseDB(WhatsAppParser.java:335)
	... 10 more
Caused by: org.sqlite.SQLiteException: [SQLITE_CORRUPT]  The database disk image is malformed (database disk image is malformed)
	at org.sqlite.core.DB.newSQLException(DB.java:1012)
	at org.sqlite.core.DB.newSQLException(DB.java:1024)
	at org.sqlite.core.DB.throwex(DB.java:989)
	at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
	at org.sqlite.core.NativeDB.prepare(NativeDB.java:134)
	at org.sqlite.core.DB.prepare(DB.java:257)
	at org.sqlite.jdbc3.JDBC3Statement.executeQuery(JDBC3Statement.java:66)
	at org.sqlite.jdbc3.JDBC3Statement.executeQuery(JDBC3Statement.java:56)
	at org.sqlite.jdbc3.JDBC3DatabaseMetaData.getTables(JDBC3DatabaseMetaData.java:1844)
	at org.sqlite.jdbc3.JDBC3DatabaseMetaData.getColumns(JDBC3DatabaseMetaData.java:1205)
	at dpf.mg.udi.gpinf.whatsappextractor.ExtractorAndroid.databaseHasSortTimestamp(ExtractorAndroid.java:105)
	at dpf.mg.udi.gpinf.whatsappextractor.ExtractorAndroid.extractChatList(ExtractorAndroid.java:67)
	... 13 more
2022-03-13 16:41:28	[WARN]	[indexer.parsers.IndexerDefaultParser]			ParsingThread-210 Parsing exception: TrisInIdem_Of0896-2020_Item_01.ufdr/Samsung GSM_SM-N975F Galaxy Note 10+.zip/data/data/com.whatsapp/databases/msgstore.db (2147483647 bytes)		dpf.mg.udi.gpinf.whatsappextractor.WAExtractorException: org.sqlite.SQLiteException: [SQLITE_CORRUPT]  The database disk image is malformed (database disk image is malformed)

**Comment by lfcnassif** [comment]
Is this happening just on master or also with 3.18.x?

**Comment by hauck-jvsh** [comment]
I didn't test on 3.18.x, I can test this tomorrow.

**Comment by hauck-jvsh** [comment]
I found that the msgstore.db actually has  2.176.393.216, but in the log it appears with 2.147.483.647 bytes.

**Comment by lfcnassif** [comment]
> I found that the msgstore.db actually has 2.176.393.216, but in the log it appears with 2.147.483.647 bytes. This is exactly 2^31 -1, the max int value.

I'll check if this is a zip4j issue or iped one.
