### ISSUE TITLE
Aborting ClassCastException in GraphTask

### ISSUE THREAD

**Issue by fmpfeifer** [sepinf-inc/IPED#1008]
While processing an UFDR file from a Android device, the processing aborted with an Exception in the GraphTask:

```
2022-03-14 15:08:29	[ERROR]	[gpinf.indexer.IndexFiles]			Processing Error: 
java.lang.Exception: Worker-12 Error while processing Relatorio/_DecodedData/Chat/Chat_b8f57994-efd3-48c2-acb1-554347cd2120/InstantMessage_dc63f067-e291-48f7-90ad-cd90a8a6e3e8/Contact_Alisso (655bytes)
	at dpf.sp.gpinf.indexer.process.Worker.process(Worker.java:182) ~[iped-engine-3.18.13.jar:?]
	at dpf.sp.gpinf.indexer.process.Worker.run(Worker.java:235) ~[iped-engine-3.18.13.jar:?]
Caused by: java.lang.ClassCastException: java.util.LinkedHashMap$Entry cannot be cast to java.util.HashMap$TreeNode
	at java.util.HashMap$TreeNode.moveRootToFront(Unknown Source) ~[?:1.8.0_152]
	at java.util.HashMap$TreeNode.treeify(Unknown Source) ~[?:1.8.0_152]
	at java.util.HashMap.treeifyBin(Unknown Source) ~[?:1.8.0_152]
	at java.util.HashMap.putVal(Unknown Source) ~[?:1.8.0_152]
	at java.util.HashMap.put(Unknown Source) ~[?:1.8.0_152]
	at java.util.Collections$SetFromMap.add(Unknown Source) ~[?:1.8.0_152]
	at br.gov.pf.labld.graph.GraphFileWriter$CSVWriter.write(GraphFileWriter.java:614) ~[iped-engine-3.18.13.jar:?]
	at br.gov.pf.labld.graph.GraphFileWriter.writeNodeId(GraphFileWriter.java:413) ~[iped-engine-3.18.13.jar:?]
	at br.gov.pf.labld.graph.GraphFileWriter.writeNode(GraphFileWriter.java:259) ~[iped-engine-3.18.13.jar:?]
	at br.gov.pf.labld.graph.GraphTask.writePersonNode(GraphTask.java:593) ~[iped-engine-3.18.13.jar:?]
	at br.gov.pf.labld.graph.GraphTask.processContacts(GraphTask.java:700) ~[iped-engine-3.18.13.jar:?]
	at br.gov.pf.labld.graph.GraphTask.processEvidence(GraphTask.java:229) ~[iped-engine-3.18.13.jar:?]
	at br.gov.pf.labld.graph.GraphTask.process(GraphTask.java:217) ~[iped-engine-3.18.13.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processMonitorTimeout(AbstractTask.java:222) ~[iped-engine-3.18.13.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:159) ~[iped-engine-3.18.13.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:201) ~[iped-engine-3.18.13.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:167) ~[iped-engine-3.18.13.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:201) ~[iped-engine-3.18.13.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:167) ~[iped-engine-3.18.13.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:201) ~[iped-engine-3.18.13.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:167) ~[iped-engine-3.18.13.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:201) ~[iped-engine-3.18.13.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:167) ~[iped-engine-3.18.13.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:201) ~[iped-engine-3.18.13.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:167) ~[iped-engine-3.18.13.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:201) ~[iped-engine-3.18.13.jar:?]
```

I can provide the UFDR file for testing, if needed (it is about 3 GB in size).
Disabling the graph generation was enought to get it done for me.

**Comment by fmpfeifer** [comment]
> Thanks @fmpfeifer for reporting. Could you send a link to the triggering UFDR to me using Teams?

Yes, done. Thanks
