### ISSUE TITLE
Support more date formats when processing UFDR files from PA 7.54

### ISSUE THREAD

**Issue by aberenguel** [sepinf-inc/IPED#1049]
Got this exception when processing an UFDR generated by PA 7.54
It happens in both 3.18.17 and 4.0.0-snapshot versions.

```
java.text.ParseException: Unparseable date: "10/08/2014 23:22:31 +00:00"
	at java.text.DateFormat.parse(DateFormat.java:366)
	at dpf.sp.gpinf.indexer.datasource.UfedXmlReader$XMLContentHandler.endElement(UfedXmlReader.java:669)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1782)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2967)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at dpf.sp.gpinf.indexer.datasource.UfedXmlReader.read(UfedXmlReader.java:207)
	at dpf.sp.gpinf.indexer.datasource.UfedXmlReader.read(UfedXmlReader.java:185)
	at dpf.sp.gpinf.indexer.datasource.ItemProducer.run(ItemProducer.java:124)
```

**Comment by lfcnassif** [comment]
> It happens in both 3.18.17 and 4.0.0-snapshot versions.

Do you mean 3.18.14, right?

Just to confirm, processing didn't abort and you saw above in processing log?

I've just pushed a possible solution to 3.18.x branch. Please test this snapshot with your ufdr file:
https://github.com/sepinf-inc/IPED/actions/runs/2096108158

**Comment by lfcnassif** [comment]
One last thing, could you confirm if that date format is dd/MM/yyyy or MM/dd/yyyy?

**Comment by aberenguel** [comment]
I think it is dd/MM/yyyy

From this related report
```xml
<item id="4b63ee40-2f3b-4919-b2ba-f0a5fa7fcdf8" name="MSISDN" group="Last known use: 10/08/2014 23:22:31 +00:00" sourceExtraction="0" systemtype="System.String"><![CDATA[XXXXXXXXXX]]></item>
```

From another report
```xml
<item id="4298771f-de1e-42e6-879e-1848b475ac6a" name="MSISDN" group="Last known use: 19/10/2021 11:08:14 +00:00" sourceExtraction="4" systemtype="System.String"><![CDATA[XXXXXXXXXXXx]]></item>
```

**Comment by lfcnassif** [comment]
Great! Let me know if the pushed commit [56ceba6](https://github.com/sepinf-inc/IPED/commit/56ceba663d785c780e1d86cedfc11fb542a3b602) fixes the exception.

**Comment by aberenguel** [comment]
It fixed. Tested on snapshot of 56ceba6 and this commit cherry-picked into master.

**Comment by lfcnassif** [comment]
Thank you!
