### ISSUE TITLE
Exception in IPEDReader.copyBookmarksToReport

### ISSUE THREAD

**Issue by aberenguel** [sepinf-inc/IPED#1057]
I processed a case with one UFDR. In order to listen the audios of WhatsApp chats in the browser, I tried to generate a report with a bookmark containing all items. In the end of report generation, this exception was thrown and the generation failed.

It happened with iped-3.18.14
```
java.lang.Exception: Error decoding datasource /tmp/report577120878047144722.iped
	at dpf.sp.gpinf.indexer.datasource.ItemProducer.run(ItemProducer.java:154) ~[iped-engine-3.18.14.jar:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 521390 out of bounds for length 521390
	at dpf.sp.gpinf.indexer.search.Marcadores.addLabel(Marcadores.java:169) ~[iped-engine-3.18.14.jar:?]
	at dpf.sp.gpinf.indexer.datasource.IPEDReader.copyBookmarksToReport(IPEDReader.java:241) ~[iped-engine-3.18.14.jar:?]
	at dpf.sp.gpinf.indexer.datasource.IPEDReader.processBookmark(IPEDReader.java:215) ~[iped-engine-3.18.14.jar:?]
	at dpf.sp.gpinf.indexer.datasource.IPEDReader.read(IPEDReader.java:136) ~[iped-engine-3.18.14.jar:?]
	at dpf.sp.gpinf.indexer.datasource.ItemProducer.run(ItemProducer.java:124) ~[iped-engine-3.18.14.jar:?]
```

So, I replaced the iped-engine.jar with the file provided in 56ceba66 commit build. The exception was:
```
java.lang.Exception: Error decoding datasource /tmp/report2132045484148108483.iped
	at dpf.sp.gpinf.indexer.datasource.ItemProducer.run(ItemProducer.java:154) ~[iped-engine-3.18.14.jar:?]
Caused by: java.lang.NumberFormatException: For input string: "ng.ArrayIndexOutOfBoundsException:"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_321]
	at java.lang.Integer.parseInt(Integer.java:580) ~[?:1.8.0_321]
	at java.lang.Integer.valueOf(Integer.java:766) ~[?:1.8.0_321]
	at dpf.sp.gpinf.indexer.datasource.IPEDReader.copyBookmarksToReport(IPEDReader.java:262) ~[iped-engine-3.18.14.jar:?]
	at dpf.sp.gpinf.indexer.datasource.IPEDReader.processBookmark(IPEDReader.java:224) ~[iped-engine-3.18.14.jar:?]
	at dpf.sp.gpinf.indexer.datasource.IPEDReader.read(IPEDReader.java:143) ~[iped-engine-3.18.14.jar:?]
	at dpf.sp.gpinf.indexer.datasource.ItemProducer.run(ItemProducer.java:124) ~[iped-engine-3.18.14.jar:?]

```

**Comment by lfcnassif** [comment]
Could you check in your original case what is the last/biggest item ID in case? Maybe this is related to #1033...

**Comment by lfcnassif** [comment]
@aberenguel please test commit above, I wrote it in a hurry, not sure if it is fine. If report generation works, please also test the top-right check/uncheck all items checkbox in analysis UI.

**Comment by aberenguel** [comment]
It is also occuring in IPED-4.0.0
```
java.lang.Exception: Error decoding datasource /tmp/report3518429781352829350.iped
	at dpf.sp.gpinf.indexer.datasource.ItemProducer.run(ItemProducer.java:153) ~[iped-engine-4.0.0-snapshot.jar:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 226841 out of bounds for length 226841
	at dpf.sp.gpinf.indexer.search.Bookmarks.addBookmark(Bookmarks.java:175) ~[iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.datasource.IPEDReader.copyBookmarksToReport(IPEDReader.java:251) ~[iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.datasource.IPEDReader.processBookmark(IPEDReader.java:225) ~[iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.datasource.IPEDReader.read(IPEDReader.java:144) ~[iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.datasource.ItemProducer.run(ItemProducer.java:123) ~[iped-engine-4.0.0-snapshot.jar:?]
```

**Comment by aberenguel** [comment]
> @aberenguel please test commit above, I wrote it in a hurry, not sure if it is fine. If report generation works, please also test the top-right check/uncheck all items checkbox in analysis UI.

I applied the 26561b0decba17c48b6804ed3d929ce9b0102856 change in master branch and it solved.

The top-right check/uncheck all items checkbox is working correctly in IPED-4.

PS: A thing I noticed is that issue #1033 also occured in IPED-4

**Comment by lfcnassif** [comment]
Thanks @aberenguel for testing, I'll apply the fix.
