### ISSUE TITLE
JSON ParserException in VoskTranscriptTask on Linux (master)

### ISSUE THREAD

**Issue by aberenguel** [sepinf-inc/IPED#1058]
Using the master branch:

```
java.lang.Exception: Worker-42 Error while processing voice_instructions.zip>>ARRIVED.ogg (7238bytes)
        at dpf.sp.gpinf.indexer.process.Worker.process(Worker.java:176) ~[iped-engine-4.0.0-snapshot.jar:?]
        at dpf.sp.gpinf.indexer.process.Worker.run(Worker.java:261) ~[iped-engine-4.0.0-snapshot.jar:?]
Caused by: org.json.simple.parser.ParseException
        at org.json.simple.parser.JSONParser.parse(JSONParser.java:257) ~[json-simple-1.1.1.jar:?]
        at org.json.simple.parser.JSONParser.parse(JSONParser.java:81) ~[json-simple-1.1.1.jar:?]
        at org.json.simple.parser.JSONParser.parse(JSONParser.java:75) ~[json-simple-1.1.1.jar:?]
        at dpf.sp.gpinf.indexer.process.task.transcript.VoskTranscriptTask.decodeFromJson(VoskTranscriptTask.java:136) ~[iped-engine-4.0.0-snapshot.jar:?]
        at dpf.sp.gpinf.indexer.process.task.transcript.VoskTranscriptTask.transcribeWav(VoskTranscriptTask.java:114) ~[iped-engine-4.0.0-snapshot.jar:?]
        at dpf.sp.gpinf.indexer.process.task.transcript.AbstractTranscriptTask.process(AbstractTranscriptTask.java:298) ~[iped-engine-4.0.0-snapshot.jar:?]
        at dpf.sp.gpinf.indexer.process.task.transcript.AudioTranscriptTask.process(AudioTranscriptTask.java:41) ~[iped-engine-4.0.0-snapshot.jar:?]
        at dpf.sp.gpinf.indexer.process.task.AbstractTask.processMonitorTimeout(AbstractTask.java:243) ~[iped-engine-4.0.0-snapshot.jar:?]
        at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:180) ~[iped-engine-4.0.0-snapshot.jar:?]
        at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:222) ~[iped-engine-4.0.0-snapshot.jar:?]
        at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188) ~[iped-engine-4.0.0-snapshot.jar:?]
        at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:222) ~[iped-engine-4.0.0-snapshot.jar:?]
        at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188) ~[iped-engine-4.0.0-snapshot.jar:?]
        at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:222) ~[iped-engine-4.0.0-snapshot.jar:?]
        at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188) ~[iped-engine-4.0.0-snapshot.jar:?]
        at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:222) ~[iped-engine-4.0.0-snapshot.jar:?]
        at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188) ~[iped-engine-4.0.0-snapshot.jar:?]
        at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:222) ~[iped-engine-4.0.0-snapshot.jar:?]
        at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188) ~[iped-engine-4.0.0-snapshot.jar:?]
        at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:222) ~[iped-engine-4.0.0-snapshot.jar:?]
        at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188) ~[iped-engine-4.0.0-snapshot.jar:?]
        at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:222) ~[iped-engine-4.0.0-snapshot.jar:?]
        at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188) ~[iped-engine-4.0.0-snapshot.jar:?]
        at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:222) ~[iped-engine-4.0.0-snapshot.jar:?]
        at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188) ~[iped-engine-4.0.0-snapshot.jar:?]
        at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:222) ~[iped-engine-4.0.0-snapshot.jar:?]
        at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188) ~[iped-engine-4.0.0-snapshot.jar:?]
        at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:222) ~[iped-engine-4.0.0-snapshot.jar:?]
        at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188) ~[iped-engine-4.0.0-snapshot.jar:?]
        at dpf.sp.gpinf.indexer.process.Worker.process(Worker.java:167) ~[iped-engine-4.0.0-snapshot.jar:?]
        ... 1 more
```

I debbuged the input string and caught:
```json
{
  "result" : [{
      "conf" : 0,976572,
      "end" : 0,570000,
      "start" : 0,060000,
      "word" : "faça"
    }, {
      "conf" : 0,724241,
      "end" : 0,690000,
      "start" : 0,570000,
      "word" : "o"
    }, {
      "conf" : 1,000000,
      "end" : 1,380000,
      "start" : 0,690000,
      "word" : "retorno"
    }],
  "text" : "faça o retorno"
}
```

I think the error is in comma being used as decimal point

**Comment by aberenguel** [comment]
I think it is related to locale in Linux

```sh
$ LC_ALL=pt_BR.utf8 awk 'BEGIN{p=236 * 1.00; printf "%0.2f", p}'
236,00

LC_ALL=en_US.utf8 awk 'BEGIN{p=236 * 1.00; printf "%0.2f", p}'
236.00
```

**Comment by aberenguel** [comment]
Setting the env var `LC_NUMERIC=en_US.utf8` solved. 

It is a bug in Vosk Library. It is not possible to set this var in Java in a straight way. For now, I think that setting this var should be mentioned as suggestion in IPED.

**Comment by aberenguel** [comment]
This has already been mentioned in https://github.com/alphacep/vosk-api/issues/808

**Comment by lfcnassif** [comment]
Thanks @aberenguel! Maybe we can make an ugly workaround before the official fix in upstream issue, since this json structure is pretty simple...

**Comment by lfcnassif** [comment]
@tc-wleite have you had this issue on your Windows OS? What is your locale?

**Comment by tc-wleite** [comment]
> @tc-wleite have you had this issue on your Windows OS? What is your locale?

No, I haven't. 
My locale is pt_BR.

**Comment by lfcnassif** [comment]
> My locale is pt_BR.

Just to confirm, Windows locale, right?

**Comment by tc-wleite** [comment]
> Just to confirm, Windows locale, right?

Yes. I checked using this command:

```
PS C:\Users\Wladimir> Get-WinSystemLocale

LCID             Name             DisplayName
----             ----             -----------
1046             pt-BR            Português (Brasil)
```

**Comment by aberenguel** [comment]
> @aberenguel I've just pushed commit [1469303](https://github.com/sepinf-inc/IPED/commit/14693036bf443d1d69531a8d3ab4eefa187c19d8) with a possible workaround, could you test on your system?

Just tested! It worked perfectly. Thanks, @lfcnassif !

**Comment by lfcnassif** [comment]
Thanks for testing!

**Comment by lfcnassif** [comment]
> It is not possible to set this var in Java in a straight way

Just a tip about this, when #771 is merged, this new method will be avaiilable: https://github.com/sepinf-inc/IPED/pull/771/commits/e6800748d599cf7a0d0c57ae96d6e9595a91eae0
