### ISSUE TITLE
Processing abort with a java swing exception

### ISSUE THREAD

**Issue by hauck-jvsh** [sepinf-inc/IPED#1063]
I was processing an evidence when the processing aborts with the following error:

> java.lang.IllegalArgumentException: TextHitInfo is out of range
	at java.desktop/java.awt.font.TextLayout.checkTextHit(TextLayout.java:776)
	at java.desktop/java.awt.font.TextLayout.getCaretInfo(TextLayout.java:1216)
	at java.desktop/java.awt.font.TextLayout.getCaretInfo(TextLayout.java:1318)
	at java.desktop/javax.swing.text.GlyphPainter2.getSpan(GlyphPainter2.java:82)
	at java.desktop/javax.swing.text.GlyphView.getPartialSpan(GlyphView.java:323)
	at java.desktop/javax.swing.text.GlyphView.getMinimumSpan(GlyphView.java:550)
	at java.desktop/javax.swing.text.ParagraphView.calculateMinorAxisRequirements(ParagraphView.java:717)
	at java.desktop/javax.swing.text.html.ParagraphView.calculateMinorAxisRequirements(ParagraphView.java:162)
	at java.desktop/javax.swing.text.BoxView.checkRequests(BoxView.java:936)
	at java.desktop/javax.swing.text.BoxView.getMinimumSpan(BoxView.java:569)
	at java.desktop/javax.swing.text.html.ParagraphView.getMinimumSpan(ParagraphView.java:275)
	at java.desktop/javax.swing.text.BoxView.calculateMinorAxisRequirements(BoxView.java:904)
	at java.desktop/javax.swing.text.html.BlockView.calculateMinorAxisRequirements(BlockView.java:146)
	at java.desktop/javax.swing.text.html.TableView$CellView.calculateMinorAxisRequirements(TableView.java:1786)
	at java.desktop/javax.swing.text.BoxView.checkRequests(BoxView.java:936)
	at java.desktop/javax.swing.text.BoxView.getMinimumSpan(BoxView.java:569)
	at java.desktop/javax.swing.text.html.BlockView.getMinimumSpan(BlockView.java:378)
	at java.desktop/javax.swing.text.html.TableView.checkSingleColumnCell(TableView.java:461)
	at java.desktop/javax.swing.text.html.TableView.calculateColumnRequirements(TableView.java:424)
	at java.desktop/javax.swing.text.html.TableView.calculateMinorAxisRequirements(TableView.java:546)
	at java.desktop/javax.swing.text.BoxView.checkRequests(BoxView.java:936)
	at java.desktop/javax.swing.text.BoxView.getMinimumSpan(BoxView.java:569)
	at java.desktop/javax.swing.text.BoxView.calculateMinorAxisRequirements(BoxView.java:904)
	at java.desktop/javax.swing.text.html.BlockView.calculateMinorAxisRequirements(BlockView.java:146)
	at java.desktop/javax.swing.text.BoxView.checkRequests(BoxView.java:936)
	at java.desktop/javax.swing.text.BoxView.getMinimumSpan(BoxView.java:569)
	at java.desktop/javax.swing.text.html.BlockView.getMinimumSpan(BlockView.java:378)
	at java.desktop/javax.swing.text.BoxView.calculateMinorAxisRequirements(BoxView.java:904)
	at java.desktop/javax.swing.text.html.BlockView.calculateMinorAxisRequirements(BlockView.java:146)
	at java.desktop/javax.swing.text.BoxView.checkRequests(BoxView.java:936)
	at java.desktop/javax.swing.text.BoxView.getPreferredSpan(BoxView.java:546)
	at java.desktop/javax.swing.text.html.BlockView.getPreferredSpan(BlockView.java:362)
	at java.desktop/javax.swing.plaf.basic.BasicHTML$Renderer.<init>(BasicHTML.java:425)
	at java.desktop/javax.swing.plaf.basic.BasicHTML.createHTMLView(BasicHTML.java:72)
	at java.desktop/javax.swing.plaf.basic.BasicHTML.updateRenderer(BasicHTML.java:219)
	at java.desktop/javax.swing.plaf.basic.BasicLabelUI.propertyChange(BasicLabelUI.java:487)
	at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:341)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:333)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:266)
	at java.desktop/java.awt.Component.firePropertyChange(Component.java:8731)
	at java.desktop/javax.swing.JLabel.setText(JLabel.java:324)
	at dpf.sp.gpinf.indexer.process.ProgressFrame.propertyChange(ProgressFrame.java:171)
	at dpf.sp.gpinf.indexer.WorkerProvider.firePropertyChange(WorkerProvider.java:34)
	at dpf.sp.gpinf.indexer.process.Manager.monitorProcessing(Manager.java:544)
	at dpf.sp.gpinf.indexer.process.Manager.process(Manager.java:262)
	at dpf.sp.gpinf.indexer.Main.startManager(Main.java:154)
	at dpf.sp.gpinf.indexer.Main.execute(Main.java:210)
	at dpf.sp.gpinf.indexer.Main.main(Main.java:283)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at dpf.sp.gpinf.indexer.util.CustomLoader.run(CustomLoader.java:65)
	at dpf.sp.gpinf.indexer.Main.main(Main.java:279)

I just run it again and it worked, so I think it rarely occurs.

**Comment by lfcnassif** [comment]
Thanks for reporting @hauck-jvsh.
