### ISSUE TITLE
Index XX is out of bounds for axis 0 from NSFWNudityDetectTask.py

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#1077]
I catch this on 4.0-alpha while testing other things:
```
2022-04-26 16:47:58	[WARN]	[process.task.PythonTask]			Exception from NSFWNudityDetectTask.py on /XXXXXX.jpg: jep.JepException: <class 'IndexError'>: index 54 is out of bounds for axis 0 with size 54
jep.JepException: <class 'IndexError'>: index 54 is out of bounds for axis 0 with size 54
	at E:\git\iped\target\release\iped-4.0.0-snapshot\conf\scripts\NSFWNudityDetectTask.processImages(NSFWNudityDetectTask.py:254) ~[?:?]
	at E:\git\iped\target\release\iped-4.0.0-snapshot\conf\scripts\NSFWNudityDetectTask.process(NSFWNudityDetectTask.py:207) ~[?:?]
	at jep.Jep.invoke(Native Method) ~[jep-4.0.3.jar:?]
	at jep.Jep.invoke(Jep.java:257) ~[jep-4.0.3.jar:?]
	at dpf.sp.gpinf.indexer.process.task.PythonTask.process(PythonTask.java:298) [iped-engine-4.0.0-snapshot.jar:?]
```

**Comment by lfcnassif** [comment]
This is looking strange, maybe is related with multithreading issues...

**Comment by lfcnassif** [comment]
Ok this seems to be happening since python scripts were converted to classes in master, 1 year ago... I had a hard time debugging this (checked out a number of versions to track when the issue started), but hopefully I found 2 different issues, one related to multithreading. This module also became much more slower than it was before. I'm still evaluating the best solution...

**Comment by lfcnassif** [comment]
I'm updating the issue title to a better one.

**Comment by lfcnassif** [comment]
For those starting with python (like me), I recommend reading this about variables scopes and classes: https://docs.python.org/3/tutorial/classes.html
