### ISSUE TITLE
Few FaceRecognition runtime exceptions in interprocess communication

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#1090]
While processing a medium size case, this was printed a few times in log:
```
2022-05-04 15:53:25	[WARN]	[process.task.PythonTask]			Exception from FaceRecognitionTask.py on /XXXXXX.JPG: jep.JepException: <class 'ValueError'>: invalid literal for int() with base 10: ''
jep.JepException: <class 'ValueError'>: invalid literal for int() with base 10: ''
	at E:\git\iped\target\release\iped-4.0.0-snapshot\conf\scripts\FaceRecognitionTask.process(FaceRecognitionTask.py:254) ~[?:?]
	at jep.Jep.invoke(Native Method) ~[jep-4.0.3.jar:?]
	at jep.Jep.invoke(Jep.java:257) ~[jep-4.0.3.jar:?]
	at dpf.sp.gpinf.indexer.process.task.PythonTask.process(PythonTask.java:310) [iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processMonitorTimeout(AbstractTask.java:251) [iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:181) [iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:208) [iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.PythonTask.sendToNextTaskSuper(PythonTask.java:266) [iped-engine-4.0.0-snapshot.jar:?]
	at jep.Jep.invoke(Native Method) ~[jep-4.0.3.jar:?]
	at jep.Jep.invoke(Jep.java:257) [jep-4.0.3.jar:?]
	at dpf.sp.gpinf.indexer.process.task.PythonTask.sendToNextTask(PythonTask.java:277) [iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:189) [iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:208) [iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:189) [iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:208) [iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:189) [iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:208) [iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:189) [iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:208) [iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:189) [iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:208) [iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:189) [iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:208) [iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:189) [iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:208) [iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:189) [iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:208) [iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:189) [iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:208) [iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:189) [iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:208) [iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:189) [iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:208) [iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:189) [iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:208) [iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:189) [iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:208) [iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:189) [iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:208) [iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:189) [iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:208) [iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:189) [iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:208) [iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:189) [iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:208) [iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:189) [iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:208) [iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:189) [iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:208) [iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:189) [iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:208) [iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:189) [iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:208) [iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:189) [iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:208) [iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:189) [iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:208) [iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:189) [iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:208) [iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:189) [iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:208) [iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:189) [iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:208) [iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:189) [iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.Worker.process(Worker.java:176) [iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.Worker.run(Worker.java:262) [iped-engine-4.0.0-snapshot.jar:?]
Traceback (most recent call last):
  File "E:\git\iped\target\release\iped-4.0.0-snapshot\conf\scripts\FaceRecognitionTask.py", line 85, in pingExternalProcess
    print(ping, file=proc.stdin, flush=True)
OSError: [Errno 22] Invalid argument
```

**Comment by lfcnassif** [comment]
related to this line: https://github.com/sepinf-inc/IPED/blob/34c5826481a0f3e031be240397b2d8cf079e4513/iped-app/resources/config/conf/scripts/FaceRecognitionTask.py#L254

**Comment by lfcnassif** [comment]
I added a simple workaround, seems face recognition library is rarely exiting/crashing the external process in this line:
https://github.com/sepinf-inc/IPED/blob/293a3c21cc5b85163a07ca7a8010aebb4a0e85e8/iped-app/resources/config/conf/scripts/FaceRecognitionProcess.py#L105
Adding a try catch around that and making `face_locations = []` in the catch has no effect...
