### ISSUE TITLE
TskCoreException when reading files after TSK-4.11.1 upgrade

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#1099]
After #232, sometimes, when processing is finishing, this exception is being thrown:
```
2022-04-19 11:36:06	[ERROR]	[sleuthkit.datamodel.SleuthkitCase]			Error freeing case handle.
org.sleuthkit.datamodel.TskCoreException: No entry for case SingleUser:F:\xxxxxxxxxxx\sleuth.db in cache. Case may have been closed
	at org.sleuthkit.datamodel.SleuthkitJNI$HandleCache.getCaseHandles(SleuthkitJNI.java:193) ~[sleuthkit-4.11.1-p2.jar:?]
	at org.sleuthkit.datamodel.SleuthkitJNI$HandleCache.closeHandlesAndClearCache(SleuthkitJNI.java:308) ~[sleuthkit-4.11.1-p2.jar:?]
	at org.sleuthkit.datamodel.SleuthkitJNI$CaseDbHandle.free(SleuthkitJNI.java:411) ~[sleuthkit-4.11.1-p2.jar:?]
	at org.sleuthkit.datamodel.SleuthkitCase.close(SleuthkitCase.java:10473) [sleuthkit-4.11.1-p2.jar:?]
	at org.sleuthkit.datamodel.SleuthkitCase.finalize(SleuthkitCase.java:10451) [sleuthkit-4.11.1-p2.jar:?]
	at java.lang.System$2.invokeFinalize(System.java:2125) [?:?]
	at java.lang.ref.Finalizer.runFinalizer(Finalizer.java:87) [?:?]
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:171) [?:?]
```
That also happened to @hauck-jvsh when changing the processing queue.

And yesterday, while testing the analysis UI, file opening stopped to work. Looking at the log, this is the first exception thrown:
```
Caused by: org.sleuthkit.datamodel.ReadContentInputStream$ReadContentInputStreamException: Error reading file 'xxxxxxx-xxxxxx.eml' (id=323762) at offset 695907.
	at org.sleuthkit.datamodel.ReadContentInputStream.read(ReadContentInputStream.java:105)
	at dpf.sp.gpinf.indexer.sleuthkit.SleuthkitInputStream.read(SleuthkitInputStream.java:32)
	at org.apache.tika.io.ProxyInputStream.read(ProxyInputStream.java:99)
	... 26 more
Caused by: org.sleuthkit.datamodel.TskCoreException: Invalid file handle.
	at org.sleuthkit.datamodel.SleuthkitJNI.readFile(SleuthkitJNI.java:1492)
	at org.sleuthkit.datamodel.FsContent.readInt(FsContent.java:222)
	at org.sleuthkit.datamodel.AbstractFile.read(AbstractFile.java:1003)
	at org.sleuthkit.datamodel.ReadContentInputStream.read(ReadContentInputStream.java:89)
	... 28 more
```
And later opening other files:
```
Caused by: org.sleuthkit.datamodel.ReadContentInputStream$ReadContentInputStreamException: Error reading file 'xxxxxxx-xxxxxx.eml' (id=228018) at offset 0.
	at org.sleuthkit.datamodel.ReadContentInputStream.read(ReadContentInputStream.java:105)
	at dpf.sp.gpinf.indexer.sleuthkit.SleuthkitInputStream.read(SleuthkitInputStream.java:32)
	at org.apache.tika.io.ProxyInputStream.read(ProxyInputStream.java:99)
	... 23 more
Caused by: org.sleuthkit.datamodel.TskCoreException: No entry for case SingleUser:E:\xxxxxxxxxxx\sleuth.db in cache. Case may have been closed
	at org.sleuthkit.datamodel.SleuthkitJNI$HandleCache.getCaseHandles(SleuthkitJNI.java:193)
	at org.sleuthkit.datamodel.SleuthkitJNI.openFile(SleuthkitJNI.java:1251)
	at org.sleuthkit.datamodel.FsContent.loadFileHandle(FsContent.java:186)
	at org.sleuthkit.datamodel.FsContent.readInt(FsContent.java:221)
	at org.sleuthkit.datamodel.AbstractFile.read(AbstractFile.java:1003)
	at org.sleuthkit.datamodel.ReadContentInputStream.read(ReadContentInputStream.java:89)
```

**Comment by aberenguel** [comment]
It also happened to me.
Sometimes the process crashes with the log `free(): invalid pointer`. It generates an `hs_err_pidXXX.log`.
This part is interesting:
```
--------------  T H R E A D  ---------------

Current thread (0x00007feab03ca000):  JavaThread "Finalizer" daemon [_thread_in_native, id=592497, stack(0x00007fea523eb000,0x00007fea524eb000)]

Stack: [0x00007fea523eb000,0x00007fea524eb000],  sp=0x00007fea524e9490,  free space=1017k
Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libbfio.so.1+0x1ce13]  libbfio_file_is_open+0x13

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  org.sleuthkit.datamodel.SleuthkitJNI.closeImgNat(J)V+0
j  org.sleuthkit.datamodel.SleuthkitJNI$HandleCache.closeHandlesAndClearCache(Ljava/lang/String;)V+386
j  org.sleuthkit.datamodel.SleuthkitJNI$CaseDbHandle.free()V+17
j  org.sleuthkit.datamodel.SleuthkitCase.close()V+48
j  org.sleuthkit.datamodel.SleuthkitCase.finalize()V+1
j  java.lang.System$2.invokeFinalize(Ljava/lang/Object;)V+1 java.base@11.0.15
j  java.lang.ref.Finalizer.runFinalizer(Ljdk/internal/misc/JavaLangAccess;)V+101 java.base@11.0.15
j  java.lang.ref.Finalizer$FinalizerThread.run()V+46 java.base@11.0.15
v  ~StubRoutines::call_stub
```
It seems the sleuthkitCase is being collected by GC. It triggers to close the case.

**Comment by aberenguel** [comment]
I've seen that everytime a case is open it creates an entry in `org.sleuthkit.datamodel.SleuthkitJNI.HandleCache.createCaseHandleCache(String)`

But the case is open is several places:
1) In `dpf.sp.gpinf.indexer.search.IPEDSource` constructor
2) In `dpf.sp.gpinf.indexer.sleuthkit.SleuthkitInputStreamFactory.getSleuthkitCase()`

When the stream is garbage collected, it closes the case (the case is garbage collected too) and remove the global cache entry. As the open cases have the same cache key, the case that remais open is handled as closed by TSK.

I think a solution could be to reuse the `IPEDSource.sleuthCase` in the `SleuthkitInputStreamFactory.getSleuthkitCase()`

**Comment by lfcnassif** [comment]
Thank you @aberenguel for debugging this! As we talked privately, this was caused by a race condition when caching SleuthkitInputStreamFactory, found almost at the same time by us, but firstly by you :-)

**Comment by lfcnassif** [comment]
Seems above fix wasn't enough to totally fix the issue, I'm still getting it here sometimes...

**Comment by lfcnassif** [comment]
> Seems above fix wasn't enough to totally fix the issue, I'm still getting it here sometimes...

Probably my fault, I was using different jar versions for each module when the error happened today.

**Comment by aberenguel** [comment]
Maybe this bug is back.

```
2022-06-03 01:50:53	[INFO]	[indexer.desktop.CopyFiles]			Exporting files to /mnt/raid-hdd/Perícias/export
2022-06-03 01:50:53	[INFO]	[indexer.desktop.CopyFiles]			Exporting file /Item03-HD-500G.E01/vol_vol2/$RECYCLE.BIN/S-1-5-21-956491387-000000000-1924586691-1001/$R6L4WVB/xxxxxxxxxxxxx.avi
org.sleuthkit.datamodel.ReadContentInputStream$ReadContentInputStreamException: Error reading file 'xxxxxxxxxxxxx.avi' (id=479041) at offset 0.
	at org.sleuthkit.datamodel.ReadContentInputStream.read(ReadContentInputStream.java:105)
	at dpf.sp.gpinf.indexer.sleuthkit.SleuthkitInputStream.read(SleuthkitInputStream.java:32)
	at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
	at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:292)
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:351)
	at java.base/java.io.FilterInputStream.read(FilterInputStream.java:107)
	at dpf.sp.gpinf.indexer.util.IOUtil.copyInputToOutputStream(IOUtil.java:305)
	at dpf.sp.gpinf.indexer.desktop.CopyFiles.doInBackground(CopyFiles.java:102)
	at dpf.sp.gpinf.indexer.desktop.CopyFiles.doInBackground(CopyFiles.java:42)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.sleuthkit.datamodel.TskCoreException: No entry for case SingleUser:/mnt/raid-hdd/Perícias/Reg-XXXX-2021/3.IPED/sleuth.db in cache. Case may have been closed
	at org.sleuthkit.datamodel.SleuthkitJNI$HandleCache.getCaseHandles(SleuthkitJNI.java:193)
	at org.sleuthkit.datamodel.SleuthkitJNI.openImage(SleuthkitJNI.java:889)
	at org.sleuthkit.datamodel.SleuthkitJNI.openImage(SleuthkitJNI.java:837)
	at org.sleuthkit.datamodel.Image.getImageHandle(Image.java:128)
	at org.sleuthkit.datamodel.FileSystem.getFileSystemHandle(FileSystem.java:113)
	at org.sleuthkit.datamodel.FsContent.loadFileHandle(FsContent.java:186)
	at org.sleuthkit.datamodel.FsContent.readInt(FsContent.java:221)
	at org.sleuthkit.datamodel.AbstractFile.read(AbstractFile.java:1003)
	at org.sleuthkit.datamodel.ReadContentInputStream.read(ReadContentInputStream.java:89)
	... 14 more
```

**Comment by lfcnassif** [comment]
Is it easy to reproduce or kind random like before? Maybe this was never fully fixed...

**Comment by aberenguel** [comment]
It is not a multicase. I've taken a look at full log, and saw that the first stack was that:
```
2022-06-03 01:24:11	[INFO]	[indexer.desktop.FileProcessor]			Opening /Item01-HD-ExcelStor.dd/vol_vol2/Users/Usuário/Downloads/20170908_105959_resized (2).jpg
java.lang.RuntimeException: org.sleuthkit.datamodel.TskCoreException: Failed to open case database at /mnt/raid-hdd/Perícias/Reg-2530-2021/3.IPED/sleuth.db
	at dpf.sp.gpinf.indexer.sleuthkit.SleuthkitInputStreamFactory.getSleuthkitCase(SleuthkitInputStreamFactory.java:73)
	at dpf.sp.gpinf.indexer.sleuthkit.SleuthkitInputStreamFactory.getContentById(SleuthkitInputStreamFactory.java:122)
	at dpf.sp.gpinf.indexer.sleuthkit.SleuthkitInputStreamFactory.getSeekableInputStream(SleuthkitInputStreamFactory.java:100)
	at gpinf.dev.data.Item.getSeekableInputStream(Item.java:567)
	at dpf.sp.gpinf.indexer.desktop.FileProcessor.waitSleuthkitInit(FileProcessor.java:198)
	at dpf.sp.gpinf.indexer.desktop.FileProcessor.process(FileProcessor.java:163)
	at dpf.sp.gpinf.indexer.desktop.FileProcessor.doInBackground(FileProcessor.java:125)
	at dpf.sp.gpinf.indexer.desktop.FileProcessor.doInBackground(FileProcessor.java:52)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.sleuthkit.datamodel.TskCoreException: Failed to open case database at /mnt/raid-hdd/Perícias/Reg-2530-2021/3.IPED/sleuth.db
	at org.sleuthkit.datamodel.SleuthkitCase.openCase(SleuthkitCase.java:2910)
	at dpf.sp.gpinf.indexer.sleuthkit.SleuthkitInputStreamFactory.getSleuthkitCase(SleuthkitInputStreamFactory.java:71)
	... 13 more
Caused by: org.sleuthkit.datamodel.TskCoreException: An SQLException was provoked by the following failure: java.lang.InterruptedException
	at org.sleuthkit.datamodel.SleuthkitCase$ConnectionPool.getConnection(SleuthkitCase.java:13003)
	at org.sleuthkit.datamodel.SleuthkitCase.updateDatabaseSchema(SleuthkitCase.java:957)
	at org.sleuthkit.datamodel.SleuthkitCase.init(SleuthkitCase.java:393)
	at org.sleuthkit.datamodel.SleuthkitCase.<init>(SleuthkitCase.java:351)
	at org.sleuthkit.datamodel.SleuthkitCase.openCase(SleuthkitCase.java:2905)
	... 14 more
```

**Comment by lfcnassif** [comment]
Hum, very interesting... SleuthkitCase instantiation is being aborted by an InterruptedException, then that partially constructed object has no reference (it is not returned by the new Constructor() call, it throws an exception) so it can be garbage collected later. I just confirmed here in a separate test that GC calls the finalize() method of objects in that scenario indeed.

So the question is: where that InterruptedException came from? Have you clicked on another item in UI while the dialog message "Opening Case..." was being shown?

**Comment by lfcnassif** [comment]
I was not able to reproduce the last issue, but I pushed a commit that hopefully can fix it, please take a look. Let me know if we should open this again.

**Comment by lfcnassif** [comment]
@aberenguel I was just able to reproduce the issue (your last stacktrace and later "Case may have been closed" errors) adding a Thread.sleep(500) before the waitSleuthkitInit() method call, now renamed to waitEvidenceOpening(). I also verified the fix. So I hope your last rare issue won't happen anymore.

**Comment by lfcnassif** [comment]
mistyped issue reference above, it should be #1052
