### ISSUE TITLE
Error adding file to the database: TskCoreException: Could not find parent

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#1204]
@hauck-jvsh reported this was printed a few times in console with 2 different evidences from some dozens of SETEC/PR some days ago:
```
2022-06-23 12:05:43	[ERROR]	[sleuthkit.datamodel.TskCaseDbBridge]			Error adding file to the database
org.sleuthkit.datamodel.TskCoreException: Could not find parent (fsObjId: 8, parMetaAddr: 212620, parSeq: 125, parentPath: /Users/Pc/Desktop/X/Y/Z)
	at org.sleuthkit.datamodel.TskCaseDbBridge.getParentObjId(TskCaseDbBridge.java:517) ~[sleuthkit-4.11.1-p2.jar:?]
	at org.sleuthkit.datamodel.TskCaseDbBridge.addBatchedFilesToDb(TskCaseDbBridge.java:411) [sleuthkit-4.11.1-p2.jar:?]
	at org.sleuthkit.datamodel.TskCaseDbBridge.addFile(TskCaseDbBridge.java:351) [sleuthkit-4.11.1-p2.jar:?]
	at org.sleuthkit.datamodel.SleuthkitJNI.runAddImgNat(Native Method) ~[sleuthkit-4.11.1-p2.jar:?]
	at org.sleuthkit.datamodel.SleuthkitJNI$CaseDbHandle$AddImageProcess.run(SleuthkitJNI.java:584) [sleuthkit-4.11.1-p2.jar:?]
	at org.sleuthkit.datamodel.SleuthkitJNI$CaseDbHandle$AddImageProcess.run(SleuthkitJNI.java:544) [sleuthkit-4.11.1-p2.jar:?]
	at iped.engine.datasource.SleuthkitReader.addImageBlocking(SleuthkitReader.java:611) [iped-engine-4.0.0-beta.jar:?]
	at iped.engine.datasource.SleuthkitReader$1.call(SleuthkitReader.java:663) [iped-engine-4.0.0-beta.jar:?]
	at iped.engine.datasource.SleuthkitReader$1.call(SleuthkitReader.java:660) [iped-engine-4.0.0-beta.jar:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
```
It is being thrown by this line:
https://github.com/sleuthkit/sleuthkit/blob/sleuthkit-4.11.1/bindings/java/src/org/sleuthkit/datamodel/TskCaseDbBridge.java#L517

Old TSK C code used before by us has some logic to retry looking into the DB for the parent if it is not found in memory cache instead of giving up:
https://github.com/sleuthkit/sleuthkit/blob/sleuthkit-4.11.1/tsk/auto/db_sqlite.cpp#L1098-L1107

We tried to copy the same logic to the java code, but that didn't help.

I'm still not sure if it is an issue or not. Seems TSK is discarding some files because their parent was not found. I still don't know if it doesn't occur with 3.18,15 or if those files are new or if they are silently discarded...

**Comment by lfcnassif** [comment]
@hauck-jvsh just looked at the original image, and the parent directory exists and is not deleted, confirming this is a bug.

I'll test with 3.18.15 tomorrow to know if this is a Sleuthkit regression or if this always happened silently...

**Comment by lfcnassif** [comment]
IPED-3.18.15 didn't miss the files. Tomorrow I'll report this to Sleuthkit project, test tsk_loaddb.exe of tsk-4.11.1 and try to debug this...

**Comment by lfcnassif** [comment]
Running tsk_loaddb version 4.11.1 adds the missing parent dir and its children files to DB, so, seems an issue coming from java code...

**Comment by lfcnassif** [comment]
I spent hours debugging this, but wasn't able to find the cause. Just opened an issue in upstream project:
https://github.com/sleuthkit/sleuthkit/issues/2723

**Comment by lfcnassif** [comment]
After ~2 days debugging this, I found the issue. TSK has a custom method to convert UTF8 C strings to java strings because they had issues with default JNI string conversion with some evidences, but their custom method is failing when converting the extension of a few triggering files. Fallbacking to default JNI string conversion fixed the issue. I pushed this commit to our fork:
https://github.com/sepinf-inc/sleuthkit/commit/594a33f23c40dfb4ebec2ac5159d01e648210b3e
