### ISSUE TITLE
Bookmark panel not being updated

### ISSUE THREAD

**Issue by aberenguel** [sepinf-inc/IPED#1223]
Using 88c3425e6 master branch.
I created a bookmark, but it was not added in the bookmark panel.

![image](https://user-images.githubusercontent.com/2973359/179130404-ca9a8619-23ba-44e2-b6de-39e44ceaf71d.png)

If I close and reopen the case, the bookmark appears.

**Comment by lfcnassif** [comment]
Thanks @aberenguel for reporting. I noticed this recently. If you rename or deletes another bookmark, the new one appears. Seems just a refresh issue.

**Comment by aberenguel** [comment]
Just reproduced it.
Select "[No Bookmarks]" in bookmark panel.
Open "Manage Bookmarks" (ctrl+B) and create a new bookmark.

**Comment by aberenguel** [comment]
Another bug I noticed is when this issue happens, when I change the selected bookmark in the bookmarks panel, the table items panel is not refreshed.

**Comment by lfcnassif** [comment]
> Select "[No Bookmarks]" in bookmark panel.
> Open "Manage Bookmarks" (ctrl+B) and create a new bookmark.

Thank you for the step by step! I tried to reproduce to fix before 4.0.0-final, but as I couldn't, unfortunately the fix will have to wait 4.0.1...

This is not a refresh issue, possibly it is related to #1194 "fix".

**Comment by aberenguel** [comment]
I'll try to debug and fix it on this weekend so that it can be applied in 4.0.0.

**Comment by lfcnassif** [comment]
I just confirmed the issue doesn't happen before https://github.com/sepinf-inc/IPED/commit/d82a848bb51d88ee34ec836720a0278bc92ea2c4

**Comment by lfcnassif** [comment]
Taking a look at this now. This is printed in IPED-SearchApp.log:
```
Exception in thread "AWT-EventQueue-0" java.lang.ClassCastException: class iped.app.ui.BookmarksTreeModel$NoBookmarks cannot be cast to class java.lang.Comparable (iped.app.ui.BookmarksTreeModel$NoBookmarks is in unnamed module of loader 'app'; java.lang.Comparable is in module java.base of loader 'bootstrap')
	at java.base/java.util.TreeMap.getEntry(Unknown Source)
	at java.base/java.util.TreeMap.containsKey(Unknown Source)
	at java.base/java.util.TreeSet.contains(Unknown Source)
	at iped.app.ui.BookmarksTreeListener.updateModelAndSelection(BookmarksTreeListener.java:82)
	at iped.app.ui.BookmarksController$2.run(BookmarksController.java:86)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by lfcnassif** [comment]
Hi @aberenguel, when you have time, please double check if commit above fixes the issues with your case.

**Comment by aberenguel** [comment]
I've just tested. The commit fixed it! Thanks, @lfcnassif !

**Comment by lfcnassif** [comment]
Thanks for testing!
