### ISSUE TITLE
New evidence location dialog stopped to be shown if it was moved

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#1250]
Regression, it's not working at least with ufdr and disk images.

**Comment by lfcnassif** [comment]
This is being caused by:
```
Caused by: java.util.MissingResourceException: Can't find bundle for base name iped-basicprops, locale pt_BR
	at java.base/java.util.ResourceBundle.throwMissingResourceException(Unknown Source)
	at java.base/java.util.ResourceBundle.getBundleImpl(Unknown Source)
	at java.base/java.util.ResourceBundle.getBundleImpl(Unknown Source)
	at java.base/java.util.ResourceBundle.getBundle(Unknown Source)
	at iped.localization.Messages.getExternalBundle(Messages.java:49)
	at iped.localization.Messages.getString(Messages.java:59)
	at iped.utils.SelectImagePathWithDialog.run(SelectImagePathWithDialog.java:44)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
```
Which was caused by a mistake when refactoring the package structure, pushing the fix shortly...
