### ISSUE TITLE
Processing or case opening can fail if missing TSK dependency is not present on user machine

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#1257]
Reported by an user:
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\IPED\iped-4.0.1\tools\tsk\x64\vccorlib140.dll: Can't find dependent libraries
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(Unknown Source)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(Unknown Source)
	at java.base/java.lang.ClassLoader.loadLibrary0(Unknown Source)
	at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.base/java.lang.Runtime.load0(Unknown Source)
	at java.base/java.lang.System.load(Unknown Source)
	at iped.engine.util.Util.loadNatLibs(Util.java:452)
	at iped.engine.config.Configuration.loadNativeLibs(Configuration.java:138)
	at iped.engine.config.Configuration.loadConfigurables(Configuration.java:197)
	at iped.app.processing.Main.main(Main.java:291)
```

**Comment by lfcnassif** [comment]
Closing as invalid.

The issue does not happen with a clean Windows 10 installation. It happened with an user Windows 7 system, but since Windows 7 support ended in 14/01/2020 by Microsoft, I don't think we should give any kind of support to Win7

**Comment by lfcnassif** [comment]
For those still interested in running iped-4.0 on old unsupported Windows 7, you should install MS Visual C++ Redistributable Package 2015.

**Comment by gfd2020** [comment]
> Can't find dependent libraries



> For those still interested in running iped-4.0 on old unsupported Windows 7, you should install MS Visual C++ Redistributable Package 2015.
> 
> **edited:** python modules won't work, since iped-4 embeds python 3.9 and that is also not supported on Windows 7.

Visual C++ Redistributable Package will not work in this case.

I believe tsk was compiled with VS2015 and/or Win10SDK. In that case it won't work on win7. I made a tweak to check windows version. If it is smaller than 6.3 (win 8.1), the tsk from version 3 of IPED will be used and it will not load the python modules either. I did it that way because it is a specific version of IPED for a special case that will run on win7.

**Comment by gfd2020** [comment]
> Be careful with this. APFS unallocated space is not supported by old TSK. APFS password passing from IPED to TSK was completely changed and it won't work with old TSK. Other things can stop working...

Thank you. This particular build was designed to parse Hikivison FS, it is a build only for that. ( Until a make a new PR)

This build have a lot of other customizations, it is exclusive and is in beta. In my tests, TSK is working fine.
