### ISSUE TITLE
Report creation from cmd line can fail sometimes

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#1258]
Reported by Carlos Rodrigo Souza Santos. Checking the log I found:
```
Caused by: java.lang.IllegalArgumentException: Inconsistency of field data structures across documents for field [office:extended-properties:TotalTime:string] of doc [11]. doc values type: expected 'SORTED_NUMERIC', but it has 'SORTED_SET'.
                at org.apache.lucene.index.IndexingChain$FieldSchema.raiseNotSame(IndexingChain.java:1357)
                at org.apache.lucene.index.IndexingChain$FieldSchema.assertSame(IndexingChain.java:1352)
                at org.apache.lucene.index.IndexingChain$FieldSchema.setDocValues(IndexingChain.java:1393)
                at org.apache.lucene.index.IndexingChain.updateDocFieldSchema(IndexingChain.java:819)
                at org.apache.lucene.index.IndexingChain.processDocument(IndexingChain.java:601)
                at org.apache.lucene.index.DocumentsWriterPerThread.updateDocuments(DocumentsWriterPerThread.java:241)
                at org.apache.lucene.index.DocumentsWriter.updateDocuments(DocumentsWriter.java:432)
                at org.apache.lucene.index.IndexWriter.updateDocuments(IndexWriter.java:1532)
                at org.apache.lucene.index.IndexWriter.addDocuments(IndexWriter.java:1503)
                at iped.engine.task.index.IndexTask.process(IndexTask.java:148)
```
Although this is a regression, I think it is not critical, since report creation from UI works.

**Comment by lfcnassif** [comment]
Explaining the possible cause here for future reference.

This is possibly being caused because the default property->type mapping file (conf/metadataTypes.txt) is being read when creating the report from command line, this maybe can cause conflicts with the dynamic types detected when the case was processed. When creating the report from UI, that mapping file is read from source case, with all dynamic types already saved.

**Comment by lfcnassif** [comment]
I'll wait feedback from user before merging the proposed fix.
