### ISSUE TITLE
Optimize Graph CSV (un)compression again

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#1265]
When working on #908, I got some weird "access denied" errors when using parallelStream() in graph CSVs (un) compression, so I did a simple change to use normal stream() instead of parallelStream() in commit cf5ffdbc414a11fa3dd14dee3c9ea00c5ddca31d.

But that error is really strange, it should be better investigated, so we could use the faster parallelStream() method in some places again.

**Comment by lfcnassif** [comment]
Reopening, the use of parallelStream is causing:
```
java.security.AccessControlException: access denied ("java.io.FilePermission" "F:\teste\parallel_stream\iped\neo4j\csv\replace.csv.gzip" "write")
        at java.security.AccessControlContext.checkPermission(Unknown Source) ~[?:?]
        at java.security.AccessController.checkPermission(Unknown Source) ~[?:?]
        at java.lang.SecurityManager.checkPermission(Unknown Source) ~[?:?]
        at java.lang.SecurityManager.checkWrite(Unknown Source) ~[?:?]
        at sun.nio.fs.WindowsChannelFactory.open(Unknown Source) ~[?:?]
        at sun.nio.fs.WindowsChannelFactory.newFileChannel(Unknown Source) ~[?:?]
        at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(Unknown Source) ~[?:?]
        at java.nio.file.spi.FileSystemProvider.newOutputStream(Unknown Source) ~[?:?]
        at java.nio.file.Files.newOutputStream(Unknown Source) ~[?:?]
        at iped.engine.graph.GraphFileWriter.lambda$compressGeneratedCSVFiles$1(GraphFileWriter.java:316) ~[iped-engine-4.2-snapshot.jar:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:?]
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
        at java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source) ~[?:?]
        at java.util.concurrent.CountedCompleter.exec(Unknown Source) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?]
```

I found this: https://bugs.openjdk.org/browse/JDK-8143638

I'll switch to common ordinary Threads to avoid this.
