### ISSUE TITLE
Error generating multicase graph depending on current directory

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#1288]
An user sent this:
```
java.lang.IllegalArgumentException: Error evaluating value for setting 'dbms.directories.neo4j_home'. Failed to validate 'H:\XXXXX\..\YYYYYY\iped\neo4j' for 'dbms.directories.neo4j_home': 'H:\XXXXX\..\YYYYYY\iped\neo4j' is not a normalized path.
	at org.neo4j.configuration.Config.evaluateSetting(Config.java:787) ~[neo4j-configuration-4.4.4.jar:4.4.4]
	at org.neo4j.configuration.Config.evaluateSettingValues(Config.java:629) ~[neo4j-configuration-4.4.4.jar:4.4.4]
	at org.neo4j.configuration.Config.<init>(Config.java:600) ~[neo4j-configuration-4.4.4.jar:4.4.4]
	at org.neo4j.configuration.Config$Builder.build(Config.java:320) ~[neo4j-configuration-4.4.4.jar:4.4.4]
	at org.neo4j.dbms.api.DatabaseManagementServiceBuilder.build(DatabaseManagementServiceBuilder.java:94) ~[neo4j-4.4.4.jar:4.4.4]
	at iped.engine.graph.GraphServiceImpl.start(GraphServiceImpl.java:43) ~[iped-engine-4.0.1.jar:?]
	at iped.app.graph.LoadGraphDatabaseWorker.initGraphService(LoadGraphDatabaseWorker.java:151) [iped-search-app.jar:?]
	at iped.app.graph.LoadGraphDatabaseWorker.doInBackground(LoadGraphDatabaseWorker.java:48) [iped-search-app.jar:?]
	at iped.app.graph.LoadGraphDatabaseWorker.doInBackground(LoadGraphDatabaseWorker.java:29) [iped-search-app.jar:?]
	at javax.swing.SwingWorker$1.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at javax.swing.SwingWorker.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

**Comment by lfcnassif** [comment]
Reopening, the fix was incomplete.
