### ISSUE TITLE
IndexOutOfBoundsException in EntropyTask

### ISSUE THREAD

**Issue by aberenguel** [sepinf-inc/IPED#1327]
Using IPED 4.0.4 in Ubuntu 22.04 processing an UFDR file
```
2022-09-20 16:32:32     [ERROR] [app.processing.Main]                   Processing Error: 
java.lang.Exception: Worker-40 Error while processing item01.ufdr/File system Extraction.zip/root/private/var/mobile/Library/Caches/com.apple.itunescloudd/Cache.db>>Carved-136952.html (-63224bytes)
        at iped.engine.core.Worker.process(Worker.java:186) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.core.Worker.processNewItem(Worker.java:227) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.core.Worker.processNewItem(Worker.java:204) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.carver.BaseCarveTask.addOffsetFile(BaseCarveTask.java:136) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.carver.BaseCarveTask.addCarvedEvidence(BaseCarveTask.java:189) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.carver.CarverTask$1.processCarvedItem(CarverTask.java:248) ~[iped-engine-4.0.4.jar:?]
        at iped.carvers.standard.AbstractCarver.carveFromHeader(AbstractCarver.java:101) ~[iped-carvers-impl-4.0.4.jar:?]
        at iped.carvers.standard.AbstractCarver.carveFromFooter(AbstractCarver.java:129) ~[iped-carvers-impl-4.0.4.jar:?]
        at iped.carvers.standard.AbstractCarver.notifyHit(AbstractCarver.java:201) ~[iped-carvers-impl-4.0.4.jar:?]
        at iped.engine.task.carver.CarverTask.findSig(CarverTask.java:193) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.carver.CarverTask.safeProcess(CarverTask.java:120) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.carver.CarverTask.process(CarverTask.java:75) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.processMonitorTimeout(AbstractTask.java:250) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:180) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:207) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:207) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.PythonTask.sendToNextTask(PythonTask.java:273) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:207) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.PythonTask.sendToNextTask(PythonTask.java:273) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:207) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:207) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:207) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:207) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:207) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:207) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:207) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:207) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:207) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:207) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:207) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:207) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:207) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:207) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:207) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:207) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:207) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:207) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:207) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:207) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:207) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:207) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:207) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:207) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:207) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:207) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.core.Worker.process(Worker.java:177) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.core.Worker.run(Worker.java:266) ~[iped-engine-4.0.4.jar:?]
Caused by: java.lang.IndexOutOfBoundsException
        at java.nio.ByteBuffer.wrap(ByteBuffer.java:395) ~[?:?]
        at iped.utils.SeekableFileInputStream.read(SeekableFileInputStream.java:33) ~[iped-utils-4.0.4.jar:?]
        at iped.utils.LimitedSeekableInputStream.read(LimitedSeekableInputStream.java:53) ~[iped-utils-4.0.4.jar:?]
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:290) ~[?:?]
        at java.io.BufferedInputStream.read(BufferedInputStream.java:351) ~[?:?]
        at java.io.FilterInputStream.read(FilterInputStream.java:133) ~[?:?]
        at iped.utils.RandomFilterInputStream.read(RandomFilterInputStream.java:103) ~[iped-utils-4.0.4.jar:?]
        at iped.utils.RandomFilterInputStream.read(RandomFilterInputStream.java:79) ~[iped-utils-4.0.4.jar:?]
        at iped.engine.task.EntropyTask.process(EntropyTask.java:57) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.processMonitorTimeout(AbstractTask.java:250) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:180) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:207) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:207) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:207) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:207) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:207) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.PythonTask.sendToNextTask(PythonTask.java:273) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:207) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.PythonTask.sendToNextTask(PythonTask.java:273) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:207) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:207) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:207) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:207) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:207) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:207) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:207) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:207) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:207) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:207) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:207) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:207) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:207) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:207) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:207) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:207) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:207) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:207) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:207) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:207) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:207) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:207) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:207) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:207) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:207) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:207) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188) ~[iped-engine-4.0.4.jar:?]
        at iped.engine.core.Worker.process(Worker.java:177) ~[iped-engine-4.0.4.jar:?]
        ... 75 more
```

**Comment by lfcnassif** [comment]
Hi @aberenguel, thanks for reporting. Could you try processing the same UFDR on 3.18.15 to see if it is a regression or not?

**Comment by aberenguel** [comment]
> Hi @aberenguel, thanks for reporting. Could you try processing the same UFDR on 3.18.15 to see if it is a regression or not?

Sure! I will leave the UFDR processing this night. Tomorrow I give you a feedback.

**Comment by lfcnassif** [comment]
Hi @aberenguel, could you share with me the `item01.ufdr/File system Extraction.zip/root/private/var/mobile/Library/Caches/com.apple.itunescloudd/Cache.db` file so I can try to reproduce? Seems to me this could be related to the negative size of the html file carved from it.

**Comment by lfcnassif** [comment]
> Hi @aberenguel, thanks for reporting. Could you try processing the same UFDR on 3.18.15 to see if it is a regression or not?

Just an update, don't waste your time with the old version. Sharing the sample is much more important to help fixing this.

**Comment by aberenguel** [comment]
I've just checked it in IPED 3.18.15. It worked without any issues.
I'll send the file to you in Teams

**Comment by lfcnassif** [comment]
This is driving me crazy, I'm investigating this issue for almost 2 days and I still didn't come up with a conclusion. Each run over the triggering UFDR shared privately takes almost 30min to finish, so testing each code change is not fast.

The error happens very often, but not always, what points to some kind of multithreading issue. A negative sized HTML is being carved from the Cache.db file. There is this rule in carving module: if carved header offset + carved file size > parent file size then carved file size is set to parent file size - carved header offset. Evaluating this formula using the actual values gives exactly the negative carved file size reported (-63224 bytes). But this should never happen, the header offset should never be bigger than parent file size. Looking into the parent Cache.db file, there is no HTML header. This makes me think a wrong content (from another file) is being processed, not only by the carving module, but by HashTask and ParsingTask that also log (non aborting IndexOutOfBounds) errors. CarvingTask also runs in a single thread.

I suspected of the following points:
- (simple) changes in SeekableFileInputStream class in 4.0 release
- a wrong implementation of internal caches in ZIPInputStreamFactory class, used to avoid uncompressing UFDR content multiple times;
- the ignoreLocalFileHeader flag used in the ZipFile constructor within ZIPInputStreamFactory. This is used to speed up opening UFDR files from UI. It has some limitations, but according to documentation, shouldn't be an issue;
- the fact that the triggering UFDR is using STORED entries, with no actual compression;
- possible thread unsafety issues of commons compress ZipFile

But all of them seems good to me...

**Comment by lfcnassif** [comment]
Last run just aborted with `ignoreLocalFileHeaders = false` and disabling `ZIPInputStreamFactory` internal caches.

**Comment by lfcnassif** [comment]
Unfortunately I couldn't find the root cause of this. I'll just fix the consequence of carved files with negative size being generated for now. If anyone has some idea, please let me know.
