### ISSUE TITLE
QRCodeTask hangs for hours

### ISSUE THREAD

**Issue by aberenguel** [sepinf-inc/IPED#1415]
Using iped 4.0.5

My case processing is hang on `QRCodeTask` for many hours. I stopped the processing and restarted with `--continue`, but it hangs on `QRCodeTask` again

![image](https://user-images.githubusercontent.com/2973359/198748631-ea36ecfb-3ab8-4450-a331-6071bc380216.png)

I run `jstack` many times to see if the code is running (changing the stack snapshot). But it always shows this.
```
"Worker-31" #232 prio=5 os_prio=0 cpu=2460920.42ms elapsed=5618.35s tid=0x00007e873c151800 nid=0x29bd94 runnable  [0x00007e87656fc000]
   java.lang.Thread.State: RUNNABLE
        at com.google.zxing.qrcode.detector.FinderPatternFinder.selectBestPatterns(FinderPatternFinder.java:637)
        at com.google.zxing.qrcode.detector.FinderPatternFinder.find(FinderPatternFinder.java:164)
        at com.google.zxing.qrcode.detector.Detector.detect(Detector.java:81)
        at com.google.zxing.qrcode.QRCodeReader.decode(QRCodeReader.java:77)
        at com.google.zxing.qrcode.QRCodeReader.decode(QRCodeReader.java:64)
        at iped.engine.task.QRCodeTask.process(QRCodeTask.java:143)
        at iped.engine.task.AbstractTask.processMonitorTimeout(AbstractTask.java:250)
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:180)
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:207)
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188)
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:207)
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188)
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:207)
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188)
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:207)
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188)
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:207)
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188)
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:207)
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188)
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:207)
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188)
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:207)
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188)
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:207)
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188)
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:207)
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188)
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:207)
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188)
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:207)
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188)
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:207)
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188)
        at iped.engine.core.Worker.process(Worker.java:177)
        at iped.engine.core.Worker.run(Worker.java:266)
```

**Comment by lfcnassif** [comment]
Seems a zxing library issue. Could you share the triggering file? After that, @hauck-jvsh could you take a look at this?

**Comment by aberenguel** [comment]
> Seems a zxing library issue. Could you share the triggering file? After that, @hauck-jvsh could you take a look at this?

The E01 or the jpg file? I tried to open the unfinished case but I haven't found the file. I think I need to let the case finish. So I set `enableQRCode = false` and started it again.

**Comment by lfcnassif** [comment]
The JPG

**Comment by aberenguel** [comment]
@lfcnassif , I've just sent the file to you in the Teams.

**Comment by hauck-jvsh** [comment]
Sure, I can take a look on monday.

**Comment by lfcnassif** [comment]
Thank you both! #27 would have helped here.

**Comment by hauck-jvsh** [comment]
@lfcnassif could you share the triggering image?

**Comment by lfcnassif** [comment]
Sure, just sent to you privatelly.

**Comment by lfcnassif** [comment]
This was fixed in upstream library: https://github.com/zxing/zxing/issues/1567

If version 3.5.1 isn't released soon, maybe we can create a patched version ourselves.

**Comment by lfcnassif** [comment]
> If version 3.5.1 isn't released soon, maybe we can create a patched version ourselves.

Or implement timeout control inside QRCodeTask, like others.
