### ISSUE TITLE
Iped 4.0.2 not working on Windows 7 - dll error

### ISSUE THREAD

**Issue by gfd2020** [sepinf-inc/IPED#1488]
Running Iped 4.0.2 on Windows 7 64-bit , gives me a following error:
iped-4.0.2\tools\tsk\x64\vccorlib140.dll: Can't find dependent libraries
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(Unknown Source)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(Unknown Source)
	at java.base/java.lang.ClassLoader.loadLibrary0(Unknown Source)
	at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.base/java.lang.Runtime.load0(Unknown Source)
	at java.base/java.lang.System.load(Unknown Source)
	at iped.engine.util.Util.loadNatLibs(Util.java:452)
	at iped.engine.config.Configuration.loadNativeLibs(Configuration.java:138)
	at iped.engine.config.Configuration.loadConfigurables(Configuration.java:197)
	at iped.app.processing.Main.main(Main.java:291)

PS: Installed packages on the OS:
Microsoft Visual C++ 2005 Redistributable
Microsoft Visual C++ 2005 Redistributable (x64)
Microsoft Visual C++ 2008 Redistributable - x64
Microsoft Visual C++ 2008 Redistributable - x86
Microsoft Visual C++ 2010 Redistributable - x64
Microsoft Visual C++ 2013 Redistributable - x64
Microsoft Visual C++ 2015-2019 Redistributable - x64

**Comment by lfcnassif** [comment]
Hi @gfd2020, could you test latest 4.0.7 on your machine? We shouldn't depend on MS Redistributable packages, all DLL's should be distributed together with the application.

**Comment by lfcnassif** [comment]
Just remembered this was discussed before. Win7 supported is not provided mainly because of this:
https://github.com/sepinf-inc/IPED/issues/1257#issuecomment-1208434477

**Comment by lfcnassif** [comment]
I'm closing this as duplicate. If you disagree, we can discuss on #1257.
