### ISSUE TITLE
AIOOBE in Timeline 

### ISSUE THREAD

**Issue by aberenguel** [sepinf-inc/IPED#1505]
I'm in a case with IPED 4.0.6.
With no filters, I clicked in timeline button and after some time, this log appeared. The table shows no item.

```
2023-02-07 16:32:01	[INFO]	[app.ui.UICaseSearcherFilter]			Searching for query *:*
2023-02-07 16:32:01	[INFO]	[engine.search.QueryBuilder]			Expanded query terms: []
2023-02-07 16:32:11	[INFO]	[app.ui.RowComparator]			Loading sort data for Column timeStamp...
2023-02-07 16:32:34	[INFO]	[app.ui.RowComparator]			Loading sort data for Column timeStamp took 23063ms
2023-02-07 16:32:41	[INFO]	[app.ui.UICaseSearcherFilter]			Searching for query *:*
java.lang.ArrayIndexOutOfBoundsException: Index 512 out of bounds for length 512
	at iped.engine.search.TimelineResults.loadOrdsFromStringInner(TimelineResults.java:99)
	at iped.engine.search.TimelineResults.loadOrdsFromString(TimelineResults.java:87)
	at iped.engine.search.TimelineResults.expandTimestamps(TimelineResults.java:51)
	at iped.app.ui.UICaseSearcherFilter.doInBackground(UICaseSearcherFilter.java:254)
	at iped.app.ui.UICaseSearcherFilter.doInBackground(UICaseSearcherFilter.java:55)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by lfcnassif** [comment]
Thanks for reporting, I'll take a look soon.

**Comment by lfcnassif** [comment]
Hi @aberenguel, please test the fix in snapshot above with your triggering case. Just download it and replace the [case]/iped/lib folder contents.

The bug was triggered because some timestamp property has more than 512 date values. I detected cases where some date property could be multivalued (like PDF editing dates). Having more than 512 date values in the same property should be very uncommon, but you found it :-). After you test and verify the fix, I'll increase the limit to 1024 or 2048.

**Comment by aberenguel** [comment]
Another thing I noticed is that the items are not sorted by timeStamp when I toggle table timeline. Is it the intention?

**Comment by lfcnassif** [comment]
> Just tested with the fix above [85a225d](https://github.com/sepinf-inc/IPED/commit/85a225d5fb741199d3cba8aa7fcb7a02a5a27ef3). It worked properly.

Thank you! I just reproduced the issue locally with artificial data and confirmed the fix too.

**Comment by lfcnassif** [comment]
> it would be interesting to have a progress dialog during "Loading sort data for Column timeStamp" processing. The UI freezes during this time.

What is your case total item count?

> Another thing I noticed is that the items are not sorted by timeStamp when I toggle table timeline. Is it the intention?

If result set is larger than 16M items, any automatic sorting is disabled intentionally, not sure if it is your case.

**Comment by lfcnassif** [comment]
> it would be interesting to have a progress dialog during "Loading sort data for Column timeStamp" processing. The UI freezes during this time.

Agreed, we can implement this when finishing #1079.

**Comment by aberenguel** [comment]
> What is your case total item count?
It has 38M items.
