### ISSUE TITLE
Upgrade to Java 17 or later LTS

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#1522]
Since java 11 active support will end in 7 months (https://endoflife.date/java) it would be good to upgrade to Java 17 at some point. Nashorn JS engine was removed in Java 15, so we at least will need #1066 and of course do regression tests.

**Comment by lfcnassif** [comment]
Let's use this ticket to track java 17 related issues. For now I got:
- Splash screen errors on Console;
- Neo4j graph building (CSV importing) is not working;

About the splash screen, I got this:
```
java.lang.NoSuchFieldException: classes
        at java.base/java.lang.Class.getDeclaredField(Unknown Source)
        at iped.app.ui.splash.StartUpControl.getCurrentProcessSize(StartUpControl.java:12)
        at iped.app.ui.splash.StartUpControlClient$1.run(StartUpControlClient.java:38)
```
@tc-wleite, any tip on how to fix it?

**Comment by lfcnassif** [comment]
UI icons are also not rendered because of our custom PNG reader impl:
```
javax.imageio.IIOException: Caught exception during read: 
	at com.sun.imageio.plugins.png2.PNGImageReader.read(PNGImageReader.java:1783)
	at java.desktop/javax.imageio.ImageIO.read(Unknown Source)
	at java.desktop/javax.imageio.ImageIO.read(Unknown Source)
	at iped.utils.IconUtil.getIconImages(IconUtil.java:61)
	at iped.app.ui.App.createGUI(App.java:431)
	at iped.app.ui.App$1.run(App.java:348)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.IllegalAccessError: class com.sun.imageio.plugins.png2.PNGImageDataEnumeration (in unnamed module @0x3fc6f2fa) cannot access class com.sun.imageio.plugins.common.SubImageInputStream (in module java.desktop) because module java.desktop does not export com.sun.imageio.plugins.common to unnamed module @0x3fc6f2fa
	at com.sun.imageio.plugins.png2.PNGImageDataEnumeration.nextElement(PNGImageReader.java:79)
	at com.sun.imageio.plugins.png2.PNGImageDataEnumeration.nextElement(PNGImageReader.java:63)
	at java.base/java.io.SequenceInputStream.peekNextStream(Unknown Source)
	at java.base/java.io.SequenceInputStream.<init>(Unknown Source)
	at com.sun.imageio.plugins.png2.PNGImageReader.readImage(PNGImageReader.java:1394)
	at com.sun.imageio.plugins.png2.PNGImageReader.read(PNGImageReader.java:1776)
	... 18 more
```
Removing it from classpath fixes icons, but may cause regression with PNG reading:
https://github.com/sepinf-inc/IPED/issues/827#issuecomment-971758133

**Comment by lfcnassif** [comment]
2 errors running OCR tests:
```
Tests run: 5, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 28.924 sec <<< FAILURE!
testOCRParserPSD(iped.parsers.ocr.OCRParserTest)  Time elapsed: 4.401 sec  <<< FAILURE!
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at iped.parsers.ocr.OCRParserTest.testOCRParserPSD(OCRParserTest.java:219)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

testOCRParserSVG(iped.parsers.ocr.OCRParserTest)  Time elapsed: 0.282 sec  <<< FAILURE!
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at iped.parsers.ocr.OCRParserTest.testOCRParserSVG(OCRParserTest.java:252)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
```

**Comment by lfcnassif** [comment]
Failing tests above are also caused by the custom PNG reader, I removed it for now.

**Comment by tc-wleite** [comment]
>  Splash screen errors on Console;
> @tc-wleite, any tip on how to fix it?

@lfcnassif, there are a few changes in JDK 17 that affected the method used to count loaded classes. The critical one is that private fields cannot be accessed using reflection (at least the way they were).

I am looking for other solutions, that work with Java 17 (and ideally newer versions).

If no acceptable solution is available, there are two alternatives. The first is to replace the progress by and indeterminate "loading". The second would be adding some "checkpoint" calls (probably as static initializers) of a few classes loaded during the application start up.

**Comment by lfcnassif** [comment]
Thanks @tc-wleite for taking a look at it. But there is no hurry. Because of java 17 changes, I guess I'll have to upgrade Tika and its many dependencies, this will take time for testing...

**Comment by tc-wleite** [comment]
@lfcnassif, I believe I found a solution to the splash issue.
Can I send the proposed changes to the branch you created (java17_upgrade) or should I create a new one?

**Comment by lfcnassif** [comment]
> @lfcnassif, I believe I found a solution to the splash issue.

Great!!!

> Can I send the proposed changes to the branch you created (java17_upgrade) or should I create a new one?

Sure, you can use the same branch.

**Comment by tc-wleite** [comment]
> > Can I send the proposed changes to the branch you created (java17_upgrade) or should I create a new one?
> 
> Sure, you can use the same branch.

I just pushed the changes to avoid the splash screen errors with Java 17.
It should work with any Java version (11, 17 or greater), as it doesn't use reflection to access a private field to count the number of loaded classes. That part was replaced by a much simpler direct call to an API call that was available since Java 1.5 (that somehow I missed during the initial implementation).

**Comment by lfcnassif** [comment]
> I just pushed the changes to avoid the splash screen errors with Java 17.
> It should work with any Java version (11, 17 or greater), as it doesn't use reflection to access a private field to count the number of loaded classes. That part was replaced by a much simpler direct call to an API call that was available since Java 1.5 (that somehow I missed during the initial implementation).

Nice commit, very clean!
