### ISSUE TITLE
Logging dependencies duplicating classes may cause NoSuchMethodError

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#1572]
NoSuchMethodError was reported by a Linux user:
```
java.lang.NoSuchMethodError: 'void org.apache.commons.logging.LogFactory.setAttribute(java.lang.String, java.lang.Object)
        at iped.engine.config.Configuration.configureLogger(Configuration.java:86)
        at iped.engine.config.Configuration.getConfiguration(Configuration.java:101)
        at iped.engine.config.Configuration.loadConfigurables(Configuration.java:166)
        at iped.engine.config.Configuration.loadConfigurables(Configuration.java:143)
        at iped.engine.sleuthkit.SleuthkitServer.main(SleuthkitServer.java:71)
java.lang.Exception: Error starting SleuthkitServer 4
        at iped.engine.sleuthkit.SleuthkitClient.start(SleuthkitClient.java:219)
        at iped.engine.sleuthkit.SleuthkitClient.<init>(SleuthkitClient.java:166)
        at iped.engine.sleuthkit.SleuthkitClient$1.run(SleuthkitClient.java:141)
```
Searching for `org.apache.commons.logging.LogFactory` class in dependencies, I found it in commons-logging-1.2.jar and jcl-over-slf4j-1.7.36.jar. Not sure, but maybe we can remove the second one, it is used just by tika-parsers and is used to redirect JCL to slf4j. The first is used by several dependencies, including tika-parsers. Before removing it, we would be better asking Tika project if that can cause some warm.

**Comment by lfcnassif** [comment]
This is also being caused by spring-jcl-5.3.23.jar brought by #1373.

**Comment by lfcnassif** [comment]
After reading:
https://issues.apache.org/jira/browse/TIKA-2245
https://www.slf4j.org/legacy.html#:~:text=JCL%2Dover%2DSLF4J%2C%20i.e.,deferred%20to%20a%20later%20time.

I think we should exclude spring-jcl and commons-logging from all dependencies, keeping jcl-over-slf4j. @fmpfeifer since you did the logging refactoring a long ago, do you have any recommendation?

**Comment by lfcnassif** [comment]
Tika has a comment in its pom.xml stating commons-logging is needed by jackcess. But I cloned jackcess, replaced commons-logging by jcl-over-slf4j and the compiled jackcess master and 4.0.1 (used by us), all tests passed, i.e. it doesn't seem to depend on a specific commons-logging API. Maybe Tika comment is outdated. So I'll process with `spring-jcl` and `commons-logging` removal.
