### ISSUE TITLE
Aborting FileNotFoundException when starting case

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#1577]
An user reported this:
```
2023-03-08 09:54:01	[ERROR]	[app.processing.Main]			Processing Error: 
java.io.FileNotFoundException: H:\XXXXXXX\iped\tools\libreoffice.zip (O sistema não pode encontrar o caminho especificado)
	at java.io.FileOutputStream.open0(Native Method) ~[?:?]
	at java.io.FileOutputStream.open(FileOutputStream.java:298) ~[?:?]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:237) ~[?:?]
	at iped.utils.IOUtil.copyFile(IOUtil.java:290) ~[iped-utils-4.2-snapshot.jar:?]
	at iped.utils.IOUtil.copyFile(IOUtil.java:285) ~[iped-utils-4.2-snapshot.jar:?]
	at iped.engine.core.Manager.prepareOutputFolder(Manager.java:866) ~[iped-engine-4.2-snapshot.jar:?]
	at iped.engine.core.Manager.process(Manager.java:235) ~[iped-engine-4.2-snapshot.jar:?]
	at iped.app.processing.Main.startManager(Main.java:177) [iped.jar:?]
	at iped.app.processing.Main.execute(Main.java:239) [iped.jar:?]
	at iped.app.processing.Main.main(Main.java:304) [iped.jar:?]
```

Looks like in his machine libreoffice.zip is being copied before folders in iped/tools, so iped/tools is not created and error above is thrown.

**Comment by lfcnassif** [comment]
Affects 4.1.0.
