### ISSUE TITLE
Decoded text temporary file shared by item fragments may be deleted before all fragments are processed

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#1584]
Some messages like this were printed in an user terminal:
```
2023-03-08 03:16:01	[ERROR]	[engine.util.TextCache]			Error reading extracted text file from /XXXX/XXXXX/XXXXX/XXXXXX.xml>>XXXXXXXX.xml_6, maybe your antivirus blocked or deleted it? java.io.FileNotFoundException: C:\iped\Temp\iped-temp2857488198079801232\text25355074186634418.tmp (O sistema não pode encontrar o arquivo especificado)
java.io.FileNotFoundException: C:\iped\Temp\iped-temp2857488198079801232\text25355074186634418.tmp (O sistema não pode encontrar o arquivo especificado)
	at java.base/java.io.RandomAccessFile.open0(Native Method)
	at java.base/java.io.RandomAccessFile.open(Unknown Source)
	at java.base/java.io.RandomAccessFile.<init>(Unknown Source)
	at java.base/java.io.RandomAccessFile.<init>(Unknown Source)
	at iped.engine.util.TextCache.getTextReader(TextCache.java:104)
	at iped.engine.data.Item.getTextReader(Item.java:513)
	at iped.engine.task.regex.RegexTask.process(RegexTask.java:264)
	at iped.engine.task.AbstractTask.processMonitorTimeout(AbstractTask.java:277)
	at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:192)
	at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:225)
	at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:205)
	at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:225)
	at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:205)
```
He said the temp directory was excluded from antivirus scanning folders. I didn't understand 100% the issue, but seems some decoded text temporary files were deleted early, causing processing issues with the item fragments.

**Comment by lfcnassif** [comment]
Just found the bug in the temporary file references counter initial value. Affects 4.1.0.
