### ISSUE TITLE
Error creating report with local wav2vec2 transcription enabled

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#1589]
Similar to #1588, but it is not finding IPED's python:
```
java.io.IOException: Cannot run program "E:\teste\no-transcript\iped/python/python.exe": CreateProcess error=2, O sistema não pode encontrar o arquivo especificado
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at iped.engine.task.transcript.Wav2Vec2TranscriptTask.startServer(Wav2Vec2TranscriptTask.java:105)
	at iped.engine.task.transcript.Wav2Vec2TranscriptTask.init(Wav2Vec2TranscriptTask.java:80)
	at iped.engine.task.transcript.AudioTranscriptTask.init(AudioTranscriptTask.java:27)
	at iped.engine.core.Worker.initTasks(Worker.java:128)
	at iped.engine.core.Worker.<init>(Worker.java:110)
	at iped.engine.core.Manager.initWorkers(Manager.java:539)
	at iped.engine.core.Manager.process(Manager.java:264)
	at iped.app.processing.Main.startManager(Main.java:177)
	at iped.app.processing.Main.execute(Main.java:239)
	at iped.app.processing.Main.main(Main.java:304)
Caused by: java.io.IOException: CreateProcess error=2, O sistema não pode encontrar o arquivo especificado
	at java.base/java.lang.ProcessImpl.create(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(Unknown Source)
	at java.base/java.lang.ProcessImpl.start(Unknown Source)
```

**Comment by lfcnassif** [comment]
Reopening, it wasn't 100% fixed as reported by https://github.com/sepinf-inc/IPED/issues/1142#issuecomment-1613353961
