### ISSUE TITLE
No space left on device thrown by transcription nodes

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#1592]
Testing with latest 4.1.1 snapshot today, I got this on 3 nodes:
```
java.io.IOException: No space left on device
        at sun.nio.ch.FileDispatcherImpl.write0(Native Method) ~[?:?]
        at sun.nio.ch.FileDispatcherImpl.write(FileDispatcherImpl.java:62) ~[?:?]
        at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:113) ~[?:?]
        at sun.nio.ch.IOUtil.write(IOUtil.java:79) ~[?:?]
        at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:280) ~[?:?]
        at java.nio.channels.Channels.writeFullyImpl(Channels.java:74) ~[?:?]
        at java.nio.channels.Channels.writeFully(Channels.java:97) ~[?:?]
        at java.nio.channels.Channels$1.write(Channels.java:172) ~[?:?]
        at iped.engine.task.transcript.RemoteWav2Vec2Service$1.run(RemoteWav2Vec2Service.java:248) [iped-engine-4.2-snapshot.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
```

Checking them, there are a lot of wav files leaked in tmp folder.

**Comment by lfcnassif** [comment]
They were not being deleted after the job indeed... Affects just master.

**Comment by lfcnassif** [comment]
Just cleaned the nodes, I'll update them tomorrow.
