### ISSUE TITLE
AIOOBE in ScriptTask

### ISSUE THREAD

**Issue by aberenguel** [sepinf-inc/IPED#1625]
I'm using IPED 4.2-snapshot (commit 1e04e83bb)

The console logged these lines:
```
java.lang.Exception: Worker-3 Error while processing /item03_XXXX-PC_C_Drive001-antigo_vdi.E01/Users/XXXXXX/AppData/Local/Google/Chrome/User Data/System Profile/History (118784bytes)
        at iped.engine.core.Worker.process(Worker.java:186) ~[iped-engine-4.2-snapshot.jar:?]
        at iped.engine.core.Worker.run(Worker.java:265) ~[iped-engine-4.2-snapshot.jar:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 0
        at java.util.ArrayList.add(ArrayList.java:487) ~[?:?]
        at java.util.ArrayList.add(ArrayList.java:499) ~[?:?]
        at jdk.nashorn.internal.runtime.ScriptObject.addProtoFilter(ScriptObject.java:1941) ~[jdk.scripting.nashorn:?]
        at jdk.nashorn.internal.runtime.ScriptObject.findGetMethod(ScriptObject.java:2012) ~[jdk.scripting.nashorn:?]
        at jdk.nashorn.internal.runtime.ScriptObject.lookup(ScriptObject.java:1866) ~[jdk.scripting.nashorn:?]
        at jdk.nashorn.internal.runtime.linker.NashornLinker.getGuardedInvocation(NashornLinker.java:104) ~[jdk.scripting.nashorn:?]
        at jdk.nashorn.internal.runtime.linker.NashornLinker.getGuardedInvocation(NashornLinker.java:96) ~[jdk.scripting.nashorn:?]
        at jdk.dynalink.linker.support.CompositeTypeBasedGuardingDynamicLinker.getGuardedInvocation(CompositeTypeBasedGuardingDynamicLinker.java:161) ~[jdk.dynalink:?]
        at jdk.dynalink.linker.support.CompositeGuardingDynamicLinker.getGuardedInvocation(CompositeGuardingDynamicLinker.java:109) ~[jdk.dynalink:?]
        at jdk.dynalink.LinkerServicesImpl.lambda$getGuardedInvocation$0(LinkerServicesImpl.java:137) ~[jdk.dynalink:?]
        at jdk.dynalink.LinkerServicesImpl.getWithLookupInternal(LinkerServicesImpl.java:168) ~[jdk.dynalink:?]
        at jdk.dynalink.LinkerServicesImpl.getGuardedInvocation(LinkerServicesImpl.java:135) ~[jdk.dynalink:?]
        at jdk.dynalink.DynamicLinker.relink(DynamicLinker.java:242) ~[jdk.dynalink:?]
        at jdk.nashorn.internal.scripts.Script$Recompilation$188$371A$\^eval\_$cu1$restOf.process(<eval>:39) ~[?:?]
        at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:657) ~[jdk.scripting.nashorn:?]
        at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:513) ~[jdk.scripting.nashorn:?]
        at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:527) ~[jdk.scripting.nashorn:?]
        at jdk.nashorn.api.scripting.ScriptObjectMirror.callMember(ScriptObjectMirror.java:202) ~[jdk.scripting.nashorn:?]
        at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:393) ~[jdk.scripting.nashorn:?]
        at jdk.nashorn.api.scripting.NashornScriptEngine.invokeFunction(NashornScriptEngine.java:197) ~[jdk.scripting.nashorn:?]
        at iped.engine.task.ScriptTask.process(ScriptTask.java:122) ~[iped-engine-4.2-snapshot.jar:?]
        at iped.engine.task.AbstractTask.processMonitorTimeout(AbstractTask.java:277) ~[iped-engine-4.2-snapshot.jar:?]
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:192) ~[iped-engine-4.2-snapshot.jar:?]
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:225) ~[iped-engine-4.2-snapshot.jar:?]
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:205) ~[iped-engine-4.2-snapshot.jar:?]
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:225) ~[iped-engine-4.2-snapshot.jar:?]
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:205) ~[iped-engine-4.2-snapshot.jar:?]
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:225) ~[iped-engine-4.2-snapshot.jar:?]
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:205) ~[iped-engine-4.2-snapshot.jar:?]
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:225) ~[iped-engine-4.2-snapshot.jar:?]
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:205) ~[iped-engine-4.2-snapshot.jar:?]
...
```

**Comment by lfcnassif** [comment]
Could you share `History (118784bytes)` file privately so we can reproduce the issue?

**Comment by lfcnassif** [comment]
Thanks for the file. Unfortunately I wasn't able to reproduce the error, even copying the whole file path (with your replacements). Do you have any additional javascript script installed in the used profile? Have you changed any of them, e.g. RefineCategoryTask.js?

**Comment by lfcnassif** [comment]
Unfortunately I wasn't able to reproduce this, so I'll close as can't reproduce, sorry. If it happens again with the default profiles or if you can provide a step by step to reproduce it artificially, please reopen.

**Comment by lfcnassif** [comment]
Another user reported this happened 2 times with 4.1.1 version on Linux, randomly. So I'm reopening to investigate again. @aberenguel what SO did you use?

**Comment by lfcnassif** [comment]
I'm suspecting this is a JDK issue, what was the used java version?

**Comment by aberenguel** [comment]
> I'm suspecting this is a JDK issue, what was the used java version?

When the bug happened, I was using Liberica Full JDK 11.0.17.

**Comment by lfcnassif** [comment]
@aberenguel did you reproduce this again since then???

**Comment by aberenguel** [comment]
> [@aberenguel](https://github.com/aberenguel) is this still happening? Are you using the same Java version or have you updated it?

It happens sometimes. Maybe 1 in 50 executions. The solution is to running the processing command again. 
What I can do is to make a loop to run the command several times in order to make it reproducible and to debug when the exception is throw.

**Comment by aberenguel** [comment]
It happend again:
```
java.lang.Exception: Worker-15 Error while processing windows/$Recycle.Bin/S-1-5-21-4170757920-60181998-1900855022-1009 (0bytes)
        at iped.engine.core.Worker.process(Worker.java:186) ~[iped-engine-4.3.0-snapshot.jar:?]
        at iped.engine.core.Worker.run(Worker.java:265) ~[iped-engine-4.3.0-snapshot.jar:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 0
        at java.util.ArrayList.add(ArrayList.java:487) ~[?:?]
        at java.util.ArrayList.add(ArrayList.java:499) ~[?:?]
        at org.openjdk.nashorn.internal.runtime.ScriptObject.addProtoFilter(ScriptObject.java:1942) ~[nashorn-core-15.4.jar:?]
        at org.openjdk.nashorn.internal.runtime.ScriptObject.findGetMethod(ScriptObject.java:2013) ~[nashorn-core-15.4.jar:?]
        at org.openjdk.nashorn.internal.runtime.ScriptObject.lookup(ScriptObject.java:1867) ~[nashorn-core-15.4.jar:?]
        at org.openjdk.nashorn.internal.runtime.linker.NashornLinker.getGuardedInvocation(NashornLinker.java:104) ~[nashorn-core-15.4.jar:?]
        at org.openjdk.nashorn.internal.runtime.linker.NashornLinker.getGuardedInvocation(NashornLinker.java:96) ~[nashorn-core-15.4.jar:?]
        at jdk.dynalink.linker.support.CompositeTypeBasedGuardingDynamicLinker.getGuardedInvocation(CompositeTypeBasedGuardingDynamicLinker.java:161) ~[jdk.dynalink:?]
        at jdk.dynalink.linker.support.CompositeGuardingDynamicLinker.getGuardedInvocation(CompositeGuardingDynamicLinker.java:109) ~[jdk.dynalink:?]
        at jdk.dynalink.LinkerServicesImpl.lambda$getGuardedInvocation$0(LinkerServicesImpl.java:137) ~[jdk.dynalink:?]
        at jdk.dynalink.LinkerServicesImpl.getWithLookupInternal(LinkerServicesImpl.java:168) ~[jdk.dynalink:?]
        at jdk.dynalink.LinkerServicesImpl.getGuardedInvocation(LinkerServicesImpl.java:135) ~[jdk.dynalink:?]
        at jdk.dynalink.DynamicLinker.relink(DynamicLinker.java:242) ~[jdk.dynalink:?]
        at org.openjdk.nashorn.internal.scripts.Script$Recompilation$61$371A$\^eval\_.process(<eval>:61) ~[?:?]
        at org.openjdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:648) ~[nashorn-core-15.4.jar:?]
        at org.openjdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:513) ~[nashorn-core-15.4.jar:?]
        at org.openjdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:520) ~[nashorn-core-15.4.jar:?]
        at org.openjdk.nashorn.api.scripting.ScriptObjectMirror.callMember(ScriptObjectMirror.java:187) ~[nashorn-core-15.4.jar:?]
        at org.openjdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:379) ~[nashorn-core-15.4.jar:?]
        at org.openjdk.nashorn.api.scripting.NashornScriptEngine.invokeFunction(NashornScriptEngine.java:186) ~[nashorn-core-15.4.jar:?]
        at iped.engine.task.ScriptTask.process(ScriptTask.java:128) ~[iped-engine-4.3.0-snapshot.jar:?]
        at iped.engine.task.AbstractTask.processMonitorTimeout(AbstractTask.java:280) ~[iped-engine-4.3.0-snapshot.jar:?]
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:195) ~[iped-engine-4.3.0-snapshot.jar:?]
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:228) ~[iped-engine-4.3.0-snapshot.jar:?]
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:208) ~[iped-engine-4.3.0-snapshot.jar:?]
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:228) ~[iped-engine-4.3.0-snapshot.jar:?]
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:208) ~[iped-engine-4.3.0-snapshot.jar:?]
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:228) ~[iped-engine-4.3.0-snapshot.jar:?]
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:208) ~[iped-engine-4.3.0-snapshot.jar:?]
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:228) ~[iped-engine-4.3.0-snapshot.jar:?]
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:208) ~[iped-engine-4.3.0-snapshot.jar:?]
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:228) ~[iped-engine-4.3.0-snapshot.jar:?]
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:208) ~[iped-engine-4.3.0-snapshot.jar:?]
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:228) ~[iped-engine-4.3.0-snapshot.jar:?]
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:208) ~[iped-engine-4.3.0-snapshot.jar:?]
        at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:228) ~[iped-engine-4.3.0-snapshot.jar:?]
        at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:208) ~[iped-engine-4.3.0-snapshot.jar:?]
        at iped.engine.core.Worker.process(Worker.java:177) ~[iped-engine-4.3.0-snapshot.jar:?]
        ... 1 more
```

**Comment by lfcnassif** [comment]
> Are you using the same Java version or have you updated it?

What's your current java version?

**Comment by aberenguel** [comment]
`Java version: 11.0.27, vendor: BellSoft, runtime: /usr/lib/jvm/bellsoft-java11-full-amd64`

Despite that is the latest release, it happened with previous releases too.
