### ISSUE TITLE
Web service start up not working

### ISSUE THREAD

**Issue by mcsimioni** [sepinf-inc/IPED#1665]
Olá,

Estamos utilizando a versão 4.1.2 e tentando executar o servidor WEBAPI, mas sem sucesso.
Abaixo, apresento o erro gerado. Existe algum pré-requisito a ser observado para poder executar a WEBAPI?

Obrigado

Exception in thread "main" java.lang.NoSuchMethodError: 'com.fasterxml.jackson.databind.JavaType com.fasterxml.jackson.databind.introspect.AnnotatedMember.getType(com.fasterxml.jackson.databind.type.TypeBindings)'
        at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:425)
        at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:203)
        at io.swagger.converter.ModelConverterContextImpl.resolve(ModelConverterContextImpl.java:103)
        at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:257)
        at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:203)
        at io.swagger.converter.ModelConverterContextImpl.resolve(ModelConverterContextImpl.java:103)
        at io.swagger.jackson.ModelResolver.resolveProperty(ModelResolver.java:175)
        at io.swagger.jackson.ModelResolver.resolveProperty(ModelResolver.java:126)
        at io.swagger.converter.ModelConverterContextImpl.resolveProperty(ModelConverterContextImpl.java:83)
        at io.swagger.converter.ModelConverters.readAsProperty(ModelConverters.java:63)
        at io.swagger.jaxrs.Reader.parseMethod(Reader.java:905)
        at io.swagger.jaxrs.Reader.read(Reader.java:326)
        at io.swagger.jaxrs.Reader.read(Reader.java:176)
        at io.swagger.jaxrs.config.BeanConfig.scanAndRead(BeanConfig.java:252)
        at io.swagger.jaxrs.config.BeanConfig.setScan(BeanConfig.java:231)
        at iped.engine.webapi.Main.startServer(Main.java:40)
        at iped.engine.webapi.Main.main(Main.java:91)

**Comment by lfcnassif** [comment]
Sorry, there are months (maybe years) since I tested it last time... @patrickdalla could you take a look at this?

**Comment by patrickdalla** [comment]
Its seems a dependency needs to be update: swagger-jersey2-jaxrs
I changed it to the new version 1.6.10, and it passed. I will test for any side effect.

        <dependency>
    		<groupId>io.swagger</groupId>
    		<artifactId>swagger-jersey2-jaxrs</artifactId>
    		<version>1.6.10</version>
	</dependency>

**Comment by patrickdalla** [comment]
Well, after a little tests, it seems it worked. I search for other references to the Swagger dependency and it seems to be used only by WEBAPI. I will submit a PR.

**Comment by lfcnassif** [comment]
I'm closing this as fixed, please reopen if not. If #1173 is still an issue, or not, please report there.

**Comment by mcsimioni** [comment]
I compiled the code without any problems and I can run the webapi. Now I'm trying to solve an issue with JPT on Windows 10 ([main] ERROR iped.parsers.python.PythonParser - JEP not found, all python modules were disabled)

Thank you very much.
