### ISSUE TITLE
Aborting IllegalArgumentException: DocValuesField "parentIds" is too large, must be <= 32766 caused by GeofileParser stacking adjacent folders

### ISSUE THREAD

**Issue by hauck-jvsh** [sepinf-inc/IPED#1668]
An user send me a log with an exception that occur in a caverd EML. It looks like that the EMLhas an extremely deep EML struct. This leads to a very large number of parentIds, apparently breaking the max number of array elements in the lucene index.
I don't known what to do in this case, should I ignore the items after this limit? Or should put than without the parentIds?

**Comment by hauck-jvsh** [comment]
The error message:

> [B720]/Polyline [B71F]/Polyline [B71E]/Polyline [B71D]/Polyline [B71C]/Polyline [B71B]/Polyline [B71A]/Polyline [B719]/Line [B718]/Arc [B717]/Line [B716]/Arc [B715]/Arc [B714]/Arc [B713]/Arc [B713]:0 (1124bytes)
	at iped.engine.core.Worker.process(Worker.java:186) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.core.Worker.processNewItem(Worker.java:226) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.ParsingTask.parseEmbedded(ParsingTask.java:689) ~[iped-engine-4.1.2.jar:?]
	at iped.geo.parsers.GeofileParser.featureParser(GeofileParser.java:231) ~[iped-geo-4.1.2.jar:?]
	at iped.geo.parsers.GeofileParser.recursiveFolderParse(GeofileParser.java:116) ~[iped-geo-4.1.2.jar:?]
	at iped.geo.parsers.GeofileParser.recursiveFolderParse(GeofileParser.java:123) ~[iped-geo-4.1.2.jar:?]
	at iped.geo.parsers.GeofileParser.parse(GeofileParser.java:94) ~[iped-geo-4.1.2.jar:?]
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:298) ~[tika-core-2.4.0-p1.jar:2.4.0]
	at iped.parsers.standard.StandardParser.parse(StandardParser.java:245) ~[iped-parsers-impl-4.1.2.jar:?]
	at iped.engine.io.ParsingReader$BackgroundParsing.run(ParsingReader.java:247) ~[iped-engine-4.1.2.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.IllegalArgumentException: DocValuesField "parentIds" is too large, must be <= 32766
	at org.apache.lucene.index.SortedDocValuesWriter.addValue(SortedDocValuesWriter.java:77) ~[lucene-core-9.2.0.jar:9.2.0 ba8c3a806ada3d7b3c34d408e449a92376a8481b - romseygeek - 2022-05-19 15:10:13]
	at org.apache.lucene.index.IndexingChain.indexDocValue(IndexingChain.java:977) ~[lucene-core-9.2.0.jar:9.2.0 ba8c3a806ada3d7b3c34d408e449a92376a8481b - romseygeek - 2022-05-19 15:10:13]
	at org.apache.lucene.index.IndexingChain.processField(IndexingChain.java:758) ~[lucene-core-9.2.0.jar:9.2.0 ba8c3a806ada3d7b3c34d408e449a92376a8481b - romseygeek - 2022-05-19 15:10:13]
	at org.apache.lucene.index.IndexingChain.processDocument(IndexingChain.java:620) ~[lucene-core-9.2.0.jar:9.2.0 ba8c3a806ada3d7b3c34d408e449a92376a8481b - romseygeek - 2022-05-19 15:10:13]
	at org.apache.lucene.index.DocumentsWriterPerThread.updateDocuments(DocumentsWriterPerThread.java:241) ~[lucene-core-9.2.0.jar:9.2.0 ba8c3a806ada3d7b3c34d408e449a92376a8481b - romseygeek - 2022-05-19 15:10:13]
	at org.apache.lucene.index.DocumentsWriter.updateDocuments(DocumentsWriter.java:432) ~[lucene-core-9.2.0.jar:9.2.0 ba8c3a806ada3d7b3c34d408e449a92376a8481b - romseygeek - 2022-05-19 15:10:13]
	at org.apache.lucene.index.IndexWriter.updateDocuments(IndexWriter.java:1532) ~[lucene-core-9.2.0.jar:9.2.0 ba8c3a806ada3d7b3c34d408e449a92376a8481b - romseygeek - 2022-05-19 15:10:13]
	at org.apache.lucene.index.IndexWriter.addDocuments(IndexWriter.java:1503) ~[lucene-core-9.2.0.jar:9.2.0 ba8c3a806ada3d7b3c34d408e449a92376a8481b - romseygeek - 2022-05-19 15:10:13]
	at iped.engine.task.index.IndexTask.process(IndexTask.java:149) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.AbstractTask.processMonitorTimeout(AbstractTask.java:277) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:192) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:225) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:205) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:225) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.MinIOTask.sendToNextTask(MinIOTask.java:372) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:205) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:225) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:205) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:225) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:205) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:225) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:205) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:225) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:205) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:225) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:205) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:225) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.PythonTask.sendToNextTask(PythonTask.java:278) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:205) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:225) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.PythonTask.sendToNextTask(PythonTask.java:278) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:205) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:225) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.PythonTask.sendToNextTask(PythonTask.java:278) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:205) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:225) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:205) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:225) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:205) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:225) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:205) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:225) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:205) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:225) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:205) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:225) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:205) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:225) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:205) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:225) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:205) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:225) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:205) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:225) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:205) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:225) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:205) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:225) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:205) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:225) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:205) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:225) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:205) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:225) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:205) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:225) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:205) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:225) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:205) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:225) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:205) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:225) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:205) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:225) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:205) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:225) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:205) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:225) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:205) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:225) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:205) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:225) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:205) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:225) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:205) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:225) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:205) ~[iped-engine-4.1.2.jar:?]
	at iped.engine.core.Worker.process(Worker.java:177) ~[iped-engine-4.1.2.jar:?]

**Comment by lfcnassif** [comment]
What kind of XML is this file? Seems it is being processed by GeofileParser and that parser is generating this huge and deep subitem tree. Maybe the generated tree could be simplified/shortened... @patrickdalla, since you implemented that parser, could you take a look? @hauck-jvsh could you send the triggering file to @patrickdalla?

**Comment by lfcnassif** [comment]
PS: I think it would be difficult to workaround that Lucene limitation, so I think the easier path would be to generate a shorter subitem tree, if possible...

**Comment by hauck-jvsh** [comment]
Sorry, I correct the original message it is an EML not a XML file. The original user says it is an EML with a map attached.

**Comment by hauck-jvsh** [comment]
> What kind of XML is this file? Seems it is being processed by GeofileParser and that parser is generating this huge and deep subitem tree. Maybe the generated tree could be simplified/shortened... @patrickdalla, since you implemented that parser, could you take a look? @hauck-jvsh could you send the triggering file to @patrickdalla?

I will ask our collegue if he can share the file. He just share the log file with me.

**Comment by patrickdalla** [comment]
yes.

Em qui., 27 de abr. de 2023 18:30, Luis Filipe Nassif <
***@***.***> escreveu:

**Comment by patrickdalla** [comment]
the file will be very useful to find the best solution

Em qui., 27 de abr. de 2023 21:11, Patrick Bernardina <
***@***.***> escreveu:

**Comment by patrickdalla** [comment]
Looking at the log we can see only 2 calls to the method "recursiveFolderParse". So, it seems that in the the GeofileParser itself, only 2 levels of parent ID is added. Maybe this error occurred by chance in GeofileParser.

**Comment by hauck-jvsh** [comment]
The user says he will send the file. As soon as I receive the file I will sent it to you @patrickdalla. Anyway, if the max deep is achieved by any means do you think that the best behavior is to abort?

**Comment by lfcnassif** [comment]
32K seems a crazy nested subitem level to me, so I think we should look into the actual triggering file at first, maybe the file is corrupted, maybe there is some bug resulting in an infinite recursion, not sure...

**Comment by lfcnassif** [comment]
32K nested subitem level seems a bit crazy to me. I think we first should look into the triggering file, maybe it is corrupted, maybe it caused an infinite loop in some parser, so a fix at a parser level may be more appropriate. 

If it is a normal situation, we can think on a workaround to Lucene limitation, maybe prunning some deep subparents and putting deep children below some max parent level, or maybe just ignoring deep subparents in parentIds field before indexing it as a Lucene DocValue (this can cause some side effects, e.g. in Metadata panel filter when filtering for parentIds)

**Comment by lfcnassif** [comment]
> Looking at the log we can see only 2 calls to the method "recursiveFolderParse". So, it seems that in the the GeofileParser itself, only 2 levels of parent ID is added. Maybe this error occurred by chance in GeofileParser.

There are some for loops into that parser that can create a deep subitem tree without a deep method recursion. I changed that parser a while ago to make it thread safe, I tried to keep the previous logic and asked for review, maybe I broke it, maybe it was already broken, maybe the file really has a deep structure and we should change the parser approcah. Anyway, we need the trigering file...

**Comment by hauck-jvsh** [comment]
I just got the the files, how can I sent it to you @patrickdalla?

**Comment by patrickdalla** [comment]
via team

**Comment by patrickdalla** [comment]
It was an error of GeoFileParser that was stacking sequential folders one inside the other. I submitted the correction in branch GeoStackFoldersBug.

**Comment by lfcnassif** [comment]
Fixed by #1674.
