### ISSUE TITLE
Aborting ArrayIndexOutOfBoundsException from Lucene when creating reports with huge files

### ISSUE THREAD

**Issue by hauck-jvsh** [sepinf-inc/IPED#1676]
An user sent me a log containing an error that occurs when the index is being commited. Do you have any clue about what is causing this @lfcnassif ?

> 2023-05-06 14:24:28	[INFO]	[engine.core.Worker]			Worker-47 interrupted on /ST4000LM024-2AN17V WTL0AKZJ.E01/vol_vol6/Equipe08.zip (137813751449 bytes)
java.lang.IllegalStateException: this writer hit an unrecoverable error; cannot commit
	at org.apache.lucene.index.IndexWriter.startCommit(IndexWriter.java:5263)
	at org.apache.lucene.index.IndexWriter.prepareCommitInternal(IndexWriter.java:3535)
	at org.apache.lucene.index.IndexWriter.prepareCommit(IndexWriter.java:3355)
	at iped.engine.core.Manager$1.run(Manager.java:632)
	Suppressed: org.apache.lucene.store.AlreadyClosedException: refusing to delete any files: this IndexWriter hit an unrecoverable exception
		at org.apache.lucene.index.IndexFileDeleter.ensureOpen(IndexFileDeleter.java:400)
		at org.apache.lucene.index.IndexFileDeleter.deleteFiles(IndexFileDeleter.java:734)
		at org.apache.lucene.index.IndexFileDeleter.decRef(IndexFileDeleter.java:655)
		at org.apache.lucene.index.IndexWriter.prepareCommitInternal(IndexWriter.java:3545)
		... 2 more
	Caused by: java.lang.ArrayIndexOutOfBoundsException: Index -65536 out of bounds for length 71428
		at org.apache.lucene.index.TermsHashPerField.writeByte(TermsHashPerField.java:219)
		at org.apache.lucene.index.TermsHashPerField.writeVInt(TermsHashPerField.java:244)
		at org.apache.lucene.index.FreqProxTermsWriterPerField.writeProx(FreqProxTermsWriterPerField.java:86)
		at org.apache.lucene.index.FreqProxTermsWriterPerField.addTerm(FreqProxTermsWriterPerField.java:197)
		at org.apache.lucene.index.TermsHashPerField.positionStreamSlice(TermsHashPerField.java:212)
		at org.apache.lucene.index.TermsHashPerField.add(TermsHashPerField.java:200)
		at org.apache.lucene.index.IndexingChain$PerField.invert(IndexingChain.java:1224)
		at org.apache.lucene.index.IndexingChain.processField(IndexingChain.java:729)
		at org.apache.lucene.index.IndexingChain.processDocument(IndexingChain.java:620)
		at org.apache.lucene.index.DocumentsWriterPerThread.updateDocuments(DocumentsWriterPerThread.java:241)
		at org.apache.lucene.index.DocumentsWriter.updateDocuments(DocumentsWriter.java:432)
		at org.apache.lucene.index.IndexWriter.updateDocuments(IndexWriter.java:1532)
		at org.apache.lucene.index.IndexWriter.addDocuments(IndexWriter.java:1503)
		at iped.engine.task.index.IndexTask.process(IndexTask.java:149)
		at iped.engine.task.AbstractTask.processMonitorTimeout(AbstractTask.java:277)
		at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:192)
		at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:225)
		at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:205)
		at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:225)
		at iped.engine.task.MinIOTask.sendToNextTask(MinIOTask.java:372)
		at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:205)
		at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:225)
		at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:205)
		at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:225)
		at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:205)
		at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:225)
		at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:205)
		at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:225)
		at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:205)
		at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:225)
		at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:205)
		at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:225)
		at iped.engine.task.PythonTask.sendToNextTask(PythonTask.java:278)
		at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:205)
		at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:225)
		at iped.engine.task.PythonTask.sendToNextTask(PythonTask.java:278)
		at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:205)
		at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:225)
		at iped.engine.task.PythonTask.sendToNextTask(PythonTask.java:278)
		at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:205)
		at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:225)
		at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:205)
		at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:225)
		at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:205)
		at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:225)
		at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:205)
		at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:225)
		at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:205)
		at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:225)
		at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:205)
		at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:225)
		at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:205)
		at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:225)
		at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:205)
		at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:225)
		at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:205)
		at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:225)
		at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:205)
		at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:225)
		at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:205)
		at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:225)
		at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:205)
		at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:225)
		at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:205)
		at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:225)
		at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:205)
		at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:225)
		at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:205)
		at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:225)
		at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:205)
		at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:225)
		at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:205)
		at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:225)
		at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:205)
		at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:225)
		at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:205)
		at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:225)
		at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:205)
		at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:225)
		at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:205)
		at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:225)
		at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:205)
		at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:225)
		at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:205)
		at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:225)
		at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:205)
		at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:225)
		at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:205)
		at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:225)
		at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:205)
		at iped.engine.task.AbstractTask.sendToNextTask(AbstractTask.java:225)
		at iped.engine.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:205)
		at iped.engine.core.Worker.process(Worker.java:177)
		at iped.engine.core.Worker.run(Worker.java:265)
Caused by: [CIRCULAR REFERENCE: java.lang.ArrayIndexOutOfBoundsException: Index -65536 out of bounds for length 71428]

**Comment by lfcnassif** [comment]
This may be related to #1281

**Comment by lfcnassif** [comment]
Can the user share the triggering file?

**Comment by lfcnassif** [comment]
What version was used? Has the user disabled FragmentLargeBinaryTask or changed parameters in SplitLargeBinaryConfig.txt?

**Comment by hauck-jvsh** [comment]
The version used was the 4.1.2, the user report that processing the zip directly the error did not occur.

**Comment by lfcnassif** [comment]
> the user report that processing the zip directly the error did not occur.

As the input evidence or inside a folder? If he puts the ZIP inside a VHD image, is he able to reproduce?

**Comment by hauck-jvsh** [comment]
> As the input evidence or inside a folder? If he puts the ZIP inside a VHD image, is he able to reproduce?
As the input evidence

**Comment by hauck-jvsh** [comment]
No he didn't contact me with any updates.

**Comment by lfcnassif** [comment]
I think I discovered what happened. Looking at the log he sent, he was generating a report:
`Java Command: iped.app.processing.Main -d D:\XXXXXXXX\iped-4.1.2-semunalloc\relatorio\iped\bookmarks.iped -o E:\XXXXXX\laudo -log D:\XXXXXXX\files\IPED-matXXX-2023-iped4.1.2-3oprocessamento.txt`

And FragmentLargeBinaryTask is disabled when creating reports:
https://github.com/sepinf-inc/IPED/blob/4.1.2/iped-engine/src/main/java/iped/engine/task/FragmentLargeBinaryTask.java#L50

Not sure about the solution, since ideally we shouldn't create (or split) items when generating reports. Maybe just index (parent) items that were splitted using an empty text in reports, like they were in the first processing (their fragments/chunks are indexed properly).

**Comment by lfcnassif** [comment]
I just checked a test I left running early today and this was reproduced while generating a report.

Thinking better, indexing the parent item with no content is not enough, this can also be triggered when indexing its fragments, which have the same size as the parent item, it was the solution chosen on #1281. And we must index or the parent item or its fragments, the user should be able to find hits at least in one of them. So I think we will have to fragment those items again when generating the report. But, splitting the item fragments again is odd... not sure if there is a better solution, I'm open for ideas...

**Comment by lfcnassif** [comment]
> So I think we will have to fragment those items again when generating the report

Actually I think this specific point is not an issue itself, we already include items in reports not directly bookmarked by the user, such as email and chat attachments. But fragmenting item fragments again is not very good...

**Comment by lfcnassif** [comment]
Splitting the parent item and its fragments again when generating the report fixed the issue as expected. I'll apply this workaround for now. But I'm not happy with it, if anyone has a better idea, please let me know so we can improve.
