### ISSUE TITLE
Clear selection not correctly updated on Map

### ISSUE THREAD

**Issue by patrickdalla** [sepinf-inc/IPED#1740]
The table selection clear information is not correctly being informed to map. Some operations like changing the selected bookmark, or changing to timeline view clears the selected rows. These operations are not being correctly informed to map, and causing a exception that is logged in IPEDAppSearch.log.

**Comment by lfcnassif** [comment]
Thanks @patrickdalla! Just to document it here, this is the logged exception on current 4.1.x branch:
```
java.lang.IndexOutOfBoundsException: Invalid index
    at iped.app.ui.parallelsorter.ParallelRowSorter.convertRowIndexToModel(ParallelRowSorter.java:526)
    at java.desktop/javax.swing.JTable.convertRowIndexToModel(Unknown Source)
    at iped.geo.impl.MapViewer$2.run(MapViewer.java:165)
    at iped.geo.impl.AppMapPanel.runAfterLoad(AppMapPanel.java:344)
    at iped.geo.impl.MapViewer.valueChanged(MapViewer.java:195)
    at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
    at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
    at java.desktop/javax.swing.DefaultListSelectionModel.setValueIsAdjusting(Unknown Source)
    at java.desktop/javax.swing.JTable.restoreSortingSelection(Unknown Source)
    at java.desktop/javax.swing.JTable$SortManager.restoreSelection(Unknown Source)
    at java.desktop/javax.swing.JTable$SortManager.processChange(Unknown Source)
    at java.desktop/javax.swing.JTable.sortedTableChanged(Unknown Source)
    at java.desktop/javax.swing.JTable.sorterChanged(Unknown Source)
    at java.desktop/javax.swing.RowSorter.fireRowSorterChanged(Unknown Source)
    at java.desktop/javax.swing.RowSorter.fireRowSorterChanged(Unknown Source)
    at iped.app.ui.parallelsorter.ParallelRowSorter.sortExistingData(ParallelRowSorter.java:570)
    at iped.app.ui.parallelsorter.ParallelRowSorter.setSortKeys(ParallelRowSorter.java:317)
    at iped.app.ui.ResultTableRowSorter.setSortKeys(ResultTableRowSorter.java:86)
    at iped.app.ui.AppListener.updateFileListing(AppListener.java:61)
    at iped.app.ui.AppListener.updateFileListing(AppListener.java:43)
    at iped.app.ui.TimelineListener.updateGUI(TimelineListener.java:59)
    at iped.app.ui.TimelineListener.toggleTimelineTableView(TimelineListener.java:46)
    at iped.app.ui.TimelineListener.actionPerformed(TimelineListener.java:41)
```
