### ISSUE TITLE
Can't launch processing, Wrong index checksum, store was not closed properly and could be corrupted

### ISSUE THREAD

**Issue by reacan** [sepinf-inc/IPED#190]
Hello everyone!

It looks like my IPED installation has become corrupt somehow and I cannot launch processing anymore. I get the following error message:

root@kali-03:/media/Skyhawk10TB/2.Ekspertīzes# java -jar ~/Apps/IPED/target/release/iped-3.17.1/iped.jar -d /media/Skyhawk10TB/bckps/USB_notes_30.04.dd -o /media/Skyhawk10TB/IPED_usb_notes -profile forensic
2020-07-07 16:04:21	[ERROR]	[gpinf.indexer.IndexFiles]			Processing Error: 
java.io.IOError: java.io.IOException: Wrong index checksum, store was not closed properly and could be corrupted.
	at org.mapdb.StoreDirect.checkHeaders(StoreDirect.java:269) ~[mapdb-1.0.9.jar:?]
	at org.mapdb.StoreDirect.<init>(StoreDirect.java:207) ~[mapdb-1.0.9.jar:?]
	at org.mapdb.DBMaker.extendStoreDirect(DBMaker.java:971) ~[mapdb-1.0.9.jar:?]
	at org.mapdb.DBMaker.makeEngine(DBMaker.java:758) ~[mapdb-1.0.9.jar:?]
	at org.mapdb.DBMaker.make(DBMaker.java:701) ~[mapdb-1.0.9.jar:?]
	at dpf.sp.gpinf.indexer.process.task.KFFTask.init(KFFTask.java:132) ~[iped-engine-3.17.1.jar:?]
	at dpf.sp.gpinf.indexer.process.Worker.initTasks(Worker.java:111) ~[iped-engine-3.17.1.jar:?]
	at dpf.sp.gpinf.indexer.process.Worker.<init>(Worker.java:93) ~[iped-engine-3.17.1.jar:?]
	at dpf.sp.gpinf.indexer.process.Manager.iniciarIndexacao(Manager.java:313) ~[iped-engine-3.17.1.jar:?]
	at dpf.sp.gpinf.indexer.process.Manager.process(Manager.java:195) ~[iped-engine-3.17.1.jar:?]
	at dpf.sp.gpinf.indexer.IndexFiles.doInBackground(IndexFiles.java:216) [iped.jar:?]
	at dpf.sp.gpinf.indexer.IndexFiles.doInBackground(IndexFiles.java:59) [iped.jar:?]
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295) [?:1.8.0_241]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_241]
	at javax.swing.SwingWorker.run(SwingWorker.java:334) [?:1.8.0_241]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_241]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_241]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]
Caused by: java.io.IOException: Wrong index checksum, store was not closed properly and could be corrupted.
	... 18 more

ERROR!!!
Check the log at /root/Apps/IPED/target/release/iped-3.17.1/log/IPED-2020-07-07-16-04-14.log

I am wondering maybe there a relatively easy way how this can be fixed without reinstalling the program? Also, any advice on how I can avoid this from happening in the future? 

Thanks in advance :)

**Comment by lfcnassif** [comment]
Your hash database index became corrupted. Comment out kffDb param in LocalConfig.txt or generate the hash index again from scratch (point kffDb to other file and import NSRL again).

Hopefully it will not happen again after commit baacd099fb54656752c70b3b6408475858a39320 already integrated in 3.18-beta version.

**Comment by reacan** [comment]
Thank you, Luis! Everything works now :+1:

**Comment by lfcnassif** [comment]
You're welcome.
