### ISSUE TITLE
Occasional exception when selecting the Map tab

### ISSUE THREAD

**Issue by tc-wleite** [sepinf-inc/IPED#1973]
It is just a minor detail, but sometimes looking at IPED-SearchApp.log I see the following exception (using cases processed with the master branch):
```
Exception in thread "JavaFX Application Thread" netscape.javascript.JSException: TypeError: undefined is not an object (evaluating 'mark.selected='true'')
	at javafx.web/com.sun.webkit.dom.JSObject.fwkMakeException(Unknown Source)
	at javafx.web/com.sun.webkit.WebPage.twkExecuteScript(Native Method)
	at javafx.web/com.sun.webkit.WebPage.executeScript(Unknown Source)
	at javafx.web/javafx.scene.web.WebEngine.executeScript(Unknown Source)
	at iped.geo.openstreet.MapCanvasOpenStreet$7.run(MapCanvasOpenStreet.java:376)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

Processing a single JPG file (without EXIF), then opening the case, selecting it in the items table and finally selecting the Map tab, I got the exception in the few attempts that I made. So it seems reproducible, but I am not sure if there is some other condition.

**Comment by lfcnassif** [comment]
Thanks for reporting @tc-wleite. By selecting the item do you mean checking or highlighting? @patrickdalla could you take a look?

**Comment by tc-wleite** [comment]
> By selecting the item do you mean checking or highlighting?

Highlighting.

**Comment by patrickdalla** [comment]
ok

Em qui., 9 de nov. de 2023 22:35, Wladimir Leite ***@***.***>
escreveu:

**Comment by lfcnassif** [comment]
I wasn't able to reproduce this with 4.1.5, just with master, so I'm updating the title.
