### ISSUE TITLE
NullPointerExceptions in AppMapPanel class

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#2121]
While testing #1613, I just saw exceptions like this in the analysis log:

```
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at iped.geo.impl.AppMapPanel.hasItem(AppMapPanel.java:571)
	at iped.geo.impl.MapViewer.applyCheckedItems(MapViewer.java:174)
	at iped.geo.impl.AppMapPanel.update(AppMapPanel.java:365)
	at iped.geo.impl.MapViewer$1.run(MapViewer.java:95)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

Not sure if it affects just master or also 4.1.5.

**Comment by lfcnassif** [comment]
Another NullPointerException:
```
java.lang.NullPointerException
	at iped.geo.openstreet.MapCanvasOpenStreet.updateUI(MapCanvasOpenStreet.java:475)
	at iped.geo.openstreet.MapCanvasOpenStreet.update(MapCanvasOpenStreet.java:463)
	at iped.geo.impl.AppMapPanel.update(AppMapPanel.java:366)
	at iped.geo.impl.MapViewer$1.run(MapViewer.java:95)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by wladimirleite** [comment]
I am getting the first exception in some cases here (processed with the master branch).

**Comment by patrickdalla** [comment]
> Another NullPointerException:
> 
> ```
> java.lang.NullPointerException
> 	at iped.geo.openstreet.MapCanvasOpenStreet.updateUI(MapCanvasOpenStreet.java:475)
> 	at iped.geo.openstreet.MapCanvasOpenStreet.update(MapCanvasOpenStreet.java:463)
> 	at iped.geo.impl.AppMapPanel.update(AppMapPanel.java:366)
> 	at iped.geo.impl.MapViewer$1.run(MapViewer.java:95)
> 	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
> 	at java.base/java.security.AccessController.doPrivileged(Native Method)
> 	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
> 	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
> 	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
> 	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
> 	at java.base/java.lang.Thread.run(Unknown Source)
> ```

@lfcnassif The above exception occured in master branch? It seems to refers to a line (475) that would never be reached in case of NullException as the unique object variable referenced is also referenced in the line just before.

**Comment by lfcnassif** [comment]
> @lfcnassif Did the above exception occur in master branch? It seems to refers to a line (475) that would never be reached in case of NullException as the unique object variable referenced is also referenced in the line just before.

I think it is, I should have pointed the commit reference, sorry. If you are not able to reproduce it, I can try in the end of this week.

**Comment by lfcnassif** [comment]
> > Another NullPointerException:
> > ```
> > java.lang.NullPointerException
> > 	at iped.geo.openstreet.MapCanvasOpenStreet.updateUI(MapCanvasOpenStreet.java:475)
> > 	at iped.geo.openstreet.MapCanvasOpenStreet.update(MapCanvasOpenStreet.java:463)
> > 	at iped.geo.impl.AppMapPanel.update(AppMapPanel.java:366)
> > 	at iped.geo.impl.MapViewer$1.run(MapViewer.java:95)
> > 	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
> > 	at java.base/java.security.AccessController.doPrivileged(Native Method)
> > 	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
> > 	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
> > 	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
> > 	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
> > 	at java.base/java.lang.Thread.run(Unknown Source)
> > ```
> 
> @lfcnassif Did the above exception occur in master branch? It seems to refers to a line (475) that would never be reached in case of NullException as the unique object variable referenced is also referenced in the line just before.

Just reproduced the stacktrace above with master commit 5585ade testing with a case without georeferenced items. I'll test the proposed PR.
