### ISSUE TITLE
Folders (inside a forensic image) with a huge number of files may be ignored

### ISSUE THREAD

**Issue by wladimirleite** [sepinf-inc/IPED#2136]
This was found by @hugohmk and I was able to reproduce it.
A folder with **one million** files in a NTFS (inside a E01) was silently ignored (no error, but its content was not added to the case).
A similar folder, with 600,000 files, was processed correctly.

To identify the problem's cause, I ran the standalone "tsk_loaddb.exe" and observed the same behavior, using TSK 4.12.0 and 4.12.1.
However, when I tried 4.11.1 (the version before 4.12.0), it worked fine.

Having such a huge number of files in the same folder should be an extremely unusual situation, but it is possible and allowed by NTFS.

**Comment by lfcnassif** [comment]
Well, unfortunately, that was an intentional Sleuthkit change... I'll search for the related issue and post it here.

**Comment by lfcnassif** [comment]
@wladimirleite, while running your tests, did you see big memory consumption issues or excessive slowness?

**Comment by wladimirleite** [comment]
> @wladimirleite, while running your tests, did you see big memory consumption issues or excessive slowness?

Using 4.11.1, tsk_loaddb.exe took a while (~40 minutes), but I didn't monitor memory.
With IPED processing (and tsk_loaddb.exe 4.12.0), it was very fast (only a minute or so), but the folder and all its files were ignored.

**Comment by wladimirleite** [comment]
> I agree with those stating it should at least be configurable, e.g. with an environment variable parameter.

Indeed. And maybe an option to abort with an error, instead of just silently ignoring.
 
> We can patch our Sleuthkit fork to implement that, I'm not happy to maintain a fork...

I don't think it is worth the effort to maintain a fork.
Since @hugohmk provided a E01 with a folder with 3 million files, I will try to raise the hardcoded limit in TSK and see what happens in terms of memory consumption and slowness.
As I said, this should be very rare, but once we try to process a disk image with such a condition, it can be very dangerous, as a lot of files will be ignored without any clear warning.

**Comment by lfcnassif** [comment]
> As I said, this should be very rare, but once we try to process a disk image with such a condition, it can be very dangerous, as a lot of files will be ignored without any clear warning.

Has tsk_loaddb.exe 4.12+ written some warning/error in the Console? If yes, was that logged in IPED logs? PS: Actually we use the java bindings, which output can be different than tsk_loaddb, we try to detect critical errors errors from TSK java binding output, log some of them and redirect others to IPED console, maybe we are failing in the error detection part...

**Comment by lfcnassif** [comment]
> Using 4.11.1, tsk_loaddb.exe took a while (~40 minutes), but I didn't monitor memory.

Well, I have seen a few cases taking a similar or more time in tsk_loaddb to decode the FS tree, not sure if they are related to this issue...

**Comment by wladimirleite** [comment]
No output in the console using tsk_loaddb.
I later saw some messages using its verbose command line option, but it generated several GB of log, so it wasn't possible to identify what was going on.

**Comment by lfcnassif** [comment]
@markmckinnon if we send a PR to Sleuthkit making that hard coded limit configurable, will it be reviewed?

**Comment by markmckinnon** [comment]
@lfcnassif it should be reviewed and implemented as this can also effect Autopsy as well.

**Comment by lfcnassif** [comment]
Thanks @markmckinnon, we will try to propose a PR to Sleuthkit repo then.

**Comment by lfcnassif** [comment]
Do you think using an environment variable, like TSK_MAX_ENTRIES_PER_FOLDER is a good approach? If not set, keep current limit. If set, use the configured value. If set to -1, disable the limit. Looks fine?

**Comment by markmckinnon** [comment]
So each tool that wants to make a new limit or no limit will have to set an environment variable in what ever OS they are running in instead of using a command line argument?

**Comment by lfcnassif** [comment]
Yes, that would work for us, and minor code changes would be needed, with no TSK API or internal data structures changes. But I understand that would be a global system configuration that would affect all TSK depending tools, and maybe different tools would need a different configuration...

**Comment by wladimirleite** [comment]
I confirmed with @hugohmk a while ago, it was in an artificial image (generated to test another unrelated possible performance issue).
I planned to investigate it a bit more, maybe suggesting a better solution inside TSK, but couldn't find time so far, as I am not familiar with its code.

**Comment by lfcnassif** [comment]
I can implement the environment variable workaround in our fork, but I'm asking to check the priority of this fix, if it should go into 4.2.0 or not.

**Comment by wladimirleite** [comment]
No, I don't think it is critical.

**Comment by lfcnassif** [comment]
Should we close this as won't fix since it was triggered by synthetic data? Should we implement a workaround in our fork **when** we upgrade TSK?

**Comment by wladimirleite** [comment]
As it is highly unlike to have this in real cases, I would just close it as won't fix.

**Comment by lfcnassif** [comment]
Seems TSK project fortunately decided to propagate and log the situation instead of silently skipping huge dirs:
https://github.com/sleuthkit/sleuthkit/pull/3300

**Comment by lfcnassif** [comment]
Seems an IPED user was affected in a real case by this. I asked him to report the details here.

**Comment by ney824** [comment]
It seems I got the same issue: there were too many files inside a single directory in an E01 image with the NTFS file system.

A folder containing 171,702 files was indexed without any problems. However, four folders with approximately 317k, 393k, 665k, and 1,087k files each, were completely ignored, with no errors or log messages generated.

About 50% of the files were image files (JPG, PNG, etc.), and the remaining files were mostly .json metadata. This data originally comes from a cloud backup, so i see it being a potential issue in this cases.

**Comment by lfcnassif** [comment]
Thanks for giving details @ney824.

> A folder containing 171,702 files was indexed without any problems. However, four folders with approximately 317k, 393k, 665k, and 1,087k files each, were completely ignored, with no errors or log messages generated.

So it may be something else, because AFAIK sleuthkit ignores just folders with more than 1M files: https://github.com/sleuthkit/sleuthkit/blob/7236282c13d873f64803fd710e9618071a56a92f/tsk/fs/tsk_fs_i.h#L72-L75

Could you please reprocess your case with IPED-4.0.7 with fastmode profile? It uses an older version of sleuthkit, without the "discard folders with +1M files" change.

**Comment by ney824** [comment]
As suggested, I ran the case again using IPED-4.0.7 with the fastmode profile, and the folders were indexed correctly.
However, when I used IPED-4.3.0 with fastmode profile, the folders were still completely ignored.

**Comment by lfcnassif** [comment]
I will try to patch our current fork to remove this 1M limit. Again, I don't like to maintain a fork. Ideally, we should upgrade to TSK-4.14 (#2229), but currently I don't have time to reapply our patches over it and to run regression tests.

**Comment by lfcnassif** [comment]
Is this still an issue after merging #2865?

**Comment by lfcnassif** [comment]
@ney824, please test this new snapshot on your problematic image, maybe TSK-4.15 fixed it, not sure:
https://github.com/sepinf-inc/IPED/actions/runs/27038162407

**Comment by hugohmk** [comment]
> Is this still an issue after merging [#2865](https://github.com/sepinf-inc/IPED/pull/2865)?

I believe so. Sleuth is still skipping folders with 1m+ files. By the way, it is also skipping nested folders with a depth of 170+ approximately (tested on a NTFS forensic image). I'm sending a sample image that shows the issue: [nested2k.zip](https://github.com/user-attachments/files/28712555/nested2k.zip)

IPED managed to handle a partition with a folder containing a large number of files by processing it directly (-d "partition"), as well as a nested folder with depth of 2k+ on a NTFS (sample image). It only showed an issue handling a nested folder approaching the maximum NTFS path length (32k+ nested folders), with the following error message:
```[ERROR] [app.processing.Main]                   Processing Error:
java.lang.Exception: Worker-14 Error while processing "LARGE_NESTED_FOLDER"
        at iped.engine.core.Worker.process(Worker.java:188) ~[iped-engine-4.4.0-SNAPSHOT.jar:?]
        at iped.engine.core.Worker.run(Worker.java:267) ~[iped-engine-4.4.0-SNAPSHOT.jar:?]
Caused by: java.lang.IllegalArgumentException: DocValuesField "parentIds" is too large, must be <= 32766
        at org.apache.lucene.index.SortedDocValuesWriter.addValue(SortedDocValuesWriter.java:77) ~[lucene-core-9.2.0.jar:9.2.0 ba8c3a806ada3d7b3c34d408e449a92376a8481b - romseygeek - 2022-05-19 15:10:13
        at org.apache.lucene.index.IndexingChain.indexDocValue(IndexingChain.java:977) ~[lucene-core-9.2.0.jar:9.2.0 ba8c3a806ada3d7b3c34d408e449a92376a8481b - romseygeek - 2022-05-19 15:10:13]
        at org.apache.lucene.index.IndexingChain.processField(IndexingChain.java:758) ~[lucene-core-9.2.0.jar:9.2.0 ba8c3a806ada3d7b3c34d408e449a92376a8481b - romseygeek - 2022-05-19 15:10:13]
        at org.apache.lucene.index.IndexingChain.processDocument(IndexingChain.java:620) ~[lucene-core-9.2.0.jar:9.2.0 ba8c3a806ada3d7b3c34d408e449a92376a8481b - romseygeek - 2022-05-19 15:10:13]
        at org.apache.lucene.index.DocumentsWriterPerThread.updateDocuments(DocumentsWriterPerThread.java:241) ~[lucene-core-9.2.0.jar:9.2.0 ba8c3a806ada3d7b3c34d408e449a92376a8481b - romseygeek - 2022-05-19 15:10:13]
        at org.apache.lucene.index.DocumentsWriter.updateDocuments(DocumentsWriter.java:432) ~[lucene-core-9.2.0.jar:9.2.0 ba8c3a806ada3d7b3c34d408e449a92376a8481b - romseygeek - 2022-05-19 15:10:13]
        at org.apache.lucene.index.IndexWriter.updateDocuments(IndexWriter.java:1532) ~[lucene-core-9.2.0.jar:9.2.0 ba8c3a806ada3d7b3c34d408e449a92376a8481b - romseygeek - 2022-05-19 15:10:13]
        at org.apache.lucene.index.IndexWriter.addDocuments(IndexWriter.java:1503) ~[lucene-core-9.2.0.jar:9.2.0 ba8c3a806ada3d7b3c34d408e449a92376a8481b - romseygeek - 2022-05-19 15:10:13]
        at iped.engine.task.index.IndexTask.process(IndexTask.java:149) ~[iped-engine-4.4.0-SNAPSHOT.jar:?]
```
