### ISSUE TITLE
Some iOS WhatsApp DBs are not parsed

### ISSUE THREAD

**Issue by wladimirleite** [sepinf-inc/IPED#2190]
When selecting from group members table (ZWAGROUPMEMBER), some members (ZMEMBERJID column) are null, causing a NPE in WhatsAppParser. I had this exception processing a recently generated UFDR, using the master branch. I just checked, and it also affects 4.1.6.

```text
org.apache.tika.exception.TikaException: WAExtractorException Exception
	at iped.parsers.whatsapp.WhatsAppParser.parseWhatsappMessages(WhatsAppParser.java:394)
	at iped.parsers.whatsapp.WhatsAppParser.parse(WhatsAppParser.java:265)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:298)
	at iped.parsers.standard.StandardParser.parse(StandardParser.java:245)
	at iped.engine.io.ParsingReader$BackgroundParsing.run(ParsingReader.java:247)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at iped.parsers.whatsapp.Extractor.setGroupMembers(Extractor.java:65)
	at iped.parsers.whatsapp.ExtractorIOS.extractChatList(ExtractorIOS.java:257)
	at iped.parsers.whatsapp.Extractor.getChatList(Extractor.java:34)
	at iped.parsers.whatsapp.WhatsAppParser.parseWhatsappMessages(WhatsAppParser.java:386)
```

**Comment by wladimirleite** [comment]
By the way, I checked in the triggering DBs and confirmed that there are NULL values in a few rows.
