### ISSUE TITLE
Error processing DD

### ISSUE THREAD

**Issue by aberenguel** [sepinf-inc/IPED#2253]
Using Ubuntu 24.04 with latest IPED (master d436a740d), profile pedo.

The error occurred in the end of processing. 

```
2024-06-28 03:26:28     [INFO]  [engine.core.Manager]                   Changed to processing queue with priority 1
2024-06-28 03:26:28     [INFO]  [engine.data.IPEDSource]                        Opening index /xxxxxxxxx/iped/index
2024-06-28 03:26:51     [INFO]  [engine.data.IPEDSource]                        Index opened
2024-06-28 03:26:51     [INFO]  [engine.data.IPEDSource]                        Creating LuceneId to ID mapping...
java.lang.RuntimeException: double[]
        at iped.engine.data.IPEDSource.<init>(IPEDSource.java:252)
        at iped.engine.data.IPEDSource.<init>(IPEDSource.java:161)
        at iped.engine.search.ItemSearcher.<init>(ItemSearcher.java:29)
        at iped.engine.core.Manager.monitorProcessing(Manager.java:622)
        at iped.engine.core.Manager.process(Manager.java:298)
        at iped.app.processing.Main.startManager(Main.java:178)
        at iped.app.processing.Main.execute(Main.java:240)
        at iped.app.processing.Main.main(Main.java:308)
Caused by: java.lang.ClassNotFoundException: double[]
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:315)
        at iped.engine.task.index.IndexItem.loadMetadataTypes(IndexItem.java:220)
        at iped.engine.data.IPEDSource.<init>(IPEDSource.java:236)
        ... 7 more
2024-06-28 03:26:57     [ERROR] [app.processing.Main]                   Processing Error: 
java.lang.RuntimeException: double[]
        at iped.engine.data.IPEDSource.<init>(IPEDSource.java:252) ~[iped-engine-4.2-snapshot.jar:?]
        at iped.engine.data.IPEDSource.<init>(IPEDSource.java:161) ~[iped-engine-4.2-snapshot.jar:?]
        at iped.engine.search.ItemSearcher.<init>(ItemSearcher.java:29) ~[iped-engine-4.2-snapshot.jar:?]
        at iped.engine.core.Manager.monitorProcessing(Manager.java:622) ~[iped-engine-4.2-snapshot.jar:?]
        at iped.engine.core.Manager.process(Manager.java:298) ~[iped-engine-4.2-snapshot.jar:?]
        at iped.app.processing.Main.startManager(Main.java:178) [iped.jar:?]
        at iped.app.processing.Main.execute(Main.java:240) [iped.jar:?]
        at iped.app.processing.Main.main(Main.java:308) [iped.jar:?]
Caused by: java.lang.ClassNotFoundException: double[]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:315) ~[?:?]
        at iped.engine.task.index.IndexItem.loadMetadataTypes(IndexItem.java:220) ~[iped-engine-4.2-snapshot.jar:?]
        at iped.engine.data.IPEDSource.<init>(IPEDSource.java:236) ~[iped-engine-4.2-snapshot.jar:?]
        ... 7 mor
```

**Comment by aberenguel** [comment]
Trying to continue with `--continue` leads to the same error.

**Comment by wladimirleite** [comment]
Does it work with IPED 4.1.x?
Can you share the image with me so I can take a closer look?

**Comment by aberenguel** [comment]
I investigated and found that the file `iped/conf/metadataTypes.txt` in the case has the following line:
```
face_encodings = double[]
```

**Comment by aberenguel** [comment]
> Does it work with IPED 4.1.x? 
I haven't tested yet.

> Can you share the image with me so I can take a closer look?
The image has 900 GB. Should I share locally with you?

**Comment by wladimirleite** [comment]
> I investigated and found that the file `iped/conf/metadataTypes.txt` in the case has the following line:
> 
> ```
> face_encodings = double[]
> ```

Trt to remove this line. I don't see it in my local version of this files, neither in the master branch.

**Comment by aberenguel** [comment]
> > I investigated and found that the file `iped/conf/metadataTypes.txt` in the case has the following line:
> > ```
> > face_encodings = double[]
> > ```
> 
> Try to remove this line. I don't see it in my local version of this file, neither in the master branch.

This line is only in the `metadataTypes.txt` file of the case. I set `enableFaceRecognition = true`.

**Comment by aberenguel** [comment]
I think the bug can be here: 
https://github.com/sepinf-inc/IPED/blob/d436a740da72e56d87da6b6bdc1b77c4ddbff156/iped-engine/src/main/java/iped/engine/task/index/IndexItem.java#L208

**Comment by aberenguel** [comment]
> > I investigated and found that the file `iped/conf/metadataTypes.txt` in the case has the following line:
> > ```
> > face_encodings = double[]
> > ```
> 
> Try to remove this line. I don't see it in my local version of this file, neither in the master branch.

I replaced by `face_encodings = [D` and worked!

**Comment by wladimirleite** [comment]
There are no arrays in metadataTypes.txt.
I guess it should either ignore (not save in the file) array values, or set it as the corresponding object wrapper class of the array elements (in this case java.lang.Double).

**Comment by lfcnassif** [comment]
> face_encodings = double[]

Arrays shouldn't appear into metadataTypes.txt.

> or set it as the corresponding object wrapper class of the array elements (in this case java.lang.Double).

I think this is the better approach.

**Comment by lfcnassif** [comment]
I'll try to reproduce the issue here, I think it happens when the first image where a face is detected have 2 or more faces. If the first image has 1 face, it works with later images with 2+ faces.

**Comment by wladimirleite** [comment]
> This line is only in the `metadataTypes.txt` file of the case. I set `enableFaceRecognition = true`.

@aberenguel, is it an "--append"?

**Comment by lfcnassif** [comment]
@aberenguel what is the jep python lib version you installed on Linux?

**Comment by aberenguel** [comment]
> --append

No. It is the first evidence.

**Comment by lfcnassif** [comment]
I processed a case with a single image with 2 faces and I didn't reproduce. The mapping into conf/metadataTypes.txt is:
> face_encodings = jep.NDArray

Not sure from where that double[] is coming from...

**Comment by aberenguel** [comment]
> @aberenguel what is the jep python lib version you installed on Linux?

I'm using Python virtual environments. It used jep 4.0.3: `./lib/python3.12/site-packages/jep/jep-4.0.3.jar`

**Comment by lfcnassif** [comment]
You didn't change FaceRecognitionTask.py code, right?

**Comment by aberenguel** [comment]
> You didn't change FaceRecognitionTask.py code, right?

No. It was not modified.

**Comment by aberenguel** [comment]
I wonder if it is thing related to Python 3.12.

**Comment by aberenguel** [comment]
Processing a folder with this single file triggers this issue.
![0317_Crime_Boss_Rockay_City](https://github.com/sepinf-inc/IPED/assets/2973359/176ab334-d836-45ff-bf70-387b873c6a51)

**Comment by lfcnassif** [comment]
I wasn't able to reproduce on Windows with image above, IPED detected 7 faces in that image with the correct type:
`face_encodings = jep.NDArray`

Please @aberenguel try to reproduce on Linux with python 3.9, the same used on Windows.

**Comment by aberenguel** [comment]
> Please @aberenguel try to reproduce on Linux with python 3.9 and numpy 1.x (not 2.0), the same used on Windows.


Ubuntu 24.04 has only python 3.12. I'll try to get python 3.9 in other way.
Btw, the numpy is version 1.26.4.

**Comment by lfcnassif** [comment]
Try to use conda

**Comment by lfcnassif** [comment]
@aberenguel have you confirmed this happens because of python 3.12? Does it work with previous python versions?

**Comment by aberenguel** [comment]
> @aberenguel have you confirmed this happens because of python 3.12? Does it work with previous python versions?

I've just tested with Python 3.9.19 (fresh installing modules `jep==4.0.3`, `tensorflow`, `face_recognition` and `bs4`).
The error was the same.

I get some old cases I processed in Ubuntu 22.04 and they have `face_encodings = jep.NDArray`.
So I think it is not related to Python version.

**Comment by aberenguel** [comment]
Another test I've just did. 
I upgraded the jep to version `4.2.0` (in pom.xml and with pip).
There is no error anymore and the case was generated with `face_encodings = jep.NDArray`.

**Comment by lfcnassif** [comment]
> I upgraded the jep to version `4.2.0` (in pom.xml and with pip).

Great! I was just going to ask you to try that :-)

**Comment by aberenguel** [comment]
Confirmed that JEP 4.2.0 solved the problem with Python 3.9 and 3.12

**Comment by patrickdalla** [comment]
Great, @aberenguel , thank you for testing.
JEP 4.2 has some important improvements, mainly "Java Methods can be Annotated to accept Python kwargs", that will be very useful in Aleapp integration.
I have made some workaround code for ALeapp bridge task working with the old JEP version, but I think I can remove them with JEP 4.2 and make a cleaner and less complex integration code.

**Comment by aberenguel** [comment]
A colleage reporte the problem is happening again. Tested with JPED 4.2.2 and 4.2.0.

The after the processing, the value of `item.getExtraAttribute(ExtraProperties.FACE_ENCODINGS)` is of type `ArrayList<double[]>`. It should be `ArrayList<jep.NDArray>`. I don't known if it can be related to numpy version. In my Python virtual environment the numpy version is 1.26.4

**Comment by lfcnassif** [comment]
And do you know what is the numpy and JEP versions in you colleague's environment?

@aberenguel, could you work on this upgrade, testing on Linux and Windows?

**Comment by aberenguel** [comment]
> And do you know what is the numpy and JEP versions in you colleague's environment?

Python 3.12.3
Jep 4.2.2 / 4.2.0 / 4.0.3
dlib 20.0.0

I reproduced the error it with numpy 1.26.4. No easy solution was found.
I seems that there is some optimization in JEP that prefers to use primitive arrays instead of NDArray.
The related code is in https://github.com/ninia/jep/blob/v4.0.3/src/main/c/Jep/jep_numpy.c

**Comment by aberenguel** [comment]
@lfcnassif , the commit above fixed this issue (tested in Linux). Could you check if it is reasonable?

I chose to use the more descriptive `KnnVector` class for cases where we want to index a `double[]` as a `KnnVectorField`. This makes the intention clearer and avoids potential conflicts with the `NDArray` logic.

**Comment by aberenguel** [comment]
I believe I’ve identified the root cause of the `ClassNotFoundException: double[]`. It depends on whether `numpy` is installed at the time `jep` is installed and compiled.

To demonstrate this, I ran the following simple test:

```java
public static void main(String[] args) {
    PyConfig pyConfig = new PyConfig();
    MainInterpreter.setInitParams(pyConfig);
    try (Jep jep = new SharedInterpreter()) {
        jep.eval("import numpy as np");
        jep.eval("myArray = np.array([10.5, 20.3, 30.8, 40.1, 55.9])");
        Object myArray = jep.getValue("myArray");
        System.out.println("myArray: " + myArray.getClass() + " -> " + myArray);
    }
}
```

If `jep` is installed in a Python environment where `numpy` **is not yet installed**, the output is:
```
myArray: class [D -> [D@573fd745
```

If `numpy` is installed **before** compiling/installing `jep`, the result is:
```
myArray: class jep.NDArray -> jep.NDArray@1f6e4ec7
```

The solution to ensure `jep` correctly uses `NDArray` is to make sure `numpy` is installed before (re)installing `jep`:
```sh
# optionally loads the Python virtual environment
source ~/.venv/IPED/bin/activate

# Reinstall jep to force rebuild with numpy support
pip install --force-reinstall numpy==1.26.4
pip install --force-reinstall --no-cache-dir jep==4.0.3
```

**Comment by lfcnassif** [comment]
> [@lfcnassif](https://github.com/lfcnassif) , the commit above fixed this issue (tested in Linux). Could you check if it is reasonable?
> 
> I chose to use the more descriptive `KnnVector` class for cases where we want to index a `double[]` as a `KnnVectorField`. This makes the intention clearer and avoids potential conflicts with the `NDArray` logic.

Thank you, @aberenguel, this approach seems very good to me! My only concern is that I think it should be compatible with multicases including cases with previous versions, have you tested it?

**Comment by aberenguel** [comment]
Tested in both directions:
* **[unchanged case] => (changed + unchanged)** - did **not** work (ClassNotFoundException: iped.engine.task.index.IndexItem$KnnVector)
* **[changed case] => (changed + unchanged)** - worked 

The value `face_encodings = jep.NDArray` or `face_encodings = iped.engine.task.index.IndexItem$KnnVector` in `metadataTypes.txt` are actually not used and can be safely removed. It is just parsed to Class when IPED App starts. The extraProperty of `face_encodings` has a special handling in `IndexItem.java`.

When `face_encodings` is removed from `metadataTypes.txt` there is no side effect and:
* **[unchanged case] => (changed + unchanged)** - worked

**Comment by aberenguel** [comment]
I'm thinking about to avoid to write the value of `face_encodings` in `metadataTypes.txt`

**Comment by lfcnassif** [comment]
> Tested in both directions:
> 
> * **[unchanged case] => (changed + unchanged)** - did **not** work (ClassNotFoundException: iped.engine.task.index.IndexItem$KnnVector)
> * **[changed case] => (changed + unchanged)** - worked
> 
> The value `face_encodings = jep.NDArray` or `face_encodings = iped.engine.task.index.IndexItem$KnnVector` in `metadataTypes.txt` are actually not used and can be safely removed. It is just parsed to Class when IPED App starts. The extraProperty of `face_encodings` has a special handling in `IndexItem.java`.
> 
> When `face_encodings` is removed from `metadataTypes.txt` there is no side effect and:
> 
> * **[unchanged case] => (changed + unchanged)** - worked

Great! Thanks @aberenguel for testing and handling it!

**Comment by aberenguel** [comment]
Fixed by #2567
