### ISSUE TITLE
TelegramParser : "no such table: users" 

### ISSUE THREAD

**Issue by aberenguel** [sepinf-inc/IPED#2295]
Using master branch processing an UFDR file generated by PA 10.3:

```
org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such table: users)
	at org.sqlite.core.DB.newSQLException(DB.java:1012)
	at org.sqlite.core.DB.newSQLException(DB.java:1024)
	at org.sqlite.core.DB.throwex(DB.java:989)
	at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
	at org.sqlite.core.NativeDB.prepare(NativeDB.java:134)
	at org.sqlite.core.DB.prepare(DB.java:257)
	at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:45)
	at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:30)
	at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:25)
	at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:35)
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:241)
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:205)
	at iped.parsers.util.DelegatingConnection.prepareStatement(DelegatingConnection.java:196)
	at iped.parsers.telegram.Extractor.extractContacts(Extractor.java:471)
	at iped.parsers.telegram.TelegramParser.parseTelegramDBAndroid(TelegramParser.java:138)
	at iped.parsers.telegram.TelegramParser.parse(TelegramParser.java:480)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:298)
	at iped.parsers.standard.StandardParser.parse(StandardParser.java:245)
	at iped.engine.io.ParsingReader$BackgroundParsing.run(ParsingReader.java:247)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by aberenguel** [comment]
Just checked. The "cache4.db" file has no table.
In such case the file has 4096 bytes. When I created a simple table, the file increased to 8192 bytes.
The file size could be checked before start the parsing.

**Comment by kevinobruno** [comment]
I've opened a PR for this: #2990.

As @aberenguel found, the `cache4.db` in this case is a 4096-byte SQLite file with no tables. It still reaches `TelegramParser` because of the filename match, and `extractContacts()` then fails on the missing `users` table.

Instead of checking the file size, each Android extraction step in `Extractor` now checks that the tables it needs exist, and is skipped with a warning in the log when they don't. The empty DB from this issue produces no items and no error. A DB that has only some of the tables still yields what it can. For example, messages are recovered even when `users` is missing.

One behavior change to be aware of: a DB missing some of these tables no longer marks the item with a parsing error. It only logs a warning.
