### ISSUE TITLE
IPED stopped - iped.exception.IPEDException: Processing canceled!

### ISSUE THREAD

**Issue by igiuseppem** [sepinf-inc/IPED#2332]
Good morning.

I have performed the parsing of a forensic copy with IPED 4.1.6. Yesterday I let it at about 50% of processing, but this morning I found the workstation at  login screen. I checked the log and I found lot of exception and the final message "iped.exception.IPEDException: Processing canceled!"
Following a piece of the last errors and the final message I found in the log:
```
2024-10-09 01:16:30	[WARN]	[parsers.misc.MultipleParser]			Exception from org.apache.tika.parser.image.JpegParser on /hd_copy.E01/vol_vol4/$Unalloc/Unalloc_39088_400717684736_422352375808-Frag19>>Carved-544783773.jpg: java.io.EOFException: End of data reached.
2024-10-09 01:16:30	[WARN]	[parsers.standard.StandardParser]			ParsingThread-717 Parsing exception: /hd_copy.E01/vol_vol4/$Unalloc/Unalloc_39088_400717684736_422352375808-Frag19>>Carved-544783773.jpg (1707 bytes)		org.apache.tika.exception.TikaException: Exception from org.apache.tika.parser.image.JpegParser
2024-10-09 01:16:32	[WARN]	[parsers.misc.MultipleParser]			Exception from org.apache.tika.parser.image.JpegParser on /hd_copy.E01/vol_vol4/$Unalloc/Unalloc_39088_400717684736_422352375808-Frag19>>Carved-750257119.jpg: java.io.EOFException: End of data reached.
2024-10-09 01:16:32	[WARN]	[parsers.standard.StandardParser]			ParsingThread-717 Parsing exception: /hd_copy.E01/vol_vol4/$Unalloc/Unalloc_39088_400717684736_422352375808-Frag19>>Carved-750257119.jpg (12192 bytes)		org.apache.tika.exception.TikaException: Exception from org.apache.tika.parser.image.JpegParser
2024-10-09 01:16:32	[WARN]	[parsers.misc.MultipleParser]			Exception from org.apache.tika.parser.image.JpegParser on /hd_copy.E01/vol_vol4/$Unalloc/Unalloc_39088_400717684736_422352375808-Frag19>>Carved-787535217.jpg: java.io.EOFException: End of data reached.
2024-10-09 01:16:32	[WARN]	[parsers.standard.StandardParser]			ParsingThread-717 Parsing exception: /hd_copy.E01/vol_vol4/$Unalloc/Unalloc_39088_400717684736_422352375808-Frag19>>Carved-787535217.jpg (233600 bytes)		org.apache.tika.exception.TikaException: Exception from org.apache.tika.parser.image.JpegParser
2024-10-09 01:27:18	[WARN]	[parsers.misc.MultipleParser]			Exception from org.apache.tika.parser.image.JpegParser on /hd_copy.E01/vol_vol4/$Unalloc/Unalloc_39088_422355521536_433660071936-Frag0>>Carved-137470864.jpg: java.io.EOFException: End of data reached.
2024-10-09 01:27:18	[WARN]	[parsers.standard.StandardParser]			ParsingThread-735 Parsing exception: /hd_copy.E01/vol_vol4/$Unalloc/Unalloc_39088_422355521536_433660071936-Frag0>>Carved-137470864.jpg (58590 bytes)		org.apache.tika.exception.TikaException: Exception from org.apache.tika.parser.image.JpegParser
2024-10-09 01:27:20	[WARN]	[parsers.misc.MultipleParser]			Exception from org.apache.tika.parser.image.JpegParser on /hd_copy.E01/vol_vol4/$Unalloc/Unalloc_39088_422355521536_433660071936-Frag0>>Carved-304368211.jpg: java.io.EOFException: End of data reached.
2024-10-09 01:27:20	[WARN]	[parsers.standard.StandardParser]			ParsingThread-734 Parsing exception: /hd_copy.E01/vol_vol4/$Unalloc/Unalloc_39088_422355521536_433660071936-Frag0>>Carved-304368211.jpg (55890 bytes)		org.apache.tika.exception.TikaException: Exception from org.apache.tika.parser.image.JpegParser
2024-10-09 01:27:50	[WARN]	[parsers.misc.MultipleParser]			Exception from org.apache.tika.parser.image.JpegParser on /hd_copy.E01/vol_vol4/$Unalloc/Unalloc_39088_422355521536_433660071936-Frag0>>Carved-530915652.jpg: java.io.EOFException: End of data reached.
2024-10-09 01:27:50	[WARN]	[parsers.standard.StandardParser]			ParsingThread-735 Parsing exception: /hd_copy.E01/vol_vol4/$Unalloc/Unalloc_39088_422355521536_433660071936-Frag0>>Carved-530915652.jpg (92989 bytes)		org.apache.tika.exception.TikaException: Exception from org.apache.tika.parser.image.JpegParser
iped.exception.IPEDException: Processing canceled!
	at iped.engine.core.Manager.monitorProcessing(Manager.java:567)
	at iped.engine.core.Manager.process(Manager.java:279)
	at iped.app.processing.Main.startManager(Main.java:178)
	at iped.app.processing.Main.execute(Main.java:240)
	at iped.app.processing.Main.main(Main.java:308)
```

Thank you

**Comment by wladimirleite** [comment]
Usually "processing canceled" just means that IPED application was closed.
Are you using Windows or Linux?
If it is Windows, is it possible that an automatic restart happened (because of an update)? Windows tries to close running applications before restarting.
