### ISSUE TITLE
Erro processamento

### ISSUE THREAD

**Issue by fcscoutinho** [sepinf-inc/IPED#278]
Estou com um problema e não consigo indexar a versão...

2020-10-08 15:52:05	[INFO]	[indexer.desktop.AppMain]			Indexador e Processador de Evidências Digitais 3.18.2
2020-10-08 15:52:06	[INFO]	[indexer.util.CustomLoader]			Adding to classpath: C:\Users\xxx\.indexador\libreoffice6\program\classes\ridl.jar
2020-10-08 15:52:06	[INFO]	[indexer.util.CustomLoader]			Adding to classpath: C:\Users\xxx\.indexador\libreoffice6\program\classes\jurt.jar
2020-10-08 15:52:06	[INFO]	[indexer.util.CustomLoader]			Adding to classpath: C:\Users\xxx\.indexador\libreoffice6\program\classes\juh.jar
2020-10-08 15:52:06	[INFO]	[indexer.util.CustomLoader]			Adding to classpath: C:\Users\xxx\.indexador\libreoffice6\program\classes\unoil.jar
2020-10-08 15:52:06	[INFO]	[indexer.util.CustomLoader]			Adding to classpath: C:\Users\xxx\.indexador\libreoffice6\program
2020-10-08 15:52:06	[INFO]	[indexer.util.CustomLoader]			Adding to classpath: C:\Users\xxx\.indexador\libreoffice6\program\classes\officebean.jar
2020-10-08 15:52:06	[INFO]	[gpinf.indexer.Configuration]			Loading configuration from D:\IPED\INDEX\13652\indexador
2020-10-08 15:52:07	[INFO]	[indexer.desktop.App]			Starting...
2020-10-08 15:52:08	[WARN]	[tika.config.InitializableProblemHandler$3]			J2KImageReader not loaded. JPEG2000 files will not be processed.
See https://pdfbox.apache.org/2.0/dependencies.html#jai-image-io
for optional dependencies.

2020-10-08 15:52:09	[INFO]	[browsers.parsers.EdgeWebCacheParser]			Libesedb library version: 20181229
2020-10-08 15:52:09	[INFO]	[indexer.parsers.OCRParser]			Detected Tesseract 4.0.0
2020-10-08 15:52:09	[WARN]	[indexer.parsers.PDFOCRTextParser]			Plugin JPEG2000 not found, JPX images will not be decoded from PDFs. You can download it from https://mvnrepository.com/artifact/com.github.jai-imageio/jai-imageio-jpeg2000/1.3.0 and put it in optional_jar folder.
2020-10-08 15:52:10	[INFO]	[indexer.desktop.App$1]			GUI created
2020-10-08 15:52:10	[INFO]	[indexer.search.IPEDSource]			Opening index D:\IPED\INDEX\13652\indexador\index
2020-10-08 15:52:10	[INFO]	[indexer.util.ConfiguredFSDirectory]			Using MMapDirectory to open index...
java.lang.RuntimeException: no segments* file found in MMapDirectory@D:\IPED\INDEX\13652\indexador\index lockFactory=org.apache.lucene.store.NativeFSLockFactory@72128ace: files: [_0.cfe, _0.cfs, _0.si, _1.cfe, _1.cfs, _1.si, _2.cfe, _2.cfs, _2.si, _3.cfe, _3.cfs, _3.si, _4.cfe, _4.cfs, _4.si, _5.cfe, _5.cfs, _5.si, _6.cfe, _6.cfs, _6.si, write.lock]
	at dpf.sp.gpinf.indexer.search.IPEDSource.<init>(IPEDSource.java:239)
	at dpf.sp.gpinf.indexer.search.IPEDSource.<init>(IPEDSource.java:142)
	at dpf.sp.gpinf.indexer.desktop.InicializarBusca.doInBackground(InicializarBusca.java:83)
	at dpf.sp.gpinf.indexer.desktop.InicializarBusca.doInBackground(InicializarBusca.java:40)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.apache.lucene.index.IndexNotFoundException: no segments* file found in MMapDirectory@D:\IPED\INDEX\13652\indexador\index lockFactory=org.apache.lucene.store.NativeFSLockFactory@72128ace: files: [_0.cfe, _0.cfs, _0.si, _1.cfe, _1.cfs, _1.si, _2.cfe, _2.cfs, _2.si, _3.cfe, _3.cfs, _3.si, _4.cfe, _4.cfs, _4.si, _5.cfe, _5.cfs, _5.si, _6.cfe, _6.cfs, _6.si, write.lock]
	at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:687)
	at org.apache.lucene.index.StandardDirectoryReader.open(StandardDirectoryReader.java:77)
	at org.apache.lucene.index.DirectoryReader.open(DirectoryReader.java:63)
	at dpf.sp.gpinf.indexer.search.IPEDSource.openIndex(IPEDSource.java:339)
	at dpf.sp.gpinf.indexer.search.IPEDSource.<init>(IPEDSource.java:197)
	... 9 more
2020-10-08 15:52:10	[INFO]	[application.connection.LocalOfficeConnection]			Opening local OpenOffice.org connection.
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at dpf.sp.gpinf.indexer.desktop.CategoryTreeModel.getLeafCategories(CategoryTreeModel.java:262)
	at dpf.sp.gpinf.indexer.desktop.CategoryTreeModel.loadHierarchy(CategoryTreeModel.java:183)
	at dpf.sp.gpinf.indexer.desktop.CategoryTreeModel.<init>(CategoryTreeModel.java:50)
	at dpf.sp.gpinf.indexer.desktop.CategoryTreeModel.install(CategoryTreeModel.java:40)
	at dpf.sp.gpinf.indexer.desktop.InicializarBusca.done(InicializarBusca.java:149)
	at javax.swing.SwingWorker$5.run(Unknown Source)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(Unknown Source)
	at sun.swing.AccumulativeRunnable.run(Unknown Source)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(Unknown Source)
	at javax.swing.Timer.fireActionPerformed(Unknown Source)
	at javax.swing.Timer$DoPostEvent.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.WaitDispatchSupport$2.run(Unknown Source)
	at java.awt.WaitDispatchSupport$4.run(Unknown Source)
	at java.awt.WaitDispatchSupport$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(Unknown Source)
	at java.awt.Dialog.show(Unknown Source)
	at javax.swing.JOptionPane.showOptionDialog(Unknown Source)
	at javax.swing.JOptionPane.showMessageDialog(Unknown Source)
	at javax.swing.JOptionPane.showMessageDialog(Unknown Source)
	at dpf.sp.gpinf.indexer.desktop.InicializarBusca$1.run(InicializarBusca.java:137)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
2020-10-08 15:52:11	[INFO]	[fileViewer.frames.LibreOfficeViewer]			LibreOffice running.
2020-10-08 15:52:11	[INFO]	[fileViewer.frames.LibreOfficeViewer$1]			Constructing LibreOffice frame...
2020-10-08 15:52:12	[INFO]	[fileViewer.frames.LibreOfficeViewer$1]			LibreOffice frame ok
Killed pid 15792 exitValue: 0
java.lang.NullPointerException
	at dpf.sp.gpinf.indexer.desktop.ColumnsManager.updateDinamicFields(ColumnsManager.java:558)
	at dpf.sp.gpinf.indexer.desktop.ColumnsManager.<init>(ColumnsManager.java:277)
	at dpf.sp.gpinf.indexer.desktop.ColumnsManager.getInstance(ColumnsManager.java:134)
	at dpf.sp.gpinf.indexer.desktop.App.destroy(App.java:347)
	at dpf.sp.gpinf.indexer.desktop.App.windowClosing(App.java:1287)
	at java.awt.AWTEventMulticaster.windowClosing(Unknown Source)
	at java.awt.AWTEventMulticaster.windowClosing(Unknown Source)
	at java.awt.AWTEventMulticaster.windowClosing(Unknown Source)
	at java.awt.AWTEventMulticaster.windowClosing(Unknown Source)
	at java.awt.AWTEventMulticaster.windowClosing(Unknown Source)
	at java.awt.Window.processWindowEvent(Unknown Source)
	at javax.swing.JFrame.processWindowEvent(Unknown Source)
	at java.awt.Window.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by lfcnassif** [comment]
Seems your case processing did not finish fine, your index is empty. Please send the full processing log.

**Comment by lfcnassif** [comment]
Closing, needed info not sent. If you could attach the full original processing log, please reopen.
