### ISSUE TITLE
Error parsing files with enableExternalParsing = true after upgrading to SevenZipJBinding-16.02-2.01

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#301]
That was introduced in #282. External parsers are not initializing correctly because new 7zipJBinding tries to overwrite already existing dll:
'''
java.lang.ExceptionInInitializerError
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at org.apache.tika.config.ServiceLoader.getServiceClass(ServiceLoader.java:235)
	at org.apache.tika.config.TikaConfig$XmlLoader.loadOne(TikaConfig.java:611)
	at org.apache.tika.config.TikaConfig$XmlLoader.loadOverall(TikaConfig.java:572)
	at org.apache.tika.config.TikaConfig.<init>(TikaConfig.java:268)
	at org.apache.tika.config.TikaConfig.getDefaultConfig(TikaConfig.java:405)
	at org.apache.tika.fork.ExternalParsingParserFactory.build(ExternalParsingParserFactory.java:34)
	at org.apache.tika.fork.ForkServer2.initializeParserAndLoader(ForkServer2.java:216)
	at org.apache.tika.fork.ForkServer2.processRequests(ForkServer2.java:163)
	at org.apache.tika.fork.ForkServer2.main(ForkServer2.java:94)
Caused by: java.lang.RuntimeException: Error initializing SevenZipJBinding native library: can't copy native library out of a resource file to the temporary location: 'C:\Users\Nassif\AppData\Local\Temp\indexador-temp1603468248395\SevenZipJBinding-0EsPGE1ZKaCb\lib7-Zip-JBinding.dll'
	at net.sf.sevenzipjbinding.SevenZip.copyLibraryToFS(SevenZip.java:844)
	at net.sf.sevenzipjbinding.SevenZip.copyOrSkipLibraries(SevenZip.java:566)
	at net.sf.sevenzipjbinding.SevenZip.initSevenZipFromPlatformJARIntern(SevenZip.java:455)
	at net.sf.sevenzipjbinding.SevenZip.initSevenZipFromPlatformJAR(SevenZip.java:340)
	at dpf.sp.gpinf.indexer.parsers.SevenZipParser.getTypes(SevenZipParser.java:70)
	at dpf.sp.gpinf.indexer.parsers.SevenZipParser.<clinit>(SevenZipParser.java:59)
	... 11 more
Caused by: java.io.FileNotFoundException: C:\Users\Nassif\AppData\Local\Temp\indexador-temp1603468248395\SevenZipJBinding-0EsPGE1ZKaCb\lib7-Zip-JBinding.dll (The process cannot access the file because it is being used by another process)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at net.sf.sevenzipjbinding.SevenZip.copyLibraryToFS(SevenZip.java:833)
	... 16 more
java.io.IOException: Server had a catastrophic initialization failure
	at org.apache.tika.fork.ForkClient2.waitForStartBeacon(ForkClient2.java:224)
	at org.apache.tika.fork.ForkClient2.<init>(ForkClient2.java:147)
	at org.apache.tika.fork.ForkClient2.<init>(ForkClient2.java:82)
	at org.apache.tika.fork.ForkParser2.newClient(ForkParser2.java:456)
	at org.apache.tika.fork.ForkParser2.acquireClient(ForkParser2.java:421)
	at org.apache.tika.fork.ForkParser2.parse(ForkParser2.java:354)
	at dpf.sp.gpinf.indexer.parsers.IndexerDefaultParser.parse(IndexerDefaultParser.java:230)
	at dpf.sp.gpinf.indexer.io.ParsingReader$BackgroundParsing.run(ParsingReader.java:251)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
'''

This just affects master and 3.18.x branches. No released versions are affected.

**Comment by lfcnassif** [comment]
Not the ideal solution, because external parsers are often restarted and that creates more and more 7zip.dll in temp folder.

Maybe the fix can be improved after feedback from @borisbrodski: https://github.com/borisbrodski/sevenzipjbinding/issues/31

**Comment by borisbrodski** [comment]
Hey folks,

thank you for using 7-Zip-JBinding! Sorry, it makes troubles.

I will look into the issue next monday. It will work.

**Comment by lfcnassif** [comment]
Thanks @borisbrodski! But it is not urgent, the workaround fixed the critical issue, thank you for your great library.
