### ISSUE TITLE
Warn user instead of aborting if antivirus has blocked or deleted extracted text temp file

### ISSUE THREAD

**Issue by gis-msouza** [sepinf-inc/IPED#311]
Hi, 

I have a problem in a processing (carving, ocr activated). The first occurrence I imagine led the process to abort was this:

2020-11-10 23:45:21	[WARN]	[process.task.HashTask]			Worker-2 Error computing hash /15265CI012.E01/vol_vol6//$Unalloc/Unalloc_1734455_67742453760_78642642944-Frag0>>Unalloc_1734455_67742453760_78642642944-Frag0_0	java.nio.channels.ClosedChannelException
2020-11-10 23:45:21	[WARN]	[process.task.IndexTask]			Null Text reader, creating a new one for /15265CI012.E01/vol_vol6//$Unalloc/Unalloc_1734455_67742453760_78642642944-Frag0
2020-11-10 23:45:21	[INFO]	[indexer.process.Worker]			Worker-2 interrupted on /15265CI012.E01/vol_vol6//$Unalloc/Unalloc_1734455_67742453760_78642642944-Frag0 (1073741824 bytes)
2020-11-10 23:45:21	[WARN]	[process.task.VideoThumbTask]			Item: /15265CI012.E01/vol_vol6//$Unalloc/Unalloc_1734455_104769323008_132606312448-Frag9>>Carved-265688709.mp4 type: mp4 size: 405173
java.lang.IllegalStateException: Shutdown in progress
	at java.io.DeleteOnExitHook.add(Unknown Source) ~[?:1.8.0_261]
	at java.io.File.deleteOnExit(Unknown Source) ~[?:1.8.0_261]
	at gpinf.video.VideoThumbsMaker.createThumbs(VideoThumbsMaker.java:92) ~[iped-engine-3.18.3.jar:?]
	at dpf.sp.gpinf.indexer.process.task.VideoThumbTask.process(VideoThumbTask.java:395) [iped-engine-3.18.3.jar:?]

But I am not shure.
Need some help to understant.

Thanks

**Comment by lfcnassif** [comment]
It doesn't seems to be the cause, could you send the full processing log? If it has sensible data, you could send it privately to me (email in my profile)

**Comment by gis-msouza** [comment]
Ok.

**Comment by lfcnassif** [comment]
```
Caused by: java.nio.file.NoSuchFileException: C:\iped\indexTemp\indexador-temp1605044864866\text2653276737585425532.tmp
	at sun.nio.fs.WindowsException.translateToIOException(Unknown Source) ~[?:1.8.0_261]
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source) ~[?:1.8.0_261]
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source) ~[?:1.8.0_261]
	at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(Unknown Source) ~[?:1.8.0_261]
	at java.nio.file.Files.newByteChannel(Unknown Source) ~[?:1.8.0_261]
	at java.nio.file.Files.newByteChannel(Unknown Source) ~[?:1.8.0_261]
	at java.nio.file.spi.FileSystemProvider.newInputStream(Unknown Source) ~[?:1.8.0_261]
	at java.nio.file.Files.newInputStream(Unknown Source) ~[?:1.8.0_261]
	at java.nio.file.Files.newBufferedReader(Unknown Source) ~[?:1.8.0_261]
	at java.nio.file.Files.newBufferedReader(Unknown Source) ~[?:1.8.0_261]
	at dpf.sp.gpinf.indexer.util.TextCache.getTextReader(TextCache.java:74) ~[iped-engine-3.18.3.jar:?]
	at gpinf.dev.data.Item.getTextReader(Item.java:574) ~[iped-engine-3.18.3.jar:?]
	at dpf.sp.gpinf.indexer.process.task.regex.RegexTask.process(RegexTask.java:217) ~[iped-engine-3.18.3.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processMonitorTimeout(AbstractTask.java:221) ~[iped-engine-3.18.3.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:159) ~[iped-engine-3.18.3.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:201) ~[iped-engine-3.18.3.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:167) ~[iped-engine-3.18.3.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:201) ~[iped-engine-3.18.3.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:167) ~[iped-engine-3.18.3.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:201) ~[iped-engine-3.18.3.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:167) ~[iped-engine-3.18.3.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:201) ~[iped-engine-3.18.3.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:167) ~[iped-engine-3.18.3.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:201) ~[iped-engine-3.18.3.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:167) ~[iped-engine-3.18.3.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:201) ~[iped-engine-3.18.3.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:167) ~[iped-engine-3.18.3.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:201) ~[iped-engine-3.18.3.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:167) ~[iped-engine-3.18.3.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:201) ~[iped-engine-3.18.3.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:167) ~[iped-engine-3.18.3.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:201) ~[iped-engine-3.18.3.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:167) ~[iped-engine-3.18.3.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:201) ~[iped-engine-3.18.3.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:167) ~[iped-engine-3.18.3.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:201) ~[iped-engine-3.18.3.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:167) ~[iped-engine-3.18.3.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:201) ~[iped-engine-3.18.3.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:167) ~[iped-engine-3.18.3.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:201) ~[iped-engine-3.18.3.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:167) ~[iped-engine-3.18.3.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:201) ~[iped-engine-3.18.3.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:167) ~[iped-engine-3.18.3.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:201) ~[iped-engine-3.18.3.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:167) ~[iped-engine-3.18.3.jar:?]
	at dpf.sp.gpinf.indexer.process.Worker.process(Worker.java:172) ~[iped-engine-3.18.3.jar:?]
	... 67 more
```
I colleague of mine recently had such problem and it probably was caused by antivirus software deleting temporary files used by Iped. This file just contains extracted text to be indexed and is not virus for sure. Please check in your antivirus log if it deleted or blocked access to that file and try to exclude the indexTemp folder from antivirus scanning before processing.

**Comment by gis-msouza** [comment]
Yes, it was a native hp tool in the workstation, "hp sure sense". It was quarantining the .tmp files.

Thank u a lot.

**Comment by lfcnassif** [comment]
You're welcome, thanks for checking it.

**Comment by lfcnassif** [comment]
Will print an error message to user instead of aborting processing. Obviously the affected file will not be processed fine.
