### ISSUE TITLE
Please release new version.

### ISSUE THREAD

**Issue by MariasStory** [sepinf-inc/IPED#317]
Hi,
Please release a new version.

At the moment I cannot go arround the error:
"Caused by: java.lang.ClassCastException: java.lang.String cannot be cast"

This, if I am right, should have been fixed in the issue:
https://github.com/sepinf-inc/IPED/issues/304

**Comment by lfcnassif** [comment]
Hi @MariasStory,

Could you post at least the full stacktrace, so we can be sure it is the same issue?

If it is the same, you can try this snapshot version, to check if it was really fixed or not: https://github.com/sepinf-inc/IPED/actions/runs/358604009

That also contains other fixes.

I am planning to release a new version next week, after some tests are done.

**Comment by MariasStory** [comment]
Something like this:

```
[ERROR] [gpinf.indexer.IndexFiles]                      Processing Error:
java.io.FileNotFoundException: ...\indexador\conf\TaskInstaller.xml (The system cannot find the path specified)
        at java.io.FileInputStream.open0(Native Method) ~[?:1.8.0_152]
        at java.io.FileInputStream.open(Unknown Source) ~[?:1.8.0_152]
        at java.io.FileInputStream.<init>(Unknown Source) ~[?:1.8.0_152]
        at java.io.FileInputStream.<init>(Unknown Source) ~[?:1.8.0_152]
        at sun.net.www.protocol.file.FileURLConnection.connect(Unknown Source) ~[?:1.8.0_152]
        at sun.net.www.protocol.file.FileURLConnection.getInputStream(Unknown Source) ~[?:1.8.0_152]
        at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(Unknown Source) ~[?:1.8.0_152]
        at com.sun.org.apache.xerces.internal.impl.XMLVersionDetector.determineDocVersion(Unknown Source) ~[?:1.8.0_152]
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source) ~[?:1.8.0_152]
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source) ~[?:1.8.0_152]
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source) ~[?:1.8.0_152]
        at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(Unknown Source) ~[?:1.8.0_152]
        at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(Unknown Source) ~[?:1.8.0_152]
        at javax.xml.parsers.DocumentBuilder.parse(Unknown Source) ~[?:1.8.0_152]
        at dpf.sp.gpinf.indexer.process.task.TaskInstaller.loadTasks(TaskInstaller.java:51) ~[iped-engine-3.18.3.jar:?]
        at dpf.sp.gpinf.indexer.process.task.TaskInstaller.installProcessingTasks(TaskInstaller.java:40) ~[iped-engine-3.18.3.jar:?]
        at dpf.sp.gpinf.indexer.process.Worker.<init>(Worker.java:93) ~[iped-engine-3.18.3.jar:?]
        at dpf.sp.gpinf.indexer.process.Manager.iniciarIndexacao(Manager.java:352) ~[iped-engine-3.18.3.jar:?]
        at dpf.sp.gpinf.indexer.process.Manager.process(Manager.java:205) ~[iped-engine-3.18.3.jar:?]
        at dpf.sp.gpinf.indexer.IndexFiles.doInBackground(IndexFiles.java:216) [iped.jar:?]
        at dpf.sp.gpinf.indexer.IndexFiles.doInBackground(IndexFiles.java:59) [iped.jar:?]
        at javax.swing.SwingWorker$1.call(Unknown Source) [?:1.8.0_152]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_152]
        at javax.swing.SwingWorker.run(Unknown Source) [?:1.8.0_152]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_152]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_152]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_152]

ERROR!!!
```

**Comment by lfcnassif** [comment]
Thanks, that seems the same. Could you try the linked snapshot above?

**Comment by MariasStory** [comment]
Running the test.
Thanks for fast answer ;-)

**Comment by lfcnassif** [comment]
Thanks for the feedback.
