### ISSUE TITLE
Aborting NullPointerException in NamedEntityTask

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#329]
Seems a null key is being stored (and accessed) in item metadata. Investigated a bit some days ago and did not find when the null key was stored and couldn't remove it from metadata...

```
Caused by: java.lang.NullPointerException
	at org.apache.tika.sax.XHTMLContentHandler.lazyEndHead(XHTMLContentHandler.java:173) ~[tika-core-1.20.jar:1.20]
	at org.apache.tika.sax.XHTMLContentHandler.startElement(XHTMLContentHandler.java:253) ~[tika-core-1.20.jar:1.20]
	at org.apache.tika.sax.XHTMLContentHandler.startElement(XHTMLContentHandler.java:290) ~[tika-core-1.20.jar:1.20]
	at org.apache.tika.parser.ner.NamedEntityParser.extractOutput(NamedEntityParser.java:170) ~[tika-parsers-1.20.jar:1.20]
	at org.apache.tika.parser.ner.NamedEntityParser.parse(NamedEntityParser.java:153) ~[tika-parsers-1.20.jar:1.20]
	at dpf.sp.gpinf.indexer.process.task.NamedEntityTask.process(NamedEntityTask.java:188) ~[iped-engine-3.18.4.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processMonitorTimeout(AbstractTask.java:221) ~[iped-engine-3.18.4.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:159) ~[iped-engine-3.18.4.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:201) ~[iped-engine-3.18.4.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:167) ~[iped-engine-3.18.4.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:201) ~[iped-engine-3.18.4.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:167) ~[iped-engine-3.18.4.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:201) ~[iped-engine-3.18.4.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:167) ~[iped-engine-3.18.4.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:201) ~[iped-engine-3.18.4.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:167) ~[iped-engine-3.18.4.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:201) ~[iped-engine-3.18.4.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:167) ~[iped-engine-3.18.4.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:201) ~[iped-engine-3.18.4.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:167) ~[iped-engine-3.18.4.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:201) ~[iped-engine-3.18.4.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:167) ~[iped-engine-3.18.4.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:201) ~[iped-engine-3.18.4.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:167) ~[iped-engine-3.18.4.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:201) ~[iped-engine-3.18.4.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:167) ~[iped-engine-3.18.4.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:201) ~[iped-engine-3.18.4.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:167) ~[iped-engine-3.18.4.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:201) ~[iped-engine-3.18.4.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:167) ~[iped-engine-3.18.4.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:201) ~[iped-engine-3.18.4.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:167) ~[iped-engine-3.18.4.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:201) ~[iped-engine-3.18.4.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:167) ~[iped-engine-3.18.4.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:201) ~[iped-engine-3.18.4.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:167) ~[iped-engine-3.18.4.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:201) ~[iped-engine-3.18.4.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:167) ~[iped-engine-3.18.4.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:201) ~[iped-engine-3.18.4.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:167) ~[iped-engine-3.18.4.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:201) ~[iped-engine-3.18.4.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:167) ~[iped-engine-3.18.4.jar:?]
	at dpf.sp.gpinf.indexer.process.Worker.process(Worker.java:172) ~[iped-engine-3.18.4.jar:?]
	... 1 more
```

**Comment by lfcnassif** [comment]
I was not able to reproduce, and was able to remove a null key in a test, not sure what happened. Added some protection I wish will fix this.
