### ISSUE TITLE
Export huge indexed case, stop without further message and incomplet

### ISSUE THREAD

**Issue by gaffinet** [sepinf-inc/IPED#345]
Hi

I have an issue with a quiet huge multicases project.
There are about 30 evidences, all in seperet iped cases folder and 16M  of objects
I open all the cases with -multicases (I used one of the IPED-SearchApp.exe -multicases ..\)
After this, I bookmark about 500'000 files.
When I try to create the corresponding indexed Report, iped opens just fine and begin the export.
After about 100'000 of exported files, iped closes without any further messages.

Where do I find the log file which might explains the crash?

thanks for your help

**Comment by lfcnassif** [comment]
Hi,
Look at indexador/log folder of the case which IPED-SearchApp.exe was used and attach it here please.

**Comment by gaffinet** [comment]
It is a java.lang.OutOfMemoryError: Java heap space Exception:

```
java.lang.Exception: Worker-6 Error while processing ****.MP4 (285117081bytes)
	at dpf.sp.gpinf.indexer.process.Worker.process(Worker.java:181) ~[iped-engine-3.18.4.jar:?]
	at dpf.sp.gpinf.indexer.process.Worker.run(Worker.java:233) ~[iped-engine-3.18.4.jar:?]
Caused by: java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Unknown Source) ~[?:1.8.0_152]
	at java.io.ByteArrayOutputStream.grow(Unknown Source) ~[?:1.8.0_152]
	at java.io.ByteArrayOutputStream.ensureCapacity(Unknown Source) ~[?:1.8.0_152]
	at java.io.ByteArrayOutputStream.write(Unknown Source) ~[?:1.8.0_152]
	at dpf.sp.gpinf.indexer.process.task.ExportFileTask.extractFile(ExportFileTask.java:457) ~[iped-engine-3.18.4.jar:?]
```
and
```
java.lang.Exception: Worker-1 Error while processing /03_hdd_ext_v2.dd/vol_vol2/New Folder/Oesterreich/~ps6E.tmp (50241024bytes)
	at dpf.sp.gpinf.indexer.process.Worker.process(Worker.java:181) ~[iped-engine-3.18.4.jar:?]
	at dpf.sp.gpinf.indexer.process.Worker.run(Worker.java:233) ~[iped-engine-3.18.4.jar:?]
Caused by: java.lang.OutOfMemoryError: Java heap space
```

I use a VM with 32G of RAM

In another log file I found:
```
2021-01-25 15:05:49	[INFO]	[indexer.process.Statistics]			CPU Cores: 8
2021-01-25 15:05:49	[INFO]	[indexer.process.Statistics]			numThreads: 8
2021-01-25 15:05:49	[INFO]	[indexer.process.Statistics]			Memory (Heap) Available: 7456 MB
```

I restarted the VM with 64G of RAM

Now, in the log file, the heap doubles

```
2021-01-25 16:39:54	[INFO]	[indexer.process.Statistics]			CPU Cores: 8
2021-01-25 16:39:54	[INFO]	[indexer.process.Statistics]			numThreads: 8
2021-01-25 16:39:54	[INFO]	[indexer.process.Statistics]			Memory (Heap) Available: 15271 MB
```

The double heap memory seams to solve the problem. The export isn't finished yet, but it looks good.

My question:

- Is it possible to generate an indexed Report from command line and that the system has more free RAM because no IPED-SearchApp is running?
- Is it possible to set the heap memory with some option?

**Comment by lfcnassif** [comment]
1. Yes, you can create an indexed report from command line. After checking the relevant bookmarks in "Create Indexed Report" menu option, close the "Create Report" dialog and click on "Save Bookmarks" in the menu to generate a xxx.iped file. Open a terminal and run (using the same IPED version used to create the cases):
`iped.exe -d xxx.iped -o report_folder`
2. Instead of using iped.exe, use, for example, java -Xms16G -Xmx16G -jar iped.jar. Currently it is not possible to set the heap memory used by report creation started by GUI, just by command line.
3. Usually IPED uses a few GBs of RAM (but your case is a bit large). Possibly that was some module leaking memory because of a corrupted file. Take a look at https://github.com/sepinf-inc/IPED/wiki/Troubleshooting#outofmemoryerror for a general approach to workaround OOME.

**Comment by lfcnassif** [comment]
There is also some memory guidelines at https://github.com/sepinf-inc/IPED/wiki/Performance-Tips

**Comment by gaffinet** [comment]
Thank you for the answer. I will try the different options.

I have to say that the iped tool is brilliant. It solves so many problems that I have with stuff like x-ways or fdk or linux bash hacking. Thanks

**Comment by lfcnassif** [comment]
You're welcome! Please report back if the OOME was solved when report creation finishes.

**Comment by gaffinet** [comment]
You may close the case, I managed to generate the indexed report with my 64g ram VM

For further testing I reduced the RAM of the VM to 32G

When I start iped.exe -d ....iped, I could see in the logfiles that iped only allocated about 8g for heap. So the process crashed again.

The solution was to launch the iped.jar with xms and xmx set to 16g

thank you for all the help
