### ISSUE TITLE
Processing error - LED WKFF

### ISSUE THREAD

**Issue by flbjuniorx** [sepinf-inc/IPED#348]
Hi!

I'm experiencing the error below while processing an image using the PEDO profile:

java -jar K:\iped-3.19\iped-3.19-SNAPSHOT\iped.jar -d .\image.E01 -o iped -profile pedo --portable
2021-01-25 18:55:29     [ERROR] [gpinf.indexer.IndexFiles]                      Processing Error:
java.lang.ArrayIndexOutOfBoundsException: 1
        at dpf.sp.gpinf.indexer.process.task.LedKFFTask.init(LedKFFTask.java:145) ~[iped-engine-3.19-snapshot.jar:?]
        at dpf.sp.gpinf.indexer.process.Worker.initTasks(Worker.java:113) ~[iped-engine-3.19-snapshot.jar:?]
        at dpf.sp.gpinf.indexer.process.Worker.<init>(Worker.java:95) ~[iped-engine-3.19-snapshot.jar:?]
        at dpf.sp.gpinf.indexer.process.Manager.iniciarIndexacao(Manager.java:352) ~[iped-engine-3.19-snapshot.jar:?]
        at dpf.sp.gpinf.indexer.process.Manager.process(Manager.java:205) ~[iped-engine-3.19-snapshot.jar:?]
        at dpf.sp.gpinf.indexer.IndexFiles.doInBackground(IndexFiles.java:216) [iped.jar:?]
        at dpf.sp.gpinf.indexer.IndexFiles.doInBackground(IndexFiles.java:59) [iped.jar:?]
        at javax.swing.SwingWorker$1.call(SwingWorker.java:295) [?:1.8.0_241]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_241]
        at javax.swing.SwingWorker.run(SwingWorker.java:334) [?:1.8.0_241]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_241]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_241]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]

ERROR!!!
Check the log at K:\iped-3.19\iped-3.19-SNAPSHOT\log\IPED-2021-01-25-18-55-22.log

[LocalConfig.txt](https://github.com/sepinf-inc/IPED/files/5870185/LocalConfig.txt)
[IPEDConfig.txt](https://github.com/sepinf-inc/IPED/files/5870187/IPEDConfig.txt)

Tks!

**Comment by lfcnassif** [comment]
In LocalConfig.txt, there is
`ledWkffPath = K:/LED-1.25.01/pedo/ppwkff`
but it should be
`ledWkffPath = K:/LED-1.25.01/pedo/wkff`

**Comment by flbjuniorx** [comment]
Tks for the reply, lfcnassif.

I've found out that one of the WKFF txt files were with some error. The characters in that file was showed correctly in Notepad, but when cat'ed in shell it outputed some weird header:

==> FILE OK <==
#MD5 Total do Arquivo            *MD5 dos primeiros 64k bytes      *Hash Edonkey                     *SHA1                                     *MD5 dos primeiros 512 bytes      *Tamanho      *Nome                  *MD5 do primeiro megabyte         *SHA256

==> FILE BUGED <==
ÿþ# M D 5   T o t a l   d o   A r q u i v o                         * M D 5   d o s   p r i m e i r o s   6 4 k   b y t e s             * H a s h   E d o n k e y                                           * S H A 1                                                                           * M D 5   d o s   p r i m e i r o s   5 1 2   b y t e s             * T a m a n h o             * N o m e                                     * M D 5   d o   p r i m e i r o   m e g a b y t e                   * S H A 2 5 6 

Once corrected, the processing kept going.

Regards,

**Comment by vitorlco** [comment]
I'm with the same problem, but I didn't find error in any archive.

C:\IPED\IPED-3.18.13\iped-3.18.13>iped.exe -profile pedo -d "H:\DIVERSOS\DOCUMENTOS\EnCase" -o L:\PROCESSAMENTO
2022-02-16 20:02:23     [ERROR] [gpinf.indexer.IndexFiles]                      Processing Error:
java.lang.ArrayIndexOutOfBoundsException: 8
        at dpf.sp.gpinf.indexer.process.task.LedKFFTask.init(LedKFFTask.java:149) ~[iped-engine-3.18.13.jar:?]
        at dpf.sp.gpinf.indexer.process.Worker.initTasks(Worker.java:114) ~[iped-engine-3.18.13.jar:?]
        at dpf.sp.gpinf.indexer.process.Worker.<init>(Worker.java:96) ~[iped-engine-3.18.13.jar:?]
        at dpf.sp.gpinf.indexer.process.Manager.iniciarIndexacao(Manager.java:441) ~[iped-engine-3.18.13.jar:?]
        at dpf.sp.gpinf.indexer.process.Manager.process(Manager.java:231) ~[iped-engine-3.18.13.jar:?]
        at dpf.sp.gpinf.indexer.IndexFiles.startManager(IndexFiles.java:196) [iped.jar:?]
        at dpf.sp.gpinf.indexer.IndexFiles.execute(IndexFiles.java:249) [iped.jar:?]
        at dpf.sp.gpinf.indexer.IndexFiles.main(IndexFiles.java:319) [iped.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_152]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_152]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_152]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_152]
        at dpf.sp.gpinf.indexer.util.CustomLoader.run(CustomLoader.java:65) [iped-engine-3.18.13.jar:?]
        at dpf.sp.gpinf.indexer.IndexFiles.main(IndexFiles.java:315) [iped.jar:?]

ERROR!!!
Check the log at C:\IPED\IPED-3.18.13\iped-3.18.13\log\IPED-2022-02-16-20-02-12.log

C:\IPED\IPED-3.18.13\iped-3.18.13
[LocalConfig.txt](https://github.com/sepinf-inc/IPED/files/8083884/LocalConfig.txt)
[IPEDConfig.txt](https://github.com/sepinf-inc/IPED/files/8083887/IPEDConfig.txt)
>

**Comment by tc-wleite** [comment]
From your LocalConfig.txt, it looks like you are using LED's version 1.21.01, right?
That version is too old (released ~6 years ago) and columns included in hash file changed in version 1.24.00.
IPED 3.18.x should work with LED versions between 1.24 and 1.28.
The new IPED version (4.0.0) will not read these LED files anymore, to avoid this kind of dependency. It will be able to use LED hashes, but in a standard CSV format.

**Comment by flbjuniorx** [comment]
Wladmir, is there any tool or script that validates the entries in the hash file? In my case, when I updated the file with some new hashes, the error raised.

> From your LocalConfig.txt, it looks like you are using LED's version 1.21.01, right? That version is too old (released ~6 years ago) and columns included in hash file changed in version 1.24.00. IPED 3.18.x should work with LED versions between 1.24 and 1.28. The new IPED version (4.0.0) will not read these LED files anymore, to avoid this kind of dependency. It will be able to use LED hashes, but in a standard CSV format.

**Comment by tc-wleite** [comment]
> @tc-wleite, is there any tool or script that validates the entries in the hash file? In my case, when I updated the file with some new hashes, the error raised. I guess there was some wrong character or misconfiguration in that ones.

First check the version you are using (and which tool to generate the hashes).
If you update the hashes and it doesn't work, probably the generated format is different from the ones contained in the wkff (or hashes) folder. So I guess it wouldn't work in LED too.

Basically, to use LED hashes in IPED you must use LED versions between 1.24 and 1.28 as I mentioned, and for calculate new hashes in the correct format use this: [https://github.com/tc-wleite/CalcWKFF](https://github.com/tc-wleite/CalcWKFF)
LED versions after 1.29 are nor compatible with IPED, and the hash generation program (for using in LED only) is already distributed with LED.

Other than that, from your previous post, it seems that there is some character encoding problem. 
It should be a plain text file (not Unicode).
