### ISSUE TITLE
Fail to delete temp file of DBX files

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#365]
java.nio.file.FileSystemException: N:\temp\indexador-temp1612998071927\iped3879667770393822858.tmp: The process cannot access the file because it is being used by another process.
	at sun.nio.fs.WindowsException.translateToIOException(Unknown Source) ~[?:1.8.0_152]
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source) ~[?:1.8.0_152]
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source) ~[?:1.8.0_152]
	at sun.nio.fs.WindowsFileSystemProvider.implDelete(Unknown Source) ~[?:1.8.0_152]
	at sun.nio.fs.AbstractFileSystemProvider.delete(Unknown Source) ~[?:1.8.0_152]
	at java.nio.file.Files.delete(Unknown Source) ~[?:1.8.0_152]
	at gpinf.dev.data.Item$1.close(Item.java:710) ~[iped-engine-3.19-snapshot.jar:?]
	at org.apache.tika.io.TemporaryResources.close(TemporaryResources.java:145) ~[tika-core-1.20.jar:1.20]
	at gpinf.dev.data.Item.dispose(Item.java:284) [iped-engine-3.19-snapshot.jar:?]
	at gpinf.dev.data.Item.dispose(Item.java:279) [iped-engine-3.19-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:177) [iped-engine-3.19-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:207) [iped-engine-3.19-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:170) [iped-engine-3.19-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:207) [iped-engine-3.19-snapshot.jar:?]

**Comment by lfcnassif** [comment]
This is because DBX files currently are mmaped by the parser (originally for performance reasons) and closing original RAF or FileChannel does not invalidate the mmap. Will decide tomorrow if mmap code will be removed or if some "Unsafe" code will be used.

**Comment by lfcnassif** [comment]
Did some performance tests, no noticeable difference using mmap, so I removed that code.
