### ISSUE TITLE
Error indexing ufdr

### ISSUE THREAD

**Issue by fcscoutinho** [sepinf-inc/IPED#402]
Processing of files on iped is being stopped abruptly ... follow the log:

Error in the pront of comando (windows):

2021-03-19 15:48:34     [ERROR] [indexer.process.Manager$1]                     Error commiting. Rollback commit started...
2021-03-19 15:48:34     [ERROR] [indexer.process.Manager$1]                     Rollback commit finished.
2021-03-19 15:48:34     [ERROR] [gpinf.indexer.IndexFiles]                      Processing Error:
org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (cannot commit - no transaction is active)
        at org.sqlite.core.DB.newSQLException(DB.java:941) ~[sqlite-jdbc-3.25.2.jar:?]
        at org.sqlite.core.DB.newSQLException(DB.java:953) ~[sqlite-jdbc-3.25.2.jar:?]
        at org.sqlite.core.DB.throwex(DB.java:918) ~[sqlite-jdbc-3.25.2.jar:?]
        at org.sqlite.core.DB.exec(DB.java:178) ~[sqlite-jdbc-3.25.2.jar:?]
        at org.sqlite.SQLiteConnection.commit(SQLiteConnection.java:404) ~[sqlite-jdbc-3.25.2.jar:?]
        at dpf.sp.gpinf.indexer.process.task.ExportFileTask.commitStorage(ExportFileTask.java:656) ~[iped-engine-3.19-snapshot.jar:?]
        at dpf.sp.gpinf.indexer.process.Manager$1.run(Manager.java:453) ~[iped-engine-3.19-snapshot.jar:?]

Last lines off log:

org.xml.sax.SAXException: Error writing: 

java.io.IOException: Pipe closed
2021-03-19 15:48:34	[WARN]	[indexer.parsers.ImageOCRMetadataParser]			OCRParser error on 'D:\INDEX_TEMP\indexador-temp1616165236885\apache-tika-7849631109755760675.tmp' (1627205 bytes)	org.apache.tika.sax.TaggedSAXException: Error writing: 

org.xml.sax.SAXException: Error writing: 

java.io.IOException: Pipe closed
2021-03-19 15:48:34	[WARN]	[indexer.parsers.ImageOCRMetadataParser]			OCRParser error on 'D:\INDEX_TEMP\indexador-temp1616165236885\apache-tika-1536226541195646677.tmp' (322188 bytes)	org.apache.tika.sax.TaggedSAXException: Error writing: 

org.xml.sax.SAXException: Error writing: 

java.io.IOException: Pipe closed
2021-03-19 15:48:34	[WARN]	[indexer.parsers.ImageOCRMetadataParser]			OCRParser error on 'D:\INDEX_TEMP\indexador-temp1616165236885\apache-tika-3427337686129410044.tmp' (1037165 bytes)	org.apache.tika.sax.TaggedSAXException: Error writing: 

org.xml.sax.SAXException: Error writing: 

java.io.IOException: Pipe closed
2021-03-19 15:48:34	[WARN]	[indexer.parsers.ImageOCRMetadataParser]			OCRParser error on 'D:\INDEX_TEMP\indexador-temp1616165236885\apache-tika-2392955201685697247.tmp' (1037165 bytes)	org.apache.tika.sax.TaggedSAXException: Error writing: 

org.xml.sax.SAXException: Error writing: 

java.io.IOException: Pipe closed
2021-03-19 15:48:34	[INFO]	[indexer.process.Worker]			Worker-12 interrupted on Item_03-Relatorio_Completo_TA_279.ufdr/Samsung GSM_SM-A515F_DS Galaxy A51.zip/sdcard/CamScanner/.images/KgMRSBTUHDTV8NJg9DdNfgUE.jpg (322188 bytes)
2021-03-19 15:48:34	[WARN]	[indexer.parsers.ImageOCRMetadataParser]			OCRParser error on 'D:\INDEX_TEMP\indexador-temp1616165236885\apache-tika-4876387147699619162.tmp' (0 bytes)	org.apache.tika.sax.TaggedSAXException: Error writing: 

org.xml.sax.SAXException: Error writing: 

java.io.IOException: Pipe closed
2021-03-19 15:48:34	[INFO]	[indexer.process.Worker]			Worker-4 interrupted on Item_03-Relatorio_Completo_TA_279.ufdr/Samsung GSM_SM-A515F_DS Galaxy A51.zip/sdcard/CamScanner/.images/.originals/y20f12aA266SEAMSb6tUF038.jpg (1627205 bytes)
2021-03-19 15:48:34	[INFO]	[indexer.process.Worker]			Worker-11 interrupted on Item_03-Relatorio_Completo_TA_279.ufdr/Samsung GSM_SM-A515F_DS Galaxy A51.zip/sdcard/CamScanner/.images/.originals/KgMRSBTUHDTV8NJg9DdNfgUE.jpg (1037165 bytes)
2021-03-19 15:48:34	[WARN]	[indexer.parsers.ImageOCRMetadataParser]			OCRParser error on 'D:\INDEX_TEMP\indexador-temp1616165236885\apache-tika-5042136861691735671.tmp' (1627205 bytes)	org.apache.tika.sax.TaggedSAXException: Error writing: 

org.xml.sax.SAXException: Error writing: 

java.io.IOException: Pipe closed
2021-03-19 15:48:34	[INFO]	[indexer.process.Worker]			Worker-3 interrupted on Item_03-Relatorio_Completo_TA_279.ufdr/Samsung GSM_SM-A515F_DS Galaxy A51.zip/data/media/0/CamScanner/.images/.originals/y20f12aA266SEAMSb6tUF038.jpg (1627205 bytes)
2021-03-19 15:48:34	[ERROR]	[gpinf.indexer.IndexFiles]			Processing Error: 
org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (cannot commit - no transaction is active)
	at org.sqlite.core.DB.newSQLException(DB.java:941) ~[sqlite-jdbc-3.25.2.jar:?]
	at org.sqlite.core.DB.newSQLException(DB.java:953) ~[sqlite-jdbc-3.25.2.jar:?]
	at org.sqlite.core.DB.throwex(DB.java:918) ~[sqlite-jdbc-3.25.2.jar:?]
	at org.sqlite.core.DB.exec(DB.java:178) ~[sqlite-jdbc-3.25.2.jar:?]
	at org.sqlite.SQLiteConnection.commit(SQLiteConnection.java:404) ~[sqlite-jdbc-3.25.2.jar:?]
	at dpf.sp.gpinf.indexer.process.task.ExportFileTask.commitStorage(ExportFileTask.java:656) ~[iped-engine-3.19-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.Manager$1.run(Manager.java:453) ~[iped-engine-3.19-snapshot.jar:?]
2021-03-19 15:48:34	[INFO]	[indexer.process.Worker]			Worker-13 interrupted on Item_03-Relatorio_Completo_TA_279.ufdr/Samsung GSM_SM-A515F_DS Galaxy A51.zip/sdcard/CamScanner/.images/.originals/KgMRSBTUHDTV8NJg9DdNfgUE.jpg (1037165 bytes)
2021-03-19 15:48:34	[INFO]	[indexer.process.Worker]			Worker-8 interrupted on Item_03-Relatorio_Completo_TA_279.ufdr/Samsung GSM_SM-A515F_DS Galaxy A51.zip/sdcard/CamScanner/.images/.originals/y20f12aA266SEAMSb6tUF038.jpg (1627205 bytes)

**Comment by lfcnassif** [comment]
Could you send the full log?

PS: I do not recommend using master for production.

**Comment by fcscoutinho** [comment]
Yes, of course, but in private because the log has the name of the operation

**Comment by fcscoutinho** [comment]
[IPED-2021-03-19-11-47-14 - v2.log](https://github.com/sepinf-inc/IPED/files/6175115/IPED-2021-03-19-11-47-14.-.v2.log)

**Comment by lfcnassif** [comment]
Thank you, I already got the log by email. I've never seen this error. Seems not related to UFDR but with internal subitem sqlite storage. Will take a closer look on monday.

**Comment by fcscoutinho** [comment]
Ok, thanks.

Em sáb., 20 de mar. de 2021 18:47, Luis Nassif ***@***.***>
escreveu:

**Comment by lfcnassif** [comment]
I am not able to reproduce this with master. Did you try to process the case again? Does the error happen every time? Could you try processing 1 ufdr at a time? Could you reproduce this with last v3.18.4?

**Comment by fcscoutinho** [comment]
I am managing to index one UFDR at a time. When everything is over I set up a multicase.

Everything is alright!!!!
Thanks!

**Comment by lfcnassif** [comment]
Could you test with 3.18.4 with all those UFDRs?

**Comment by fcscoutinho** [comment]
Yes of course, I just have to download and configure it to do the test.

**Comment by fcscoutinho** [comment]
I found out what was causing the error! I am using an HP Workstation that was still in the factory configuration. I deactivated the antivirus, but HP is sending its new machines with "hp wolf security" it was preventing the execution of several tasks of IPED.

**Comment by lfcnassif** [comment]
Thanks for digging into this and for the feedback!

**Comment by lfcnassif** [comment]
PS: HP Sure Sense software is problematic too. It was unzipping RAR files in system32 folder of our processing machines silently...

**Comment by fcscoutinho** [comment]
I did a clean installation of windows 10, that way I think it won't give any more problems!

Thank you Nassif.
