### ISSUE TITLE
Errors in the console while processing corrupted VCFs

### ISSUE THREAD

**Issue by tc-wleite** [sepinf-inc/IPED#490]
A few corrupted carved VCFs are generating errors in the console (an example in the end of this post).
@lfcnassif, this is a really minor issue, but I think such error messages should be ignored, right?!

I noticed that `Log4j2Configuration*.xml` already contains a configuration of `PackageRegexpFilter` to ignore messages from FreeMarker with the following package pattern `(.*freemarker\.log.*)`, but it does not cover the errors I found.
Extending the filter to `(.*freemarker\..*)` is enough to filter the errors I got here, but I am not sure if this change would filter out other messages that should be preserved.

```
2021-04-24 23:38:20	[ERROR]	[freemarker.log._JULLoggerFactory$JULLogger]   Error executing FreeMarker template
freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
==> sound.contentType  [in template "hcard-template.html" at line 179, column 73]

----
Tip: It's the step after the last dot that caused this error, not those before it.
----
Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, 
either specify a default value like myOptionalVar!myDefault, 
or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. 
(These only cover the last step of the expression; to cover the whole expression, 
use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
----

----
FTL stack trace ("~" means nesting-related):
	- Failed at: #assign sourceSrc = utils.base64(soun...  [in template "hcard-template.html" at line 179, column 41]
----
	at freemarker.core.InvalidReferenceException.getInstance(InvalidReferenceException.java:134) ~[freemarker-2.3.30.jar:2.3.30]
	at freemarker.core.UnexpectedTypeException.newDescriptionBuilder(UnexpectedTypeException.java:85) ~[freemarker-2.3.30.jar:2.3.30]
	at freemarker.core.UnexpectedTypeException.<init>(UnexpectedTypeException.java:48) ~[freemarker-2.3.30.jar:2.3.30]
	at freemarker.core.NonHashException.<init>(NonHashException.java:49) ~[freemarker-2.3.30.jar:2.3.30]
	at freemarker.core.Dot._eval(Dot.java:48) ~[freemarker-2.3.30.jar:2.3.30]
	at freemarker.core.Expression.eval(Expression.java:101) ~[freemarker-2.3.30.jar:2.3.30]
	at freemarker.core.ListLiteral.getModelList(ListLiteral.java:98) ~[freemarker-2.3.30.jar:2.3.30]
	at freemarker.core.MethodCall._eval(MethodCall.java:60) ~[freemarker-2.3.30.jar:2.3.30]
	at freemarker.core.Expression.eval(Expression.java:101) ~[freemarker-2.3.30.jar:2.3.30]
	at freemarker.core.Assignment.accept(Assignment.java:134) ~[freemarker-2.3.30.jar:2.3.30]
	at freemarker.core.Environment.visit(Environment.java:334) [freemarker-2.3.30.jar:2.3.30]
	at freemarker.core.Environment.visit(Environment.java:340) [freemarker-2.3.30.jar:2.3.30]
	at freemarker.core.Environment.visit(Environment.java:340) [freemarker-2.3.30.jar:2.3.30]
	at freemarker.core.Environment.visit(Environment.java:376) [freemarker-2.3.30.jar:2.3.30]
	at freemarker.core.IteratorBlock$IterationContext.executedNestedContentForCollOrSeqListing(IteratorBlock.java:321) [freemarker-2.3.30.jar:2.3.30]
	at freemarker.core.IteratorBlock$IterationContext.executeNestedContent(IteratorBlock.java:271) [freemarker-2.3.30.jar:2.3.30]
	at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:244) [freemarker-2.3.30.jar:2.3.30]
	at freemarker.core.Environment.visitIteratorBlock(Environment.java:644) [freemarker-2.3.30.jar:2.3.30]
	at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:108) [freemarker-2.3.30.jar:2.3.30]
	at freemarker.core.IteratorBlock.accept(IteratorBlock.java:94) [freemarker-2.3.30.jar:2.3.30]
	at freemarker.core.Environment.visit(Environment.java:334) [freemarker-2.3.30.jar:2.3.30]
	at freemarker.core.Environment.visit(Environment.java:340) [freemarker-2.3.30.jar:2.3.30]
	at freemarker.core.Environment.process(Environment.java:313) [freemarker-2.3.30.jar:2.3.30]
	at freemarker.template.Template.process(Template.java:383) [freemarker-2.3.30.jar:2.3.30]
	at ezvcard.io.html.HCardPage.write(HCardPage.java:168) [ez-vcard-0.10.6.jar:?]
	at ezvcard.io.chain.ChainingHtmlWriter.go(ChainingHtmlWriter.java:97) [ez-vcard-0.10.6.jar:?]
	at dpf.mg.udi.gpinf.vcardparser.VCardParser.parse(VCardParser.java:98) [iped-parsers-impl-4.0.0-snapshot.jar:?]
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280) [tika-core-1.26.jar:1.26]
	at dpf.sp.gpinf.indexer.parsers.IndexerDefaultParser.parse(IndexerDefaultParser.java:233) [iped-parsers-impl-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.io.ParsingReader$BackgroundParsing.run(ParsingReader.java:251) [iped-engine-4.0.0-snapshot.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_282]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_282]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_282]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_282]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
```

**Comment by tc-wleite** [comment]
Attached is one file that causes this error.
Carving must be enabled.
I got it testing with 4.0.0-snapshot, but checked that it also happens with previous IPED versions.
[a.zip](https://github.com/sepinf-inc/IPED/files/6372324/a.zip)

**Comment by lfcnassif** [comment]
Yes, they should be ignored. I think the broader pattern is ok. Console messages should come from just IPED classes. Library errors should go just to log.

**Comment by lfcnassif** [comment]
Thanks @tc-wleite
