### ISSUE TITLE
Race condition in QueryBuilder

### ISSUE THREAD

**Issue by fmpfeifer** [sepinf-inc/IPED#510]
While working on #486, I came across a bug that was driving me crazy.
It turns out that, for #486, we have to make more intense use of the IItemSearcher.
But sometimes the processing was interrupted by an NumberFormatException (inputString "" or multiple points).

Here is the stack trace:

```
java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(Unknown Source) ~[?:1.8.0_152]
	at java.lang.Long.parseLong(Unknown Source) ~[?:1.8.0_152]
	at java.lang.Long.parseLong(Unknown Source) ~[?:1.8.0_152]
	at java.text.DigitList.getLong(Unknown Source) ~[?:1.8.0_152]
	at java.text.DecimalFormat.parse(Unknown Source) ~[?:1.8.0_152]
	at java.text.NumberFormat.parse(Unknown Source) ~[?:1.8.0_152]
	at org.apache.lucene.queryparser.flexible.standard.processors.PointRangeQueryNodeProcessor.postProcessNode(PointRangeQueryNodeProcessor.java:101) ~[lucene-queryparser-6.6.6.jar:6.6.6 68fa249034ba8b273955f20097700dc2fbb7a800 - ishan - 2019-03-29 09:08:34]
	at org.apache.lucene.queryparser.flexible.core.processors.QueryNodeProcessorImpl.processIteration(QueryNodeProcessorImpl.java:98) ~[lucene-queryparser-6.6.6.jar:6.6.6 68fa249034ba8b273955f20097700dc2fbb7a800 - ishan - 2019-03-29 09:08:34]
	at org.apache.lucene.queryparser.flexible.core.processors.QueryNodeProcessorImpl.processChildren(QueryNodeProcessorImpl.java:124) ~[lucene-queryparser-6.6.6.jar:6.6.6 68fa249034ba8b273955f20097700dc2fbb7a800 - ishan - 2019-03-29 09:08:34]
	at org.apache.lucene.queryparser.flexible.core.processors.QueryNodeProcessorImpl.processIteration(QueryNodeProcessorImpl.java:96) ~[lucene-queryparser-6.6.6.jar:6.6.6 68fa249034ba8b273955f20097700dc2fbb7a800 - ishan - 2019-03-29 09:08:34]
	at org.apache.lucene.queryparser.flexible.core.processors.QueryNodeProcessorImpl.process(QueryNodeProcessorImpl.java:89) ~[lucene-queryparser-6.6.6.jar:6.6.6 68fa249034ba8b273955f20097700dc2fbb7a800 - ishan - 2019-03-29 09:08:34]
	at org.apache.lucene.queryparser.flexible.core.processors.QueryNodeProcessorPipeline.process(QueryNodeProcessorPipeline.java:89) ~[lucene-queryparser-6.6.6.jar:6.6.6 68fa249034ba8b273955f20097700dc2fbb7a800 - ishan - 2019-03-29 09:08:34]
	at org.apache.lucene.queryparser.flexible.core.QueryParserHelper.parse(QueryParserHelper.java:250) ~[lucene-queryparser-6.6.6.jar:6.6.6 68fa249034ba8b273955f20097700dc2fbb7a800 - ishan - 2019-03-29 09:08:34]
	at org.apache.lucene.queryparser.flexible.standard.StandardQueryParser.parse(StandardQueryParser.java:159) ~[lucene-queryparser-6.6.6.jar:6.6.6 68fa249034ba8b273955f20097700dc2fbb7a800 - ishan - 2019-03-29 09:08:34]
	at dpf.sp.gpinf.indexer.search.QueryBuilder.getQuery(QueryBuilder.java:151) ~[iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.search.QueryBuilder.getQuery(QueryBuilder.java:116) ~[iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.search.IPEDSearcher.setQuery(IPEDSearcher.java:84) ~[iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.search.IPEDSearcher.<init>(IPEDSearcher.java:67) ~[iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.ItemSearcher.getResult(ItemSearcher.java:72) ~[iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.ItemSearcher.searchIterable(ItemSearcher.java:47) ~[iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.ItemSearcher.search(ItemSearcher.java:38) ~[iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.parsers.util.Util.getItems(Util.java:231) ~[iped-parsers-impl-4.0.0-snapshot.jar:?]
	at dpf.mg.udi.gpinf.whatsappextractor.ReportGenerator.findMediaItem(ReportGenerator.java:595) ~[iped-parsers-impl-4.0.0-snapshot.jar:?]
	at dpf.mg.udi.gpinf.whatsappextractor.ReportGenerator.printMessage(ReportGenerator.java:387) ~[iped-parsers-impl-4.0.0-snapshot.jar:?]
	at dpf.mg.udi.gpinf.whatsappextractor.ReportGenerator.lambda$generateNextChatHtml$0(ReportGenerator.java:170) ~[iped-parsers-impl-4.0.0-snapshot.jar:?]
	at dpf.mg.udi.gpinf.whatsappextractor.ReportGenerator$1.lookup(ReportGenerator.java:687) [iped-parsers-impl-4.0.0-snapshot.jar:?]
	at org.apache.commons.text.StringSubstitutor.resolveVariable(StringSubstitutor.java:1012) [commons-text-1.8.jar:1.8]
	at org.apache.commons.text.StringSubstitutor.substitute(StringSubstitutor.java:1356) [commons-text-1.8.jar:1.8]
	at org.apache.commons.text.StringSubstitutor.substitute(StringSubstitutor.java:1242) [commons-text-1.8.jar:1.8]
	at org.apache.commons.text.StringSubstitutor.replace(StringSubstitutor.java:764) [commons-text-1.8.jar:1.8]
	at dpf.mg.udi.gpinf.whatsappextractor.ReportGenerator.printMessageFile(ReportGenerator.java:696) [iped-parsers-impl-4.0.0-snapshot.jar:?]
	at dpf.mg.udi.gpinf.whatsappextractor.ReportGenerator.generateNextChatHtml(ReportGenerator.java:149) [iped-parsers-impl-4.0.0-snapshot.jar:?]
	at dpf.mg.udi.gpinf.whatsappextractor.WhatsAppParser.createReport(WhatsAppParser.java:205) [iped-parsers-impl-4.0.0-snapshot.jar:?]
	at dpf.mg.udi.gpinf.whatsappextractor.WhatsAppParser.parseWhatsappMessages(WhatsAppParser.java:277) [iped-parsers-impl-4.0.0-snapshot.jar:?]
	at dpf.mg.udi.gpinf.whatsappextractor.WhatsAppParser.parse(WhatsAppParser.java:187) [iped-parsers-impl-4.0.0-snapshot.jar:?]
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280) [tika-core-1.26.jar:1.26]
	at dpf.sp.gpinf.indexer.parsers.IndexerDefaultParser.parse(IndexerDefaultParser.java:233) [iped-parsers-impl-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.io.ParsingReader$BackgroundParsing.run(ParsingReader.java:251) [iped-engine-4.0.0-snapshot.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_152]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_152]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_152]
```

but the query that was: `nome:"09c5612b\-ae8a\-4890\-9f02\-2f26223a229d.jpg" AND tamanho:[137874 TO 137888]`
this is a valid query.

Running the process again, the error popped out in a different query, indicationg a possible race condition.

**Comment by fmpfeifer** [comment]
Will send a PR to try to fix this.
As I'm not familiar with this code, please review to make sure if won't cause undesirable side effects.

**Comment by fmpfeifer** [comment]
With this fix I didn't manage to trigger this error again.
Did a few tests here, and also didn't see any noticeable performance degradation.

**Comment by lfcnassif** [comment]
Thank you @fmpfeifer! But this is really strange because a new query parser is created before each parse... Maybe it is a lucene bug or maybe the issue could be in another place...

**Comment by fmpfeifer** [comment]
It turns out that lucene takes the `NumberFormat` from a config manager class (`PointConfig`). See [PointRangeQueryNodePorcessor.java](https://github.com/apache/lucene-solr/blob/releases/lucene-solr/6.6.6/lucene/queryparser/src/java/org/apache/lucene/queryparser/flexible/standard/processors/PointRangeQueryNodeProcessor.java):
```

QueryConfigHandler config = getQueryConfigHandler();

if (config != null) {
    TermRangeQueryNode termRangeNode = (TermRangeQueryNode) node;
    FieldConfig fieldConfig = config.getFieldConfig(StringUtils.toString(termRangeNode.getField()));

    if (fieldConfig != null) {
        PointsConfig numericConfig = fieldConfig.get(ConfigurationKeys.POINTS_CONFIG);

        if (numericConfig != null) {
            FieldQueryNode lower = termRangeNode.getLowerBound();
            FieldQueryNode upper = termRangeNode.getUpperBound();

            String lowerText = lower.getTextAsString();
            String upperText = upper.getTextAsString();
            NumberFormat numberFormat = numericConfig.getNumberFormat();
```

But, in `QueryBuilder`, for each `StandardQueryParser` created, the method `setPointsConfigMap` is called, and a static `pointsConfigCache` is passed in. So it is using the same  `NumberFormat` object for parsing the same fields, and the `NumberFormat` class isn't thread safe:

QueryBuilder:
```
private static HashMap<String, PointsConfig> pointsConfigCache;
```
...
```
StandardQueryParser parser = new StandardQueryParser(analyzer);
parser.setMultiFields(fields);
parser.setAllowLeadingWildcard(true);
parser.setFuzzyPrefixLength(2);
parser.setFuzzyMinSim(0.7f);
parser.setDateResolution(DateTools.Resolution.SECOND);
parser.setMultiTermRewriteMethod(MultiTermQuery.SCORING_BOOLEAN_REWRITE);
parser.setPointsConfigMap(getPointsConfigMap());
```

...

```
private HashMap<String, PointsConfig> getPointsConfigMap() {

    synchronized (lock) {
        if (ipedCase == prevIpedCase && pointsConfigCache != null) {
            return pointsConfigCache;
        }
    }
```

**Comment by lfcnassif** [comment]
Great! Thanks for the explanation, will apply your fix soon.
