### ISSUE TITLE
Java error with the build from 05.05.2021

### ISSUE THREAD

**Issue by reacan** [sepinf-inc/IPED#513]
Hello everyone!

The build process was successful however I get the following error when launching the processing:

2021-05-05 16:58:04	[ERROR]	[gpinf.indexer.IndexFiles]			Processing Error: 
java.lang.ClassNotFoundException: dpf.sp.gpinf.indexer.process.task.KFFTask
	at dpf.sp.gpinf.indexer.util.CustomLoader$CustomURLClassLoader.findClass(CustomLoader.java:126) ~[iped-engine-4.0.0-snapshot.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_261]
	at dpf.sp.gpinf.indexer.util.CustomLoader$CustomURLClassLoader.loadClass(CustomLoader.java:136) ~[iped-engine-4.0.0-snapshot.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_261]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_261]
	at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_261]
	at dpf.sp.gpinf.indexer.process.task.TaskInstaller.loadTasks(TaskInstaller.java:58) ~[iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.TaskInstaller.installProcessingTasks(TaskInstaller.java:40) ~[iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.Worker.<init>(Worker.java:93) ~[iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.Manager.iniciarIndexacao(Manager.java:423) ~[iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.Manager.process(Manager.java:222) ~[iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.IndexFiles.startManager(IndexFiles.java:175) [iped.jar:?]
	at dpf.sp.gpinf.indexer.IndexFiles.execute(IndexFiles.java:228) [iped.jar:?]
	at dpf.sp.gpinf.indexer.IndexFiles.main(IndexFiles.java:297) [iped.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_261]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_261]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_261]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_261]
	at dpf.sp.gpinf.indexer.util.CustomLoader.run(CustomLoader.java:65) [iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.IndexFiles.main(IndexFiles.java:293) [iped.jar:?]

ERROR!!!
Check the log at /root/Apps/IPED/target/release/iped-4.0.0-snapshot/log/IPED-2021-05-05-16-57-52.log

The log does not contain much more info, but if necessary I can post that as well.

**Comment by tc-wleite** [comment]
KFFTask class was removed in 4.0.0.
Didn't you mix configuration files from previous versions?

**Comment by reacan** [comment]
I did copy/paste configuration files from an older build, I will try with the original configuration files and see if it helps, thanks!

**Comment by lfcnassif** [comment]
Thanks @tc-wleite.
