### ISSUE TITLE
Error closing resources (master)

### ISSUE THREAD

**Issue by tc-wleite** [sepinf-inc/IPED#546]
Processing a case with many videos (using the master branch) I was getting several warnings like this in the log:

```
2021-05-14 16:14:13	[WARN]	[dev.data.Item]			Error closing resources of video1.mov
java.nio.file.FileSystemException: c:\TempIPED\indexador-temp1621019632175\iped203590075326825578.mov: O arquivo já está sendo usado por outro processo.
	at sun.nio.fs.WindowsException.translateToIOException(Unknown Source) ~[?:1.8.0_281]
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source) ~[?:1.8.0_281]
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source) ~[?:1.8.0_281]
	at sun.nio.fs.WindowsFileSystemProvider.implDelete(Unknown Source) ~[?:1.8.0_281]
	at sun.nio.fs.AbstractFileSystemProvider.delete(Unknown Source) ~[?:1.8.0_281]
	at java.nio.file.Files.delete(Unknown Source) ~[?:1.8.0_281]
	at gpinf.dev.data.Item$1.close(Item.java:710) ~[iped-engine-4.0.0-snapshot.jar:?]
	at org.apache.tika.io.TemporaryResources.close(TemporaryResources.java:156) ~[tika-core-1.26.jar:1.26]
	at gpinf.dev.data.Item.dispose(Item.java:284) [iped-engine-4.0.0-snapshot.jar:?]
	at gpinf.dev.data.Item.dispose(Item.java:279) [iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:188) [iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:218) [iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:181) [iped-engine-4.0.0-snapshot.jar:?]
	(...)
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:218) [iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:181) [iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.Worker.process(Worker.java:179) [iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.Worker.run(Worker.java:240) [iped-engine-4.0.0-snapshot.jar:?]
```

After a very long time investigating this issue, it turned out to be a problem in Tika MP4Parser.
The parser is keeping the temporary file opened, preventing it to be deleted.
It happens only with part of the videos handled by this parser, but there are hundreds of such files in the case I am working with.

I couldn't find a workaround, so I created an issue in Tika project:
https://issues.apache.org/jira/browse/TIKA-3405

This doesn't happen with previous IPED versions (3.18.x) and it seems to be a side effect of Tika upgrade (#178) and enabling the MP4Parser (#463).

**Comment by tc-wleite** [comment]
A test file that causes this issue: [video.zip](https://github.com/sepinf-inc/IPED/files/6481471/video.zip)
It must be processed inside a container (not directly in a folder), otherwise no temporary file would have to be created.

**Comment by lfcnassif** [comment]
Thank you @tc-wleite! I remember Tim Allison (Tika project leader) forked MP4Parser project in the past to fix some issues. Not sure if original or forked mp4parser is being used by Tika-1.26. Maybe we will need to send a PR them.

**Comment by lfcnassif** [comment]
Just a tip, not sure if you already know it, I have successfully used https://file-leak-detector.kohsuke.org/ in the past to track the source of open file handles a number of times in the past.

**Comment by tc-wleite** [comment]
> Thank you @tc-wleite! I remember Tim Allison (Tika project leader) forked MP4Parser project in the past to fix some issues. Not sure if original or forked mp4parser is being used by Tika-1.26. Maybe we will need to send a PR to them.

It is using the forked one.

**Comment by tc-wleite** [comment]
> Just a tip, not sure if you already know it, I have successfully used https://file-leak-detector.kohsuke.org/ in the past to track the source of open file handles a number of times in the past.

Yes, I used it here and was very helpful in this case.

**Comment by lfcnassif** [comment]
Will upgrade to recently released org.tallison.isoparser-1.9.41.6 and test if this was fixed.

**Comment by lfcnassif** [comment]
fix was better than expected: no "RuntimeException: box size of zero means 'till end of file. That is not yet supported" is thrown anymore for the sample, thanks to Tim Allison.

**Comment by lfcnassif** [comment]
Maybe master is now being affected by this https://issues.apache.org/jira/browse/TIKA-3459...
