### ISSUE TITLE
VcardParser not parsing cards with thumbnails. 

### ISSUE THREAD

**Issue by streeg** [sepinf-inc/IPED#549]
Hi, I am writing tests for the parsers, and today I found a problem when I tried to use the parser with a test file that contained a photo. The apparent problem is that getData() returns null as seen below: 
![errowhenvcardhasthumb](https://user-images.githubusercontent.com/22523306/118546959-13e43180-b72f-11eb-9148-0c53f12c3dc7.png)

Also here is the error log: 
```

java.lang.NullPointerException
	at java.util.Base64$Encoder.encode(Unknown Source)
	at java.util.Base64$Encoder.encodeToString(Unknown Source)
	at dpf.mg.udi.gpinf.vcardparser.VCardParser.extractMetadata(VCardParser.java:157)
	at dpf.mg.udi.gpinf.vcardparser.VCardParser.parse(VCardParser.java:93)
	at dpf.mg.udi.gpinf.vcardparser.VCardParserTest.testVCardCompleteInfoParser(VCardParserTest.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at junit.framework.TestCase.runTest(TestCase.java:177)
	at junit.framework.TestCase.runBare(TestCase.java:142)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:768)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
```

All the other information for VCards seems to be working just fine.

**Comment by lfcnassif** [comment]
Could you upload the file that reproduces this?

**Comment by streeg** [comment]
Sure! Sorry, I have forgotten to attach! 

[test_contactsCompleteInfo.zip](https://github.com/sepinf-inc/IPED/files/6496834/test_contactsCompleteInfo.zip)

**Comment by lfcnassif** [comment]
I'll fix the NPE. But how are you seeing the thumbnail of this vcard? MS Outlook doesn't show any thumb to me.

**Comment by lfcnassif** [comment]
ok seems it has a http link pointing to an external thumbnail

**Comment by lfcnassif** [comment]
Thanks @streeg for reporting this.
