### ISSUE TITLE
Rare aborting ConcurrentModificationException while processing

### ISSUE THREAD

**Issue by aberenguel** [sepinf-inc/IPED#690]
I was generating a report based on a case with UFDR and the following exception occurred (some strings omitted).

```
2021-08-10 17:16:16     [WARN]  [indexer.parsers.IndexerDefaultParser]                  ParsingThread-7 Parsing exception: iPhoneXXX.ufdr/Iphone XXXXXX/mobile/Library/Mobile Documents/XXXXXXXX~net~whatsapp~WhatsApp/Accounts/XXXXXXXX/backup/Document.tar>>Media/XXXXXXXXXX@s.whatsapp.net/6/3/xxxxxxx-xxx-xxxx-xxxx-xxxxxxxxx.pdf (230127 bytes)               org.apache.commons.io.IOExceptionWithCause: Unable to start a page
2021-08-10 17:16:16     [ERROR] [gpinf.indexer.IndexFiles]                      Processing Error: 
java.util.ConcurrentModificationException: null
        at java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1211) ~[?:1.8.0_281]
        at java.util.TreeMap$EntryIterator.next(TreeMap.java:1247) ~[?:1.8.0_281]
        at java.util.TreeMap$EntryIterator.next(TreeMap.java:1242) ~[?:1.8.0_281]
        at dpf.sp.gpinf.indexer.process.ProgressFrame.getParsersTime(ProgressFrame.java:301) ~[iped-search-app.jar:?]
        at dpf.sp.gpinf.indexer.process.ProgressFrame.propertyChange(ProgressFrame.java:171) ~[iped-search-app.jar:?]
        at dpf.sp.gpinf.indexer.WorkerProvider.firePropertyChange(WorkerProvider.java:34) ~[iped-engine-3.18.7.jar:?]
        at dpf.sp.gpinf.indexer.process.Manager.monitorarIndexacao(Manager.java:458) ~[iped-engine-3.18.7.jar:?]
        at dpf.sp.gpinf.indexer.process.Manager.process(Manager.java:232) ~[iped-engine-3.18.7.jar:?]
        at dpf.sp.gpinf.indexer.IndexFiles.startManager(IndexFiles.java:196) [iped-search-app.jar:?]
        at dpf.sp.gpinf.indexer.IndexFiles.execute(IndexFiles.java:249) [iped-search-app.jar:?]
        at dpf.sp.gpinf.indexer.IndexFiles.main(IndexFiles.java:319) [iped-search-app.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_281]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_281]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_281]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_281]
        at dpf.sp.gpinf.indexer.util.CustomLoader.run(CustomLoader.java:65) [iped-engine-3.18.7.jar:?]
        at dpf.sp.gpinf.indexer.IndexFiles.main(IndexFiles.java:315) [iped-search-app.jar:?]
```

I tried again and it worked.

**Comment by lfcnassif** [comment]
What iped version did you use?

**Comment by lfcnassif** [comment]
This is hard to reproduce, but I think commit e16a908 will fix it.

**Comment by aberenguel** [comment]
> What iped version did you use?
3.18.7

I was wondering if the e16a908 fixes it, because TreeMap is not thread-safe. But I think it fixes, since the ConcurrentModificationException might be happening due to some writing in ParsingTask.times in another thread. The fix is wrapping it. You're the guy, @lfcnassif !

**Comment by lfcnassif** [comment]
Actually I don't think this is fixed. The idea was to make a Map copy before iterating over it (notice original map is already a thread-safe one), but, at least in my JDK implementation, TreeMap(Map map) constructor uses map.entrySet().iterator() internally, so the exception could be thrown inside the constructor.
