### ISSUE TITLE
NullPointerException caused by 2nd level containers if processed again with --continue

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#719]
Found this in logs while working on #709, need to investigate next week:

```
java.lang.NullPointerException
	at java.io.ByteArrayInputStream.<init>(Unknown Source)
	at dpf.sp.gpinf.indexer.process.task.ExportFileTask$SQLiteInputStreamFactory.getSeekableInputStream(ExportFileTask.java:696)
	at gpinf.dev.data.Item.getStream(Item.java:659)
	at gpinf.dev.data.Item.getBufferedStream(Item.java:335)
	at dpf.sp.gpinf.indexer.process.task.EntropyTask.process(EntropyTask.java:61)
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processMonitorTimeout(AbstractTask.java:252)
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:184)
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:229)
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:192)

```

**Comment by lfcnassif** [comment]
What is happening here: even fully expanded and commited containers may need to be processed again, their subitems still could be in processing queue or may not be commited when processing was interrupted . So, although already commited, containers may be expanded again when resuming. But as they are already commited, they are ignored later to be not indexed again, just expanded. If they are 2nd level containers, ignoring causes the referenced file/data to be deleted from disk. But if they have duplicates, this can affect other subitems pointing to the same data with the same hash, resulting in the exception above.

**Comment by lfcnassif** [comment]
Actually, even unique (not duplicates) 2nd level containers that are processed again when resuming are deleted and they become inaccessible from the analysis UI.

**Comment by lfcnassif** [comment]
This was wrongly fixed.
