### ISSUE TITLE
Error exporting subitem:	java.io.FileNotFoundException xxxxxx\indexador\subitens\043 (Access is denied) when resuming processing

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#721]
I first found this in logs attached to #702. Now I'm able to reproduce using --continue with a small test case. Stacktrace:
```
java.io.FileNotFoundException: E:\teste\continue-7z-4\indexador\subitens\043 (Access is denied)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at dpf.sp.gpinf.indexer.process.task.ExportFileTask.extractFile(ExportFileTask.java:532)
	at dpf.sp.gpinf.indexer.process.task.ParsingTask.parseEmbedded(ParsingTask.java:596)
	at org.apache.tika.parser.pkg.CompressorParser.parse(CompressorParser.java:280)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280)
	at dpf.sp.gpinf.indexer.parsers.IndexerDefaultParser.parse(IndexerDefaultParser.java:244)
	at dpf.sp.gpinf.indexer.io.ParsingReader$BackgroundParsing.run(ParsingReader.java:247)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by lfcnassif** [comment]
Issue here was the read-only flag set on files left behind from previous processing
