### ISSUE TITLE
Error loading resource bundle property at the initialization

### ISSUE THREAD

**Issue by aberenguel** [sepinf-inc/IPED#739]
I'm using branch master (commit 554c3f6e0).

At the initialization I got this exception
```
java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key PythonModule.JepNotFound
	at java.util.ResourceBundle.getObject(ResourceBundle.java:450)
	at java.util.ResourceBundle.getString(ResourceBundle.java:407)
	at dpf.sp.gpinf.indexer.parsers.util.Messages.getString(Messages.java:23)
	at dpf.inc.sepinf.python.PythonParser.<clinit>(PythonParser.java:44)
	at dpf.sp.gpinf.indexer.process.task.PythonTask.<clinit>(PythonTask.java:29)
	at dpf.sp.gpinf.indexer.config.TaskInstallerConfig.getScriptTask(TaskInstallerConfig.java:100)
	at dpf.sp.gpinf.indexer.config.TaskInstallerConfig.loadTasks(TaskInstallerConfig.java:89)
	at dpf.sp.gpinf.indexer.config.TaskInstallerConfig.getNewTaskInstances(TaskInstallerConfig.java:47)
	at dpf.sp.gpinf.indexer.Configuration.loadConfigurables(Configuration.java:195)
	at dpf.sp.gpinf.indexer.Configuration.loadConfigurables(Configuration.java:139)
	at dpf.sp.gpinf.indexer.IndexFiles.main(IndexFiles.java:251)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at dpf.sp.gpinf.indexer.util.CustomLoader.run(CustomLoader.java:65)
	at dpf.sp.gpinf.indexer.IndexFiles.main(IndexFiles.java:271)
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at dpf.sp.gpinf.indexer.util.CustomLoader.run(CustomLoader.java:65)
	at dpf.sp.gpinf.indexer.IndexFiles.main(IndexFiles.java:271)
Caused by: java.lang.ExceptionInInitializerError
	at dpf.sp.gpinf.indexer.process.task.PythonTask.<clinit>(PythonTask.java:29)
	at dpf.sp.gpinf.indexer.config.TaskInstallerConfig.getScriptTask(TaskInstallerConfig.java:100)
	at dpf.sp.gpinf.indexer.config.TaskInstallerConfig.loadTasks(TaskInstallerConfig.java:89)
	at dpf.sp.gpinf.indexer.config.TaskInstallerConfig.getNewTaskInstances(TaskInstallerConfig.java:47)
	at dpf.sp.gpinf.indexer.Configuration.loadConfigurables(Configuration.java:195)
	at dpf.sp.gpinf.indexer.Configuration.loadConfigurables(Configuration.java:139)
	at dpf.sp.gpinf.indexer.IndexFiles.main(IndexFiles.java:251)
	... 6 more
Caused by: java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key PythonModule.JepNotFound
	at java.util.ResourceBundle.getObject(ResourceBundle.java:450)
	at java.util.ResourceBundle.getString(ResourceBundle.java:407)
	at dpf.sp.gpinf.indexer.parsers.util.Messages.getString(Messages.java:23)
	at dpf.inc.sepinf.python.PythonParser.<clinit>(PythonParser.java:44)
	... 13 more
```

I saw the property `PythonModule.JepNotFound` is there, but when it is loaded (statically), it seems that the resource bundle is not fully loaded or there is missing dependency load at the execution time of `dpf.inc.sepinf.python.PythonParser.<clinit>(PythonParser.java:44)`:
```java
public static final String JEP_NOT_FOUND = Messages.getString("PythonModule.JepNotFound");
```

As a ugly fix, I moved the load of the property values to the static code block:
```java
    static {
        // fix for https://github.com/sepinf-inc/IPED/issues/586
        try {
            JepConfig config = new JepConfig();
            config.setClassEnquirer(JEPClassFinder.getInstance());
            SharedInterpreter.setConfig(config);

            JEP_NOT_FOUND = Messages.getString("PythonModule.JepNotFound");
            DISABLED = Messages.getString("PythonModule.ModuleDisabled");
            SEE_MANUAL = Messages.getString("PythonModule.SeeManual");
            
        } catch (JepException e1) {
            throw new RuntimeException(e1);
        }
    }
```

I worked, but I don't know why.

**Comment by aberenguel** [comment]
As these messages are only used in log errors, I think the `Messages.getString()` should be invoked directly when the log message is being built.

**Comment by aberenguel** [comment]
There are another places where the internationalized properties are loaded in static initialization. Some of those classes: `IndexerDefaultParser`, `AresParser`, `MapTypeMSG`, `FirefoxSavedSessionParser`. It seems that theses ones did not triggered the exception. But I think it is a matter of luck (the order of classes initializations).

**Comment by lfcnassif** [comment]
Thanks @aberenguel, I will take a look. Maybe this is related to class loading order on Linux. Did you run "mvn clean" before building? I have already got this kind of issues after switching branches, which sometimes leaves garbage behind...

**Comment by aberenguel** [comment]
I hadn't ran `mvn clean` before.
Running `mvn clean package` made this issue disappears. 
Thank's @lfcnassif !
