### ISSUE TITLE
Missing DLL in OfficeViewer could cause LibreOffice window to be detached from main GUI

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#795]
An user reported the LibreOffice window was being shown on top of application GUI, not embedded. Also sent the stacktrace below:
```
java.lang.reflect.InvocationTargetException
        at java.awt.EventQueue.invokeAndWait(EventQueue.java:1349)
        at java.awt.EventQueue.invokeAndWait(EventQueue.java:1324)
        at javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1353)
        at dpf.sp.gpinf.indexer.ui.fileViewer.frames.LibreOfficeViewer.constructLOFrame(LibreOfficeViewer.java:247)
        at dpf.sp.gpinf.indexer.ui.fileViewer.frames.LibreOfficeViewer.init(LibreOfficeViewer.java:166)
        at dpf.sp.gpinf.indexer.desktop.ViewerController$2.run(ViewerController.java:117)
Caused by: java.lang.UnsatisfiedLinkError: Z:\operacao_teste\alvo1\HD2\SARDteste\indexador\lib\nativeview\64bit\nativeview.dll: Can't find dependent libraries
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1934)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1817)
        at java.lang.Runtime.load0(Runtime.java:810)
        at java.lang.System.load(System.java:1088)
        at ag.ion.bion.officelayer.NativeView.loadLibrary(NativeView.java:230)
        at ag.ion.bion.officelayer.NativeView.<init>(NativeView.java:135)
        at dpf.sp.gpinf.indexer.ui.fileViewer.frames.LibreOfficeViewer$1.run(LibreOfficeViewer.java:251)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```
Opening nativeview.dll with a dependency walker, it depends on msvcr100.dll, that is not being distributed together. This affects all released versions on machines without that dll installed.

**Comment by lfcnassif** [comment]
Just found this was not fixed properly while testing #1078 in a fresh Windows VM, putting msvcr100.dll in the same folder of nativeview.dll is not enough, it should be loaded before...

**Comment by lfcnassif** [comment]
Last commit is causing an `UnsatisfiedLinkError: Can't load library: E:\git\iped\target\release\iped-4.0.0-snapshot\..\lib\nativeview\64bit\msvcr100.dll` if UI is opened while processing

**Comment by aberenguel** [comment]
The load of dll is being executed in Linux too.
I surrounded the loading in order to load only in Windows.
```
                    if (System.getProperty("os.name").startsWith("Windows")) { 
                        File msvcr100 = new File(nativelib, "64bit/msvcr100.dll");
                        System.load(msvcr100.getAbsolutePath());
                    }
```

**Comment by lfcnassif** [comment]
Ugh... thanks for reporting!
