### ISSUE TITLE
Exception when opening an item processed as a single file (master only)

### ISSUE THREAD

**Issue by tc-wleite** [sepinf-inc/IPED#821]
After processing a single file, not a folder, using `-d /path/to/file.ext`, when I open the analysis application and try to view its contents, I am getting the following exception:

```
2021-11-05 12:34:51	[INFO]	[indexer.desktop.FileProcessor]			Opening AMOSTRA.pdf
java.lang.IllegalArgumentException
	at sun.nio.fs.WindowsPath.subpath(Unknown Source)
	at sun.nio.fs.WindowsPath.subpath(Unknown Source)
	at dpf.sp.gpinf.indexer.process.IndexItem.checkIfEvidenceFolderExists(IndexItem.java:1150)
	at dpf.sp.gpinf.indexer.process.IndexItem.getItem(IndexItem.java:937)
	at dpf.sp.gpinf.indexer.desktop.FileProcessor.process(FileProcessor.java:134)
	at dpf.sp.gpinf.indexer.desktop.FileProcessor.doInBackground(FileProcessor.java:117)
	at dpf.sp.gpinf.indexer.desktop.FileProcessor.doInBackground(FileProcessor.java:47)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

I tested with 3.18.9, and it worked fine, so I believe this seems to be a regression.

Adding `if (pathSuffix.getNameCount() > 1)` before `pathSuffix = pathSuffix.subpath(1, pathSuffix.getNameCount());` in `IndexItem.checkIfEvidenceFolderExists()` method seems to fix the issue, but I am not sure that would be the correct logic.

**Comment by lfcnassif** [comment]
Thanks @tc-wleite this seems to be a recent regression caused by #785. That check was there before but I couldn't remember why, seems you've found it :-)
