### ISSUE TITLE
Multicases IPED 4.0.0

### ISSUE THREAD

**Issue by fabriciossouza13** [sepinf-inc/IPED#834]
Boa tarde.

Estou utilizando o IPED 4.0.0 e processei cerca de 39 pendrives. Para analisar de forma mais prática tentei utilizar a função multicases com a seguinte linha de comando: "java -jar lib/iped-search-app.jar -multicases local_dos_pendrives_processados". Contudo, estou recebendo um erro que não estou conseguindo identificar qual o real problema.

2021-11-11 14:23:11	[INFO]	[indexer.desktop.ReportDialog]			Report command: [java, -cp, C:\IPED-4.0.0\IPED4\lib\iped-search-app.jar, dpf.sp.gpinf.indexer.IndexFiles, -d, C:\Users\usr\AppData\Local\Temp\3\report941632200735456111.iped, -o, R:\1153-1155, -asap, C:\Users\usr\AppData\Local\Temp\3\iped-2030938101049539056.report]
2021-11-11 14:23:12	[INFO]	[indexer.desktop.ReportDialog$2]			java.lang.NullPointerException
	at dpf.sp.gpinf.indexer.util.Util.loadNatLibs(Util.java:551)
	at dpf.sp.gpinf.indexer.Configuration.loadNativeLibs(Configuration.java:131)
	at dpf.sp.gpinf.indexer.Configuration.loadConfigurables(Configuration.java:174)
	at dpf.sp.gpinf.indexer.Configuration.loadConfigurables(Configuration.java:139)
	at dpf.sp.gpinf.indexer.IndexFiles.main(IndexFiles.java:251)

Gerei um marcador com todos os dados... Salvei o marcador... Infelizmente não consegui gerar um único caso com todos os processados...

Obs.: Tentei com a linha de comando mencionada no wiki e não funcionou... "IPEDSearch-App.exe -multicases param"

**Comment by lfcnassif** [comment]
I just tested from last commit on master and report creation from a multicase worked fine. From what commit did you compile from? Since 4.0.0 was not released yet, this info is needed, otherwise posting your stacktrace would be useless, I don't know what point in time version you are using. But, I "guess" the folder [case]/indexador/tools/tsk/x64 doesn't exist in your main case (used to open the multicase), that could mean your case or your 4.0.0 build is broken.

**Comment by lfcnassif** [comment]
Please reopen if you are able to reproduce after compiling from last commit on master using `mvn clean install`. Also please provide a step by step to reproduce this.
