### ISSUE TITLE
Make Java 11 minimum supported java version

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#885]
This will allow us to upgrade to Lucene 9.0 and Neo4j-4.x, as discussed at #179

**Comment by lfcnassif** [comment]
Actually, after this, if user tries to run using an older java version (e.g. 1.8), the JVM returns error below:
```
java -jar iped.jar -d f:\teste-files\caixas\mbox\Trash -o e:\teste\java11-build
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: dpf/sp/gpinf/indexer/IndexFiles has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:601)
```

I don't know if it is possible to give a more intuitive error message, but I think it is not a blocker anyway.
