### ISSUE TITLE
Random ClassCastException when opening GUI (master)

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#989]
I don't know when this started to happen exactly (after java11 upgrade, Dark Theme or other change, was some months ago...), but sometimes GUI starting fails with this or a similar stacktrace:
```
java.lang.ClassCastException: class javax.swing.plaf.FontUIResource cannot be cast to class javax.swing.InputMap (javax.swing.plaf.FontUIResource and javax.swing.InputMap are in module java.desktop of loader 'bootstrap')
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.getInputMap(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.installKeyboardActions(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicButtonUI.installKeyboardActions(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicButtonUI.installUI(Unknown Source)
	at java.desktop/javax.swing.JComponent.setUI(Unknown Source)
	at java.desktop/javax.swing.AbstractButton.setUI(Unknown Source)
	at java.desktop/javax.swing.plaf.synth.SynthArrowButton.updateUI(Unknown Source)
	at java.desktop/javax.swing.AbstractButton.init(Unknown Source)
	at java.desktop/javax.swing.JButton.<init>(Unknown Source)
	at java.desktop/javax.swing.JButton.<init>(Unknown Source)
	at java.desktop/javax.swing.plaf.synth.SynthArrowButton.<init>(Unknown Source)
	at java.desktop/javax.swing.plaf.synth.SynthComboBoxUI.createArrowButton(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicComboBoxUI.installComponents(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicComboBoxUI.installUI(Unknown Source)
	at java.desktop/javax.swing.plaf.synth.SynthComboBoxUI.installUI(Unknown Source)
	at java.desktop/javax.swing.JComponent.setUI(Unknown Source)
	at java.desktop/javax.swing.JComboBox.setUI(Unknown Source)
	at java.desktop/javax.swing.JComboBox.updateUI(Unknown Source)
	at java.desktop/javax.swing.JComboBox.init(Unknown Source)
	at java.desktop/javax.swing.JComboBox.<init>(Unknown Source)
	at dpf.sp.gpinf.indexer.desktop.MetadataPanel.<init>(MetadataPanel.java:102)
	at dpf.sp.gpinf.indexer.desktop.App.createGUI(App.java:616)
	at dpf.sp.gpinf.indexer.desktop.App$1.run(App.java:330)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
```

@tc-wleite do you have any tip?

**Comment by tc-wleite** [comment]
That is odd... I don't remember seeing this kind of error. I don't have any ideas right now, but I will think a bit more and update here.

**Comment by lfcnassif** [comment]
PS: I think sometimes the issue arises from a different component than MetadataPanel, if I remember, so seems to be something more global... if I got a different trace, I'll post here.

**Comment by lfcnassif** [comment]
Got a different stack now:
```
InteropFactory: cannot load com.sun.javafx.embed.swing.newimpl.InteropFactoryN
java.lang.ClassCastException: class javax.swing.plaf.nimbus.DerivedColor$UIResource cannot be cast to class java.awt.Insets (javax.swing.plaf.nimbus.DerivedColor$UIResource and java.awt.Insets are in module java.desktop of loader 'bootstrap')
	at java.desktop/javax.swing.plaf.synth.SynthButtonUI.updateStyle(Unknown Source)
	at java.desktop/javax.swing.plaf.synth.SynthButtonUI.installDefaults(Unknown Source)
	at java.desktop/javax.swing.plaf.synth.SynthArrowButton$SynthArrowButtonUI.installDefaults(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicButtonUI.installUI(Unknown Source)
	at java.desktop/javax.swing.JComponent.setUI(Unknown Source)
	at java.desktop/javax.swing.AbstractButton.setUI(Unknown Source)
	at java.desktop/javax.swing.plaf.synth.SynthArrowButton.updateUI(Unknown Source)
	at java.desktop/javax.swing.AbstractButton.init(Unknown Source)
	at java.desktop/javax.swing.JButton.<init>(Unknown Source)
	at java.desktop/javax.swing.JButton.<init>(Unknown Source)
	at java.desktop/javax.swing.plaf.synth.SynthArrowButton.<init>(Unknown Source)
	at java.desktop/javax.swing.plaf.synth.SynthScrollBarUI$1.<init>(Unknown Source)
	at java.desktop/javax.swing.plaf.synth.SynthScrollBarUI.createDecreaseButton(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicScrollBarUI.installComponents(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicScrollBarUI.installUI(Unknown Source)
	at java.desktop/javax.swing.JComponent.setUI(Unknown Source)
	at java.desktop/javax.swing.JScrollBar.setUI(Unknown Source)
	at java.desktop/javax.swing.JScrollBar.updateUI(Unknown Source)
	at java.desktop/javax.swing.JScrollBar.<init>(Unknown Source)
	at java.desktop/javax.swing.JScrollBar.<init>(Unknown Source)
	at java.desktop/javax.swing.JScrollPane$ScrollBar.<init>(Unknown Source)
	at java.desktop/javax.swing.JScrollPane.createHorizontalScrollBar(Unknown Source)
	at java.desktop/javax.swing.JScrollPane.<init>(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicComboPopup.createScroller(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicComboPopup.<init>(Unknown Source)
	at java.desktop/javax.swing.plaf.synth.SynthComboPopup.<init>(Unknown Source)
	at java.desktop/javax.swing.plaf.synth.SynthComboBoxUI.createPopup(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicComboBoxUI.installUI(Unknown Source)
	at java.desktop/javax.swing.plaf.synth.SynthComboBoxUI.installUI(Unknown Source)
	at java.desktop/javax.swing.JComponent.setUI(Unknown Source)
	at java.desktop/javax.swing.JComboBox.setUI(Unknown Source)
	at java.desktop/javax.swing.JComboBox.updateUI(Unknown Source)
	at java.desktop/javax.swing.JComboBox.init(Unknown Source)
	at java.desktop/javax.swing.JComboBox.<init>(Unknown Source)
	at dpf.sp.gpinf.indexer.desktop.MetadataPanel.<init>(MetadataPanel.java:102)
	at dpf.sp.gpinf.indexer.desktop.App.createGUI(App.java:616)
	at dpf.sp.gpinf.indexer.desktop.App$1.run(App.java:330)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by lfcnassif** [comment]
I took a quick look at code called before MetadataPanel instantiation and did some (not useful) thread dumps. Just found UI configuration code being called outside EDT in IcePDFViewer.init(), pushed changes to #989_fix branch. But that code was there since a long time ago, not sure if it is related to this...

**Comment by lfcnassif** [comment]
I wrote a script to open and close the UI several times during the night. Got more (only) 3 stacktraces on master:
InteropFactory: cannot load com.sun.javafx.embed.swing.newimpl.InteropFactoryN
```
java.lang.ClassCastException: class java.lang.Integer cannot be cast to class javax.swing.InputMap (java.lang.Integer is in module java.base of loader 'bootstrap'; javax.swing.InputMap is in module java.desktop of loader 'bootstrap')
	at java.desktop/javax.swing.plaf.basic.BasicScrollBarUI.getInputMap(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicScrollBarUI.installKeyboardActions(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicScrollBarUI.installUI(Unknown Source)
	at java.desktop/javax.swing.JComponent.setUI(Unknown Source)
	at java.desktop/javax.swing.JScrollBar.setUI(Unknown Source)
	at java.desktop/javax.swing.JScrollBar.updateUI(Unknown Source)
	at java.desktop/javax.swing.JScrollBar.<init>(Unknown Source)
	at java.desktop/javax.swing.JScrollBar.<init>(Unknown Source)
	at java.desktop/javax.swing.JScrollPane$ScrollBar.<init>(Unknown Source)
	at java.desktop/javax.swing.JScrollPane.createVerticalScrollBar(Unknown Source)
	at java.desktop/javax.swing.JScrollPane.<init>(Unknown Source)
	at java.desktop/javax.swing.JScrollPane.<init>(Unknown Source)
	at org.icepdf.ri.common.views.DocumentViewControllerImpl.<init>(DocumentViewControllerImpl.java:123)
	at org.icepdf.ri.common.SwingController.<init>(SwingController.java:288)
	at org.icepdf.ri.common.SwingController.<init>(SwingController.java:282)
	at dpf.sp.gpinf.indexer.ui.fileViewer.frames.IcePDFViewer$1.<init>(IcePDFViewer.java:78)
	at dpf.sp.gpinf.indexer.ui.fileViewer.frames.IcePDFViewer.init(IcePDFViewer.java:78)
	at dpf.sp.gpinf.indexer.ui.fileViewer.frames.ViewersRepository.init(ViewersRepository.java:75)
	at dpf.sp.gpinf.indexer.desktop.ViewerController$2.run(ViewerController.java:112)
```
```
InteropFactory: cannot load com.sun.javafx.embed.swing.newimpl.InteropFactoryN
java.lang.ClassCastException: class javax.swing.plaf.DimensionUIResource cannot be cast to class javax.swing.InputMap (javax.swing.plaf.DimensionUIResource and javax.swing.InputMap are in module java.desktop of loader 'bootstrap')
	at java.desktop/javax.swing.plaf.basic.BasicScrollBarUI.getInputMap(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicScrollBarUI.installKeyboardActions(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicScrollBarUI.installUI(Unknown Source)
	at java.desktop/javax.swing.JComponent.setUI(Unknown Source)
	at java.desktop/javax.swing.JScrollBar.setUI(Unknown Source)
	at java.desktop/javax.swing.JScrollBar.updateUI(Unknown Source)
	at java.desktop/javax.swing.JScrollBar.<init>(Unknown Source)
	at java.desktop/javax.swing.JScrollBar.<init>(Unknown Source)
	at java.desktop/javax.swing.JScrollPane$ScrollBar.<init>(Unknown Source)
	at java.desktop/javax.swing.JScrollPane.createVerticalScrollBar(Unknown Source)
	at java.desktop/javax.swing.JScrollPane.<init>(Unknown Source)
	at java.desktop/javax.swing.JScrollPane.<init>(Unknown Source)
	at org.icepdf.ri.common.views.DocumentViewControllerImpl.<init>(DocumentViewControllerImpl.java:123)
	at org.icepdf.ri.common.SwingController.<init>(SwingController.java:288)
	at org.icepdf.ri.common.SwingController.<init>(SwingController.java:282)
	at dpf.sp.gpinf.indexer.ui.fileViewer.frames.IcePDFViewer$1.<init>(IcePDFViewer.java:78)
	at dpf.sp.gpinf.indexer.ui.fileViewer.frames.IcePDFViewer.init(IcePDFViewer.java:78)
	at dpf.sp.gpinf.indexer.ui.fileViewer.frames.ViewersRepository.init(ViewersRepository.java:75)
	at dpf.sp.gpinf.indexer.desktop.ViewerController$2.run(ViewerController.java:112)
```
```
InteropFactory: cannot load com.sun.javafx.embed.swing.newimpl.InteropFactoryN
java.lang.ClassCastException: class javax.swing.plaf.nimbus.DerivedColor$UIResource cannot be cast to class javax.swing.InputMap (javax.swing.plaf.nimbus.DerivedColor$UIResource and javax.swing.InputMap are in module java.desktop of loader 'bootstrap')
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.getInputMap(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.installKeyboardActions(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicButtonUI.installKeyboardActions(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicButtonUI.installUI(Unknown Source)
	at java.desktop/javax.swing.JComponent.setUI(Unknown Source)
	at java.desktop/javax.swing.AbstractButton.setUI(Unknown Source)
	at java.desktop/javax.swing.plaf.synth.SynthArrowButton.updateUI(Unknown Source)
	at java.desktop/javax.swing.AbstractButton.init(Unknown Source)
	at java.desktop/javax.swing.JButton.<init>(Unknown Source)
	at java.desktop/javax.swing.JButton.<init>(Unknown Source)
	at java.desktop/javax.swing.plaf.synth.SynthArrowButton.<init>(Unknown Source)
	at java.desktop/javax.swing.plaf.synth.SynthScrollBarUI$1.<init>(Unknown Source)
	at java.desktop/javax.swing.plaf.synth.SynthScrollBarUI.createDecreaseButton(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicScrollBarUI.installComponents(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicScrollBarUI.installUI(Unknown Source)
	at java.desktop/javax.swing.JComponent.setUI(Unknown Source)
	at java.desktop/javax.swing.JScrollBar.setUI(Unknown Source)
	at java.desktop/javax.swing.JScrollBar.updateUI(Unknown Source)
	at java.desktop/javax.swing.JScrollBar.<init>(Unknown Source)
	at java.desktop/javax.swing.JScrollBar.<init>(Unknown Source)
	at java.desktop/javax.swing.JScrollPane$ScrollBar.<init>(Unknown Source)
	at java.desktop/javax.swing.JScrollPane.createVerticalScrollBar(Unknown Source)
	at java.desktop/javax.swing.JScrollPane.<init>(Unknown Source)
	at java.desktop/javax.swing.JScrollPane.<init>(Unknown Source)
	at org.icepdf.ri.common.views.DocumentViewControllerImpl.<init>(DocumentViewControllerImpl.java:123)
	at org.icepdf.ri.common.SwingController.<init>(SwingController.java:288)
	at org.icepdf.ri.common.SwingController.<init>(SwingController.java:282)
	at dpf.sp.gpinf.indexer.ui.fileViewer.frames.IcePDFViewer$1.<init>(IcePDFViewer.java:78)
	at dpf.sp.gpinf.indexer.ui.fileViewer.frames.IcePDFViewer.init(IcePDFViewer.java:78)
	at dpf.sp.gpinf.indexer.ui.fileViewer.frames.ViewersRepository.init(ViewersRepository.java:75)
	at dpf.sp.gpinf.indexer.desktop.ViewerController$2.run(ViewerController.java:112)
```
So seems the IcePDFViewer.init() is related, but while initializing the SwingController. I'll also put that in EDT and do more tests.

**Comment by lfcnassif** [comment]
Given the analysis results, I think this could also happen to 3.x, since the fix is simple, I'll cherry pick.
